---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: La actualización es compatible con puestas en marcha tanto de alta disponibilidad como con otras de alta disponibilidad. 
---
= Actualización de las ONTAP tools for VMware vSphere 10.x a 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar las ONTAP tools for VMware vSphere 10.3 o 10.4 a 10.5.  Sin embargo, para actualizar de las herramientas ONTAP 10.0, 10.1 o 10.2 a 10.5, primero debe actualizar a 10.3 o 10.4 antes de continuar a 10.5.

NOTA:

* Para los sistemas ASA r2, asegúrese de actualizar las ONTAP tools for VMware vSphere a 10.5 y ONTAP a 9.16.1, antes de configurar más zonas de disponibilidad de almacenamiento (SAZ).
* Si falla la actualización de las ONTAP tools for VMware vSphere 10.3 o 10.4 a 10.5, no podrá revertirla.  Utilice un RPO bajo o una recuperación de instantánea para restaurar la configuración.  Para las ONTAP tools for VMware vSphere 10.2 y versiones anteriores, utilice RPO cero para restaurar la configuración.


.Antes de empezar
* Asegúrese de que el certificado del sistema ONTAP y los certificados vCenter incorporados sean válidos durante al menos 5 días.  Si caduca antes, la actualización falla.
* Para garantizar una actualización segura, verifique que sus certificados incluyan entradas de Nombre alternativo del sujeto (SAN).  Si sus certificados carecen de entradas SAN y necesita continuar con la actualización, puede establecer el indicador de validación del certificado en falso para omitir las verificaciones de SAN en el mensaje durante la actualización.
* Asegúrese de tener un quinto disco con una capacidad de 100 GB en todos los nodos.
* Verifique que la configuración del nodo coincida con las especificaciones de la tabla siguiente.


|===
| Tipo de puesta en marcha | CPU (Core) por nodo | Memoria (GB) por nodo | Espacio en disco (GB) por nodo | Total de CPU (núcleo) | Memoria (GB) | Espacio Total en Disco (GB) 


| No alta disponibilidad pequeña | 9 | 18 | 350 | 9 | 18 | 350 


| No HA Medio | 13 | 26 | 350 | 13 | 26 | 350 


| HA pequeña | 9 | 18 | 350 | 27 | 54 | 1050 


| ALTA disponibilidad media | 13 | 26 | 350 | 39 | 78 | 1050 


| ALTA disponibilidad | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Asegúrese de que la conexión en caliente para CPU y RAM esté habilitada.
* Para las ONTAP tools for VMware vSphere 10.3 o 10.4, tome una instantánea inactiva en la máquina virtual de las herramientas ONTAP antes de actualizar.
* Habilite la copia de seguridad con RPO bajo y asegúrese de que haya una copia de seguridad visible en la interfaz del cliente vCenter.


.Pasos
. Cargue ISO de las herramientas de ONTAP para la actualización de VMware vSphere a la biblioteca de contenido.
. En la página principal de VM, seleccione *Acciones* > *Editar configuración*
. Seleccione el *archivo ISO de la biblioteca de contenido* en la ventana de edición de configuraciones, debajo del campo *Unidad de CD/DVD*.
. Seleccione el archivo ISO, marque la casilla *Conectado* para el campo *Unidad de CD/DVD* y haga clic en *Aceptar*.
. Desde vCenter Server, abra una consola a las herramientas de ONTAP.
. Inicie sesión como el usuario de mantenimiento.
. Introduzca *3* para seleccionar el menú *Configuración del sistema*.
. Introduzca *7* para seleccionar la opción *Actualizar*.
+
Durante la actualización, si alguno de los certificados de backend de almacenamiento incorporados no tiene entradas de Nombre alternativo del sujeto (SAN), recibirá un mensaje indicando el SAN faltante.  Si decide continuar sin validar la SAN, la actualización continuará, pero esto no se recomienda debido a posibles riesgos de seguridad.

. Al actualizar, las siguientes acciones se realizan automáticamente:
+
.. El certificado de puerta de enlace se renueva con un periodo de validez de 1 año.  Cuando elimina el adaptador SRA anterior y carga el nuevo adaptador 10.5, la validez del certificado SRA cambia de 10 años a 1 año.
.. El complemento remoto se ha actualizado
.. Los certificados de ONTAP y vCenter Server se validan y se agregan a las herramientas de ONTAP
.. La copia de seguridad está habilitada




.El futuro
Después de actualizar a las ONTAP tools for VMware vSphere 10.5:

* Supervise las alertas del sistema y planifique la renovación del certificado de puerta de enlace antes de que caduque en un año.
* Elimine el adaptador SRA de las herramientas ONTAP 10.4 o 10.3 y cargue el archivo tar del adaptador SRA 10.5.  Luego, vuelva a escanear los adaptadores SRA para actualizar la página Adaptadores de replicación de almacenamiento de VMware Site Recovery.


Después de actualizar podrás:

* Desactive los servicios desde la interfaz de usuario del administrador
* Pase de una configuración no de alta disponibilidad a una configuración de alta disponibilidad
* Amplíe una configuración pequeña sin alta disponibilidad a una configuración mediana sin alta disponibilidad, o a una configuración mediana o grande con alta disponibilidad.


.Información relacionada
link:../migrate/migrate-to-latest-ontaptools.html["Migrar de las ONTAP tools for VMware vSphere 9.xx a 10.5"]
