---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade, ONTAP tools, VMware vSphere, HA, non-HA, low RPO backup, SRA adapter, vCenter Server 
summary: Actualiza ONTAP tools for VMware vSphere de la versión 10.4 o 10.5 a la 10.6 para implementaciones HA y no HA usando los pasos necesarios de comprobación previa y copia de seguridad. 
---
= Actualiza desde ONTAP tools for VMware vSphere 10.x a 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes actualizar directamente ONTAP tools for VMware vSphere 10.4 o 10.5 a 10.6. Para actualizar desde ONTAP tools 10.0, 10.1, 10.2 o 10.3 a 10.6, primero actualiza a 10.4 o 10.5.

[NOTE]
====
* Para los sistemas ASA r2, asegúrate de actualizar ONTAP tools for VMware vSphere a 10.6 y ONTAP a 9.16.1 antes de configurar más zonas de disponibilidad de almacenamiento (SAZ).
* Si la actualización de ONTAP tools for VMware vSphere 10.4 o 10.5 a 10.6 falla, no puedes revertirla. Usa un RPO bajo o la recuperación mediante instantáneas para restaurar la configuración. Para ONTAP tools for VMware vSphere 10.3 y anteriores, usa RPO cero para restaurar la configuración. Después de restaurar en entornos protegidos, vuelve a validar la protección del datastore y verifica el estado y las relaciones del grupo de protección.


====
.Antes de empezar
* Asegúrate de que todos los nodos estén activos antes de iniciar la actualización.
* Asegúrese de que el certificado del sistema ONTAP y los certificados vCenter incorporados sean válidos durante al menos 5 días. Si los certificados caducan antes, la actualización falla.
* Asegúrese de tener un quinto disco con una capacidad de 100 GB en todos los nodos.
* Verifique que la configuración del nodo coincida con las especificaciones de la tabla siguiente.


|===
| Tipo de despliegue | Núcleos de CPU por nodo | Memoria (GB) por nodo | Espacio en disco (GB) por nodo | Número total de núcleos de CPU | Memoria total (GB) | Espacio total en disco (GB) 


| No alta disponibilidad pequeña | 9 | 18 | 350 | 9 | 18 | 350 


| No HA Medio | 13 | 26 | 350 | 13 | 26 | 350 


| HA pequeña | 9 | 18 | 350 | 27 | 54 | 1050 


| ALTA disponibilidad media | 13 | 26 | 350 | 39 | 78 | 1050 


| ALTA disponibilidad | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Activa la copia de seguridad con un RPO bajo y asegúrate de que haya una copia de seguridad visible en la interfaz de vSphere Client. Descarga la carpeta de copia de seguridad antes de la actualización.
* Se recomienda una copia de seguridad con un RPO bajo.  Sin embargo, en una implementación que no sea de alta disponibilidad, puede tomar una instantánea inactiva de la máquina virtual de herramientas ONTAP antes de actualizar.
+
Referirse a link:../manage/backup-settings.html["Editar la configuración de la copia de seguridad"] y link:../manage/recover-backup.html["Recuperar la configuración de las herramientas ONTAP"] Para obtener más información sobre copias de seguridad y recuperación.



.Pasos
. Cargue ISO de las herramientas de ONTAP para la actualización de VMware vSphere a la biblioteca de contenido.
. En la página principal de la máquina virtual, seleccione *Acciones* > *Editar configuración*. Para identificar el nombre de la máquina virtual principal:
+
.. Habilitar el shell de diagnóstico en cualquier nodo
.. Ejecuta el siguiente comando:
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. Seleccione el *archivo ISO de la biblioteca de contenido* en la ventana de edición de configuraciones, debajo del campo *Unidad de CD/DVD*.
. Seleccione el archivo ISO, marque la casilla *Conectado* para el campo *Unidad de CD/DVD* y haga clic en *Aceptar*.
. Inicia sesión en el servidor vCenter.
. Localiza la máquina virtual principal de ONTAP tools e inicia la consola web.
. Inicia sesión usando las credenciales de `maint`.
. Introduzca *2* para seleccionar el menú *Configuración del sistema*.
. Teclea *6* para seleccionar la opción *Upgrade*.
. Proporciona las credenciales de vCenter cuando se te solicite. Esta es la instancia de vCenter donde se alojan las ONTAP tools.
+
Si estás usando las herramientas ONTAP en una topología de dos vCenter Server, donde el appliance se aloja en una instancia de vCenter y gestiona otra, puedes asignar un rol restringido para la instancia de vCenter que aloja las herramientas ONTAP. Puedes crear un usuario y un rol dedicados de vCenter con solo los permisos necesarios para el despliegue de plantillas OVF. Para más detalles, consulta los roles listados en link:../concepts/rbac-vcenter-use.html#vsphere-object-hierarchy["Roles incluidos con las herramientas de ONTAP para VMware vSphere 10"].

+
Para la instancia de vCenter que será administrada por las herramientas de ONTAP , asegúrese de que la cuenta de usuario de vCenter tenga privilegios de administrador.

+
Durante la actualización, si alguno de los certificados de backend de almacenamiento incorporados no tiene entradas de Nombre alternativo del sujeto (SAN), recibirá un mensaje indicando el SAN faltante.  Si decide continuar sin validar la SAN, la actualización continuará, pero esto no se recomienda debido a posibles riesgos de seguridad.

. Al actualizar, las siguientes acciones se realizan automáticamente:
+
.. El certificado de la puerta de enlace se renueva con un periodo de validez de un año. Al eliminar el adaptador SRA anterior y subir el nuevo adaptador 10.6, la validez del certificado SRA pasa de 10 años a 1 año.
.. El complemento remoto se ha actualizado
.. Los certificados de ONTAP y vCenter Server se validan y se agregan a las herramientas de ONTAP
.. La copia de seguridad está habilitada
.. Si existen ajustes de protección del clúster de host de la versión 10.5 o anteriores, ONTAP tools crea un elemento de navegación independiente denominado *Configuración de protección del clúster* durante la actualización.




.El futuro
Después de actualizar a ONTAP tools for VMware vSphere 10.6:

* Supervise las alertas del sistema y planifique la renovación del certificado de puerta de enlace antes de que caduque en un año.
* Elimina el adaptador SRA de ONTAP tools 10.4 o 10.5 y carga el archivo tar del adaptador SRA 10.6.
* Ejecute el comando de instalación después de cargar el archivo tar del adaptador SRA. Luego, vuelva a escanear los adaptadores SRA para actualizar la página Adaptadores de replicación de almacenamiento de VMware Site Recovery.
* Abre *Cluster protection configuration* y verifica que los ajustes de protección de clúster de los hosts existentes estén presentes y mapeados correctamente.


Después de actualizar podrás:

* Desactivar servicios desde ONTAP tools Manager
* Pase de una configuración no de alta disponibilidad a una configuración de alta disponibilidad
* Amplíe una configuración pequeña sin alta disponibilidad a una configuración mediana sin alta disponibilidad, o a una configuración mediana o grande con alta disponibilidad.


.Información relacionada
link:../migrate/migrate-to-latest-ontaptools.html["Migra desde ONTAP tools for VMware vSphere 9.x a 10.6"]
