---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: ONTAP tools migration, vVols migration, VMware vSphere, NFS datastores, VMFS datastores 
summary: Migra ONTAP tools for VMware vSphere 9.xx a 10.6 eligiendo una ruta según si usas almacenes de datos vVols. 
---
= Migra desde ONTAP tools for VMware vSphere 9.xx a 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La migración desde ONTAP tools for VMware vSphere 9.xx a 10.6 requiere diferentes pasos según tus tipos de datastore.

Puedes migrar desde ONTAP tools for VMware vSphere 9.12D1, 9.13D2 y 9.13P2 a ONTAP tools for VMware vSphere 10.6.

Si tu configuración tiene almacenes de datos NFS y VMFS y no tiene almacenes de datos vVols, desinstala ONTAP tools 9.xx y despliega ONTAP tools 10.6. Si tu configuración contiene almacenes de datos vVols, migra el VASA Provider y el SRA.

La siguiente tabla describe el proceso de migración en estos dos escenarios diferentes.

|===
| *Si la configuración tiene almacenes de datos vVols* | *Si la configuración solo contiene almacenes de datos NFS y VMFS* 


| Pasos: 1. link:../migrate/sra-vasa-migration.html["Migrar el proveedor VASA"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Crear políticas de almacenamiento de máquinas virtuales"] | Pasos: 1. Elimina ONTAP tools 9.xx de tu entorno. Consulta  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["Cómo eliminar OTV 9.xx de tu entorno"] en la base de conocimientos de NetApp. 2. link:../deploy/quick-start.html["Implementa y configura ONTAP tools for VMware vSphere 10.6"] 3. link:../migrate/sra-vasa-migration.html["Actualice el SRA"] 4. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Crear políticas de almacenamiento de máquinas virtuales"] 
|===

NOTE: Después de migrar de ONTAP tools for VMware vSphere 9.xx a 10.6, los almacenes de datos vVols que usan el protocolo NVMe/FC dejan de funcionar porque ONTAP tools 10.6 solo admite el protocolo NVMe-oF con almacenes de datos VMFS.



[[after-migration]]
== Tras la migración

Comprueba lo siguiente:

* Los almacenes de datos son accesibles desde vCenter Server.
* Las políticas de almacenamiento de las máquinas virtuales se asignan como se espera.
* El estado de protección y replicación muestra que todo está en orden para los almacenes de datos configurados.

