---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: Cuando se migran datos de almacenamiento, los back-ends de almacenamiento se incorporan manualmente mediante las API DE REST. Cuando se migran datos del proveedor VASA, los datos se exportan desde la base de datos de Derby existente e se importan a la base de datos MongoDB. 
---
= Migra el proveedor VASA y actualiza el SRA en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga los pasos de esta sección para migrar el proveedor VASA de las ONTAP tools for VMware vSphere 9.xx a las ONTAP tools for VMware vSphere 10.5 y actualizar el adaptador de replicación de almacenamiento (SRA) en el dispositivo VMware Live Site Recovery.



== Pasos para migrar el proveedor VASA

. Para habilitar EL PUERTO 1527 de Derby en las herramientas de ONTAP existentes para VMware vSphere, habilite el usuario raíz e inicie sesión en la interfaz de línea de comandos mediante SSH. A continuación, ejecute el siguiente comando:
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. Implementar OVA para ONTAP tools for VMware vSphere 10.5.
. Agregue la instancia de vCenter Server que desea migrar a las ONTAP tools for VMware vSphere 10.5. Consulte link:../configure/add-vcenter.html["Agregue una instancia de vCenter Server"] Para más información.
. link:../manage/enable-services.html["Habilite el proveedor de VASA"]Servicio en ONTAP tools for VMware vSphere 10.5.
. Incorpore el backend de almacenamiento localmente desde las API de vCenter Server para el complemento de herramientas de ONTAP . Consultelink:../configure/add-storage-backend.html["Agregue un backend de almacenamiento mediante la interfaz del cliente vSphere"] Para más información.
. Obtenga un token de acceso para autenticar solicitudes de API REST.  Utilice el siguiente ejemplo, reemplazando las variables con valores específicos de su entorno.
+
[source, curl]
----
curl --request POST \
  --location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/vcenter-login" \
  --header "Content-Type: application/json" \
  --header "Accept: */*" \
  -d '{"username": "$MYUSER", "password": "$MYPASSWORD"}'
----
+
Copie y guarde el token de acceso devuelto en la respuesta.

. Emita la siguiente API desde Swagger o en Postman para migrar.
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
Puedes acceder a Swagger a través de esta URL: `\https://$FQDN_IP_PORT/` , Por ejemplo: `\https://10.67.25.33:8443/` .

+
[]
====
*Método HTTP y punto final*

Esta llamada a la API de REST utiliza el siguiente método y extremo.

|===


| *Método HTTP* | *Ruta* 


| PUBLICAR | /api/v1 
|===
*Tipo de procesamiento*

Asíncrona

*Ejemplo de Curl*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
  --header 'x-auth: <auth_token>' \
  --header 'Content-Type: application/json' \
  --data '{
    "otv_ip": "xx.xx.xx.xx",
    "vasa_provider_credentials": {
      "username": "xxxxx",
      "password": "******"
    },
    "database_password": "******"
  }'
----
Cuerpo de solicitud para otra migración de versiones:

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
*Ejemplo de salida JSON*

El sistema devuelve un objeto de trabajo.  Guarde el identificador de trabajo para usarlo en el siguiente paso.

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Use el siguiente URI en Swagger para comprobar el estado:
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobId>?includeSubJobsAndTasks=true`
----
+
Usa el valor 'id' devuelto por el trabajo de migración en el paso anterior. Después de que el trabajo termine, revisa el informe de migración en la respuesta del trabajo.

. Agregue las ONTAP tools for VMware vSphere al vCenter Server.
. Registre el proveedor VASA con ONTAP tools for VMware vSphere. Para obtener instrucciones, consultelink:../configure/registration-process.html["Registre el proveedor de VASA de"] .
. Verifica el registro del proveedor VASA:
+
.. En el vSphere Client, ve al vCenter Server.
.. Selecciona *Configurar* > *Proveedores de almacenamiento*.
.. Confirma que el VASA Provider registrado en el paso anterior aparece en línea.


. Detenga el servicio del proveedor VASA de las ONTAP tools for VMware vSphere 9.10/9.11/9.12/9.13 mediante estos pasos:
+
.. En las herramientas ONTAP 9.x, abra la consola web.
.. Acceda a la consola de mantenimiento.
.. Ingresar `1` para seleccionar el menú *Configuración de la aplicación*.
.. Ingresar `5` para detener los servicios del Proveedor VASA y SRA.
.. En el vSphere Client, ve al vCenter Server y selecciona *Configurar* > *Proveedores de almacenamiento*.
.. Selecciona el VASA Provider offline para ONTAP tools 9.x y selecciona *Remove*.
+
Tras detener el antiguo proveedor VASA, vCenter Server conmuta por error a las ONTAP tools for VMware vSphere. Todos los almacenes de datos y máquinas virtuales se vuelven accesibles y se sirven desde las ONTAP tools for VMware vSphere.



. Los almacenes de datos NFS y VMFS migrados aparecen en las ONTAP tools for VMware vSphere 10.5 después del trabajo de descubrimiento del almacén de datos, que puede demorar hasta 30 minutos.  Compruebe su visibilidad en la página de descripción general.
. Realice la migración de parches mediante la siguiente API en Swagger o en Postman:
+
[]
====
*Método HTTP y punto final*

Esta llamada a la API de REST utiliza el siguiente método y extremo.

|===


| *Método HTTP* | *Ruta* 


| PARCHE | /api/v1 
|===
*Tipo de procesamiento*

Asíncrona

Utilice la siguiente URI en Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Método HTTP y punto final*

Esta llamada a la API de REST utiliza el siguiente método y extremo.

|===


| *Método HTTP* | *Ruta* 


| PARCHE | /api/v1 
|===
*Tipo de procesamiento*

Asíncrona

Utilice la siguiente URI en Swagger:

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/<vcenter_id>/migration-jobs/<migration_id>`
----
*Ejemplo de Curl*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/d50073ce-35b4-4c51-9d2e-4ce66f802c35`
----
*Ejemplo de salida JSON*

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
+

NOTE: Usa el valor 'migration_id' devuelto en el paso 7 como <migration_id> en la llamada a la API PATCH. El cuerpo de la solicitud está vacío para la operación patch.

+

NOTE: UUID es el UUID de migración devuelto en respuesta a la API posterior a la migración.



Después de ejecutar la API de migración de revisiones, todas las máquinas virtuales cumplen con la normativa de almacenamiento.

.El futuro
Después de completar la migración y registrar las herramientas ONTAP 10.5 en vCenter Server, siga estos pasos:

* Espere a que se complete el *Descubrimiento* y el sistema actualice los certificados automáticamente en todos los hosts.
* Espere antes de iniciar las operaciones del almacén de datos y de la máquina virtual.  El tiempo de espera depende de la cantidad de hosts, almacenes de datos y máquinas virtuales.  Si no esperas, es posible que veas fallos ocasionales.


Después de la actualización, si el estado de cumplimiento de la máquina virtual es obsoleto, vuelva a aplicar la política de almacenamiento siguiendo los pasos siguientes:

. Vaya al almacén de datos y seleccione *Resumen* > *Políticas de almacenamiento de VM*.
. El sistema muestra el estado de cumplimiento en *Cumplimiento de la política de almacenamiento de VM* como *Desactualizado*.
. Seleccione la política de VM de almacenamiento y la VM correspondiente.
. Seleccione *Aplicar*.
. El estado de cumplimiento bajo *Cumplimiento de la política de almacenamiento de VM* se muestra como compatible.


.Información relacionada
* link:../concepts/rbac-learn-about.html["Obtenga más información sobre las herramientas de ONTAP para el control de acceso basado en roles de VMware vSphere 10"]
* link:../upgrade/upgrade-ontap-tools.html["Actualización de las ONTAP tools for VMware vSphere 10.x a 10.5"]




== Pasos para actualizar el adaptador de replicación de almacenamiento (SRA)

.Antes de empezar
En el plan de recuperación, el sitio protegido se refiere a la ubicación donde se ejecutan las máquinas virtuales, mientras que el sitio de recuperación es donde se recuperarán. La interfaz del dispositivo VMware Live Site Recovery muestra el estado del plan de recuperación con detalles sobre los sitios protegidos y de recuperación.  En el plan de recuperación, los botones LIMPIAR y REPROTEGER están deshabilitados, mientras que los botones PROBAR y EJECUTAR permanecen habilitados. Esto indica que el sitio está preparado para la recuperación de datos. Antes de migrar el SRA, verifique que un sitio esté en estado protegido y el otro en estado de recuperación.


NOTE: No comience la migración si se ha completado la conmutación por error pero la re-protección está pendiente.  Asegúrese de que el proceso de re-protección se haya completado antes de continuar con la migración.  Si hay una conmutación por error de prueba en curso, limpie la conmutación por error de prueba e inicie la migración.

. Siga estos pasos para eliminar el adaptador del SRA de herramientas de ONTAP para VMware vSphere 9.xx en VMware Site Recovery:
+
.. Vaya a la página de gestión de configuración de VMware Live Site Recovery
.. Vaya a la sección *Storage Replication Adapter*.
.. En el menú de puntos suspensivos, seleccione *Restablecer configuración*.
.. En el menú de puntos suspensivos, seleccione *Eliminar*.


. Lleve a cabo estos pasos en sitios de protección y recuperación.
+
.. link:../manage/enable-services.html["Habilite herramientas de ONTAP para los servicios de VMware vSphere"]
.. Configure las ONTAP tools for VMware vSphere 10.5 SRA siguiendo los pasos que se indican enlink:../protect/configure-on-srm-appliance.html["Configure el SRA en el dispositivo VMware Live Site Recovery"] .
.. En la interfaz de VMware Live Site Recovery, ejecute *Discover Arrays* y *Discover Devices*.  Confirme que los dispositivos se muestren como antes de la migración.



