---
permalink: deploy/deployment-error-codes.html 
sidebar: sidebar 
keywords: upgrade 
summary: En esta página se describen los códigos de error para las operaciones de implementación, reinicio y recuperación de las herramientas de ONTAP para el sistema VMware vSphere. 
---
= Soluciona errores de despliegue de ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si experimenta problemas de implementación, revise los registros y los códigos de error para diagnosticar y resolver los problemas.  A partir de las ONTAP tools for VMware vSphere 10.5, los paquetes de registros recopilados de los pods incluyen registros de MongoDB, RabbitMQ y Vault, junto con el estado y las descripciones de todos los pods.  Estos se proporcionan además de los registros de servicio de las herramientas ONTAP existentes, lo que mejora la capacidad de soporte y la resolución de problemas.



== Recoja los archivos de registro

Puede recoger archivos de registro para las herramientas de ONTAP para VMware vSphere desde las opciones disponibles en la interfaz de usuario del gestor de herramientas de ONTAP. Es posible que el soporte técnico le solicite recoger los archivos de registro que sirven como ayuda para la solución de un problema.


NOTE: La generación de registros desde el Administrador de herramientas de ONTAP incluye todos los registros para todas las instancias de vCenter Server. Los registros de generación desde la interfaz de usuario del cliente de vCenter se incluyen en la instancia de vCenter Server seleccionada.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *Log Bundles* en la barra lateral.
+
Esta operación puede llevar varios minutos.

. Seleccione *Generar* para generar los archivos de registro.
. Ingrese la etiqueta para el paquete de registro y seleccione *Generar*.
+
Descargue el archivo tar.gz y envíelo al soporte técnico.



Siga los pasos a continuación para generar paquete de registros con la interfaz de usuario del cliente de vCenter:

.Pasos
. Inicie sesión en el cliente de vSphere.
. En la página de inicio de vSphere Client, vaya a *Support* > *Log bundle* > *Generar*.
. Proporcione la etiqueta del paquete de registro y genere el paquete. Podrá ver la opción de descarga cuando se generen los archivos. La descarga puede tardar un poco.



NOTE: El paquete de logs generado sustituye el paquete de logs generado en los últimos 3 días o 72 horas.



== Códigos de error de despliegue

Es posible que aparezcan códigos de error durante las herramientas de ONTAP para operaciones de implementación, reinicio y recuperación de VMware vSphere.
Los códigos de error tienen una longitud de cinco dígitos, donde los dos primeros dígitos representan el script que encontró el problema, y los tres últimos dígitos representan el flujo de trabajo específico dentro de ese script.

Todos los registros de errores se graban en el archivo ansible-perl-errors.log en el directorio /var/log para facilitar el seguimiento y la resolución de problemas.  Este archivo de registro contiene el código de error y la tarea de Ansible fallida.


NOTE: Los códigos de error proporcionados en esta página son sólo de referencia. Póngase en contacto con el equipo de soporte si el error persiste o si no se menciona ninguna solución.

En la siguiente tabla se enumeran los códigos de error y los nombres de archivo correspondientes.

|===


| *Código de error* | *Nombre del script* 


| 00 | firstboot-network-config.pl, despliegue del modo 


| 01 | firstboot-network-config.pl, actualización del modo 


| 02 | firstboot-inputs-validation.pl 


| 03 | firstboot-deploy-otv-ng.pl: Puesta en marcha, alta disponibilidad 


| 04 | firstboot-deploy-otv-ng.pl TB, puesta en marcha, no alta disponibilidad 


| 05 | firstboot-deploy-otv-ng.pl, reiniciar 


| 06 | firstboot-deploy-otv-ng.pl, actualización, alta disponibilidad 


| 07 | firstboot-deploy-otv-ng.pl, actualización, no alta disponibilidad 


| 08 | firstboot-otv-recovery.pl 


| 09 | post-deploy-upgrade.pl 
|===
Los últimos tres dígitos del código de error indican el error de flujo de trabajo específico dentro del script:

|===


| *Código de error de implementación* | *Flujo de trabajo* | *Resolución* 


| 049 | Para la red y el script de perl de validación también los asignará en breve | - 


| 050 | Fallo al generar la clave SSH | Reiniciar la máquina virtual primaria (VM). 


| 053 | Error al instalar RKE2 | Ejecute lo siguiente y reinicie el equipo virtual principal o vuelva a ponerlo en marcha:
Sudo rke2-killall.sh (todas las máquinas virtuales)
Sudo rke2-uninstall.sh (todas las máquinas virtuales). 


| 054 | Fallo al definir kubeconfig | Volver a desplegar 


| 055 | Fallo al desplegar el registro | Si el pod del registro está presente, espere a que el pod esté listo y, a continuación, reinicie la VM principal o vuelva a implementarla. 


| 059 | El despliegue de KubeVip ha fallado | Asegúrese de que la dirección IP virtual para el plano de control de Kubernetes y la dirección IP de las herramientas de ONTAP proporcionada durante la implementación pertenezcan a la misma VLAN y sean direcciones IP libres. Reinicie si todos los puntos anteriores son correctos. De lo contrario, vuelva a desplegar. 


| 060 | Fallo en el despliegue del operador | Reinicie 


| 061 | Fallo en el despliegue de servicios | Realice la depuración básica de Kubernetes como los pods GET, GET rs, GET svc, etc. en el espacio de nombres ntv-SYSTEM para obtener más detalles y registros de errores en /var/log/ansible-perl-errors.log y /var/log/ansible-run.log y vuelva a desplegar. 


| 062 | Se ha producido un error en la implementación de ONTAP TOOLS Services | Consulte los registros de errores en /var/log/ansible-perl-errors.log para obtener más detalles y volver a desplegar. 


| 065 | No se puede acceder a la URL de la página de Swagger | Volver a desplegar 


| 066 | Se ha producido un error en los pasos posteriores al despliegue del certificado de gateway | Realice lo siguiente para recuperar/completar la actualización: * Habilitar shell de diagnóstico. * Ejecutar el comando 'sudo perl /home/maint/scripts/post-deploy-upgrade.pl --postDeploy'. * Compruebe los registros en /var/log/post-deploy-upgrade.log. 


| 088 | Fallo al configurar la rotación de log para el diario | Compruebe la configuración de red de la máquina virtual compatible con el host en el que se aloja la máquina virtual. Puede intentar migrar a otro host e intentar reiniciar la máquina virtual. 


| 089 | Fallo al cambiar la propiedad del archivo de configuración de rotación de registro de resumen | Reiniciar la máquina virtual principal. 


| 096 | Instale el aprovisionador de almacenamiento dinámico | - 


| 108 | Fallo al iniciar el script | - 
|===
|===


| *Reiniciar código de error* | *Flujo de trabajo* | *Resolución* 


| 067 | Se ha agotado el tiempo de espera de rke2-server. | - 


| 101 | Fallo al restablecer la contraseña de usuario de mantenimiento/consola. | - 


| 102 | Error al eliminar el archivo de contraseñas durante el restablecimiento de la contraseña de usuario de Maint/Console. | - 


| 103 | Error al actualizar la nueva contraseña de usuario de mantenimiento/consola en el almacén. | - 


| 088 | Fallo al configurar la rotación de log para el diario. | Compruebe la configuración de red de la máquina virtual compatible con el host en el que se aloja la máquina virtual. Puede intentar migrar a otro host e intentar reiniciar la máquina virtual. 


| 089 | Fallo al cambiar la propiedad del archivo de configuración de rotación de registro de resumen. | Reinicie VM. 
|===