---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: Puede configurar HA en configuraciones pequeñas, medianas o grandes. 
---
= Implemente una configuración de alta disponibilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar tres nodos de alta disponibilidad en configuraciones pequeñas, medianas o grandes. La IMPLEMENTACIÓN de ALTA DISPONIBILIDAD usa Trident para almacenar los datos de servicios.

* Tres nodos pequeños de alta disponibilidad contienen 8 CPU y 16 GB de RAM por nodo.
* Tres nodos de alta disponibilidad media contienen 12 CPU y 24 GB de RAM por nodo.
* Tres nodos de alta disponibilidad grandes contienen 16 CPU y 32 GB de RAM por nodo.


*Antes de empezar*

Esta tarea le da instrucciones sobre cómo instalar tres nodos HA en configuraciones pequeñas, medianas o altas.


NOTE: La creación de la biblioteca de contenido es un paso obligatorio para implementar la configuración de tres nodos de alta disponibilidad. Consulte link:../deploy/download-ontap-tools.html["Crear biblioteca de contenido"]la sección para conocer el procedimiento. Para obtener más información, consulte https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Creación y Uso de la Biblioteca de Contenido"] el blog.

Asegúrese de haber importado el OVA a la biblioteca de contenido. Mantenga a mano el nombre de la biblioteca de contenido y el nombre del elemento de la biblioteca que ha proporcionado al elemento OVA.


NOTE: Antes de continuar con el despliegue, establezca el planificador de recursos distribuidos (DRS) del cluster en el inventario en 'Conservador' durante la instalación de las herramientas de ONTAP. Esto garantiza que los equipos virtuales no se migren durante la instalación.

* Pasos*

. Inicie sesión en vSphere Server.
. Desplácese hasta el pool de recursos que haya creado o hasta el clúster o hasta el host donde desea implementar el OVA.
. Haga clic con el botón derecho en la ubicación requerida y seleccione *Implementar plantilla OVF...*.
+

NOTE: No implemente herramientas de ONTAP para máquinas virtuales VMware vSphere en un almacén de datos vVols que gestiona.

. Seleccione el archivo OVA a través de la URL del archivo _.ova_ o vaya a la carpeta donde se guarda el archivo _.ova_ y, a continuación, haga clic en *Siguiente*.
. Para implementar herramientas de ONTAP para VMware vSphere desde la biblioteca de contenido:
+
.. Vaya a la biblioteca de contenidos y haga clic en el elemento de biblioteca que desea desplegar.
.. Haga clic en *Acciones* > *Nueva VM desde esta plantilla*


. Seleccione un recurso informático y haga clic en *Siguiente*.
. Revise los detalles de la plantilla y haga clic en *Siguiente*.
. Lea y acepte el contrato de licencia y haga clic en *Siguiente*.
. Seleccione la configuración de implementación y haga clic en *Siguiente*.
. Seleccione el almacenamiento para la configuración y los archivos de disco y haga clic en *Siguiente*.
. Seleccione la red de destino para cada red de origen y haga clic en *Siguiente*.
. En la ventana *Personalizar plantilla*, rellena los campos requeridos y haz clic en *Siguiente*.
+
** Cuando el ámbito de SVM está habilitado, debe haber habilitado la compatibilidad de SVM con la dirección IP de gestión.
** La información proporcionada aquí se valida para los patrones adecuados durante el proceso de instalación. En caso de discrepancia, se muestra un mensaje de error en la consola web y se le solicita que corrija cualquier información incorrecta proporcionada.
** Los nombres de host deben consistir en letras mayúsculas (A-Z), letras minúsculas (a-z), dígitos (0-9) o el guión (-) carácter especial. Si desea configurar la pila doble, especifique el nombre de host asignado a la dirección IPv6.


. Revise los detalles en la ventana *Listo para completar*, seleccione *Finalizar*.
+
A medida que se crea la tarea de implementación, el progreso se muestra en la barra de tareas de vSphere.

. Encienda la máquina virtual después de completar la tarea.
+
Comienza la instalación. Puede realizar un seguimiento del progreso de la instalación en la consola web de VM. Como parte de la instalación, se validan las configuraciones de los nodos. Se validan las entradas proporcionadas en diferentes secciones de la plantilla Personalizar en el formulario OVF. En el caso de discrepancias, un cuadro de diálogo le solicita que realice una acción correctiva.

. Realice los cambios necesarios en el indicador de diálogo. Utilice el botón Tab para navegar por el panel y seleccione *OK*.
+
Los valores proporcionados se validan de nuevo. Las herramientas de ONTAP para VMware vSphere permiten corregir tres intentos cualquier valor no válido. Si no puede corregir los problemas después de tres intentos, la instalación del producto se detiene y se recomienda que intente la instalación en una máquina virtual nueva.



Después de la instalación correcta, la consola web muestra el estado de las herramientas de ONTAP para VMware vSphere.
