---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: Se puede configurar un solo nodo que no sea de alta disponibilidad en configuraciones pequeñas o medianas. 
---
= Implemente una configuración de un solo nodo que no sea de alta disponibilidad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se puede poner en marcha una configuración sin nodo de alta disponibilidad en una configuración pequeña o mediana.

* La configuración pequeña que no es de alta disponibilidad contiene 8 CPU y 16 GB de RAM.
* La configuración media sin alta disponibilidad contiene 12 CPU y 24 GB de RAM.


*Antes de empezar*

Asegúrese de que la ruta de red esté presente. La red de datos de almacenamiento debe ser accesible desde la red de gestión de equipos virtuales. Por ejemplo, inicie sesión en ONTAP > ejecute el comando _network route create -vserver <SVM> -destination 0,0.0.0/0 -gateway <gateway_ip>_

* Pasos*

. Inicie sesión en vSphere Server.
. Desplácese hasta el pool de recursos que haya creado o hasta el clúster o hasta el host donde desea implementar el OVA.
. Haga clic con el botón derecho en la ubicación requerida y seleccione *Implementar plantilla OVF...*.
+

NOTE: No implemente herramientas de ONTAP para máquinas virtuales VMware vSphere en un almacén de datos vVols que gestiona.

. Seleccione el archivo OVA a través de la URL del archivo _.ova_ o vaya a la carpeta donde se guarda el archivo _.ova_ y, a continuación, haga clic en *Siguiente*.
. Seleccione un recurso informático y haga clic en *Siguiente*.
. Revise los detalles de la plantilla y haga clic en *Siguiente*.
. Lea y acepte el contrato de licencia.
. Seleccione la configuración de implementación y haga clic en *Siguiente*.
+
Las opciones de implementación avanzada utilizan Trident como aprovisionador de almacenamiento dinámico para ONTAP para crear volúmenes y la sencilla puesta en marcha utiliza almacenamiento local para crear volúmenes.

. Seleccione el almacenamiento para la configuración y los archivos de disco y haga clic en *Siguiente*.
. Seleccione la red de destino para cada red de origen y haga clic en *Siguiente*.
. En la plantilla *Personalizar*, ingresa los detalles requeridos y haz clic en *Siguiente*
+
** Cuando el ámbito de SVM está habilitado, debe haber habilitado la compatibilidad de SVM con la dirección IP de gestión.
** La información proporcionada aquí se valida para los patrones adecuados durante el proceso de instalación. En caso de discrepancia, se muestra un mensaje de error en la consola web y se le solicita que corrija cualquier información incorrecta proporcionada.
** Los nombres de host deben consistir en letras mayúsculas (A-Z), letras minúsculas (a-z), dígitos (0-9) o el guión (-) carácter especial. Si desea configurar la pila doble, especifique el nombre de host asignado a la dirección IPv6.


. Revise los detalles en la ventana *Listo para completar*, seleccione *Finalizar*.
+
A medida que se crea la tarea de implementación, el progreso se muestra en la barra de tareas de vSphere.

. Encienda la máquina virtual después de completar la tarea.
+
Comienza la instalación. Puede realizar un seguimiento del progreso de la instalación en la consola web de VM. Como parte de la instalación, se validan las configuraciones de los nodos. Se validan las entradas proporcionadas en diferentes secciones de la plantilla Personalizar en el formulario OVF. En caso de discrepancias, un cuadro de diálogo le solicita que realice una acción correctiva.

. Realice los cambios necesarios en el indicador de diálogo. Utilice el botón Tab para navegar por el panel y seleccione *OK*.
+
Los valores proporcionados se validan de nuevo. Las herramientas de ONTAP para VMware vSphere permiten corregir tres intentos cualquier valor no válido. Si no puede corregir los problemas después de tres intentos, la instalación del producto se detiene y se recomienda que intente la instalación en una máquina virtual nueva.



Después de la instalación correcta, la consola web muestra el estado de las herramientas de ONTAP para VMware vSphere.
