---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: Las herramientas de ONTAP para el dispositivo VMware vSphere siempre se ponen en marcha como nodo individual de pequeño tamaño y servicios principales para admitir almacenes de datos NFS/VMFS. 
---
= Ponga en marcha herramientas de ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para el dispositivo VMware vSphere siempre se ponen en marcha como nodo individual de pequeño tamaño y servicios principales para admitir almacenes de datos NFS/VMFS.

*Antes de empezar*

Una biblioteca de contenido en VMware es un objeto contenedor que almacena plantillas de máquinas virtuales, plantillas de vApp y otros tipos de archivos. La implementación con biblioteca de contenido le proporciona una experiencia perfecta, ya que no depende de la conectividad de red.


NOTE: Debe almacenar la biblioteca de contenido en un almacén de datos compartido, de modo que todos los hosts de un clúster puedan acceder a él. Debe crear una biblioteca de contenido para almacenar el OVA antes de cambiar la configuración del dispositivo a la configuración HA. La plantilla de biblioteca de contenido una vez cargada no se debe suprimir después del despliegue.


NOTE: Para habilitar más adelante la puesta en marcha de alta disponibilidad, la máquina virtual que aloja las herramientas de ONTAP no se debe poner en marcha directamente en un host ESXi. En su lugar, debe ponerse en marcha en un clúster o en un pool de recursos.

Si aún no tiene una biblioteca de contenido adecuada, cree una mediante los siguientes pasos:


NOTE: Si sólo pretende utilizar un despliegue de nodo único pequeño, no es necesario crear una biblioteca de contenido.

. Descargue el `.zip` archivo que contiene archivos binarios (_.ova_) y certificados firmados para herramientas de ONTAP para VMware vSphere desde el https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sitio de soporte de NetApp"^].
. Inicie sesión en el cliente de vSphere mediante `\https://<vcenterip>/<ui>`
. Seleccione las elipses horizontales junto al cliente vSphere y seleccione *Biblioteca de contenido*.
. Selecciona *Crear* a la derecha de la página.
. Proporcione un nombre para la biblioteca y cree la biblioteca de contenido.
. Navegue a la biblioteca de contenido que ha creado.
. Seleccione *Acciones* a la derecha de la página y seleccione *Importar elemento* e importe el archivo OVA.



NOTE: Para obtener más información, consulte https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Creación y Uso de la Biblioteca de Contenido"] el blog.

Asegúrese de haber importado el OVA a la biblioteca de contenido.


NOTE: Antes de continuar con el despliegue, establezca el planificador de recursos distribuidos (DRS) del cluster en el inventario en 'Conservador' durante la instalación de las herramientas de ONTAP. Esto garantiza que los equipos virtuales no se migren durante la instalación.

.Pasos
. Descargue el `.zip` archivo que contiene archivos binarios (_.ova_) y certificados firmados para herramientas de ONTAP para VMware vSphere desde el https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sitio de soporte de NetApp"^]. Si ha importado el OVA a la biblioteca de contenido, puede omitir este paso y continuar con el siguiente paso, ya que puede implementar directamente desde la biblioteca de contenido.
. Inicie sesión en vSphere Server.
. Desplácese hasta el pool de recursos que haya creado o hasta el clúster o hasta el host donde desea implementar el OVA.
. Haga clic con el botón derecho en la ubicación requerida y seleccione *Implementar plantilla OVF...*.
+

NOTE: Nunca almacene las herramientas de ONTAP para máquinas virtuales de VMware vSphere en almacenes de datos vVols que gestionen.

. Seleccione el archivo OVA a través de la URL del archivo _.ova_ o vaya a la carpeta donde se guarda el archivo _.ova_ y, a continuación, seleccione *Siguiente*.
. Para implementar herramientas de ONTAP para VMware vSphere desde la biblioteca de contenido:
+
.. Vaya a la biblioteca de contenido y seleccione el elemento de biblioteca que desea desplegar.
.. Selecciona *Acciones* > *Nueva VM de esta plantilla*


. En el *Seleccione un nombre y una carpeta* para la ventana de la máquina virtual, introduzca el nombre de la máquina virtual y seleccione la ubicación de la máquina virtual. Si marca la casilla de verificación que dice *Personalizar el hardware de esta máquina virtual*, se activará un paso llamado *Personalizar hardware* antes de llegar a la ventana *Listo para completar*.
. Seleccione un recurso informático y seleccione *Siguiente*. Puede elegir marcar la casilla de verificación para *encender automáticamente la VM implementada*.
. Revisa los detalles de la plantilla y selecciona *Siguiente*.
. Lea y acepte el contrato de licencia y seleccione *Siguiente*.
. Seleccione el almacenamiento para la configuración y los archivos de disco y seleccione *Siguiente*.
. Seleccione la red de destino para cada red de origen y seleccione *Siguiente*.
. En la ventana *Personalizar plantilla*, rellena los campos requeridos y selecciona *Siguiente*.
+
** La información proporcionada aquí se valida para los patrones adecuados durante el proceso de instalación. En caso de discrepancia, se muestra un mensaje de error en la consola web y se le solicita que corrija cualquier información incorrecta proporcionada.
** Los nombres de host deben consistir en letras mayúsculas (A-Z), letras minúsculas (a-z), dígitos (0-9) o el guión (-) carácter especial. Si desea configurar la pila doble, especifique el nombre de host asignado a la dirección IPv6.
+

NOTE: No se admite Pure IPv6. El modo mixto es compatible con una VLAN que tenga direcciones IPv6 e IPv4.



. En la ventana *Personalizar hardware* debe habilitar CPU hot add y memoria hot plug.
. Revise los detalles en la ventana *Listo para completar*, seleccione *Finalizar*.
+
A medida que se crea la tarea de implementación, el progreso se muestra en la barra de tareas de vSphere.

. Encienda la máquina virtual después de completar la tarea.
+

NOTE: Antes de encender, asegúrese de que la máquina virtual tenga habilitados los complementos activos para la CPU y la memoria.



Puede realizar un seguimiento del progreso de la instalación dentro de la consola web de la máquina virtual.

En caso de discrepancias en los valores introducidos en el formulario OVF, un cuadro de diálogo le pedirá que realice una acción correctiva. Realice los cambios necesarios en el cuadro de diálogo, utilizando el botón Tab para navegar y seleccionar OK. Tiene tres intentos para rectificar cualquier problema. Si el problema persiste después de tres intentos, el proceso de instalación cesará y se recomienda volver a intentar la instalación en una máquina virtual nueva.
