---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Antes de implementar las herramientas de ONTAP para VMware vSphere, debería estar familiarizado con los requisitos de espacio para el paquete de implementación y algunos requisitos básicos del sistema host. 
---
= Requisitos y límites de configuración de las herramientas ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de implementar las herramientas de ONTAP para VMware vSphere, debería estar familiarizado con los requisitos de espacio para el paquete de implementación y algunos requisitos básicos del sistema host.

Puede usar herramientas de ONTAP para VMware vSphere con VMware vCenter Server Virtual Appliance (vcsa). Debe poner en marcha herramientas de ONTAP para VMware vSphere en un cliente de vSphere compatible que incluya un sistema ESXi.



== Requisitos del sistema

* * Requisitos de espacio del paquete de instalación por nodo*
+
** 15 GB para instalaciones con Thin Provisioning
** 348 GB para instalaciones con aprovisionamiento pesado


* *Requisitos de dimensionamiento del sistema host* La tabla siguiente muestra la memoria recomendada para cada tamaño de implementación. Para implementaciones de alta disponibilidad (HA), necesita tres veces el tamaño del dispositivo indicado.


|===


| *Tipo de despliegue* | *CPU por nodo* | *Memoria (GB) por nodo* | *Espacio en disco (GB) de espesor aprovisionado por nodo* 


| Pequeño | 9 | 18 | 350 


| Mediano | 13 | 26 | 350 


| NOTA grande: La puesta en marcha de gran envergadura solo es para configuración de alta disponibilidad. | 17 | 34 | 350 
|===

NOTE: Cuando se habilita el backup, cada clúster de herramientas de ONTAP necesita otros 50GB TB de espacio en el almacén de datos donde se implementan las máquinas virtuales. Por tanto, la no alta disponibilidad requiere 400 GB y alta disponibilidad requiere 1100 GB de espacio en total.



== Requisitos mínimos de almacenamiento y aplicaciones

|===
| Almacenamiento, host y aplicaciones | Requisitos de versión 


| ONTAP | 9.15.1, 9.16.1 y 9.17.0 


| Las herramientas de ONTAP admiten hosts ESXi | a partir de 7.0.3 


| Las herramientas de ONTAP eran compatibles con vCenter Server | 7.0U3 en adelante 


| Proveedor de VASA | 3,0 


| Aplicación ova | 10,5 


| Host ESXi para implementar máquinas virtuales de herramientas de ONTAP | 7.0U3 y 8.0U3 


| VCenter Server para poner en marcha máquinas virtuales de herramientas de ONTAP | 7,0 y 8,0 
|===

NOTE: A partir de las herramientas de ONTAP para VMware vSphere 10,4, el hardware de las máquinas virtuales cambia de la versión 10 a la 17.

La herramienta de matriz de interoperabilidad (IMT) contiene la información más reciente sobre las versiones compatibles de ONTAP, vCenter Server, hosts ESXi y aplicaciones de plugins.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad"^]



== Requisitos de puertos

La siguiente tabla describe los puertos de red que utiliza NetApp y sus funciones. Existen tres tipos diferentes de puertos:

* Puertos externos: Estos puertos son accesibles desde fuera del clúster o nodo de Kubernetes. Permiten que los servicios se comuniquen con redes o usuarios externos, posibilitando la integración con sistemas fuera del entorno del clúster.
* Puertos entre nodos: Estos puertos permiten la comunicación entre nodos dentro del clúster de Kubernetes. Son necesarios para tareas de clúster como compartir datos y trabajar juntos. Para implementaciones de un solo nodo, los puertos entre nodos se utilizan únicamente dentro del nodo y no necesitan acceso externo. Los puertos entre nodos pueden aceptar tráfico procedente de fuera del clúster. Bloquee el acceso a internet de los puertos entre nodos mediante reglas de firewall.
* Puertos internos: Estos puertos se comunican dentro del clúster de Kubernetes utilizando direcciones ClusterIP. No están expuestos externamente y no es necesario agregarlos a las reglas del firewall.



NOTE: Asegúrese de que todos los nodos de herramientas ONTAP residan en la misma subred para mantener una comunicación ininterrumpida entre sí.

Haga clic para expandir o contraer la tabla de requisitos del puerto.

[%collapsible]
====
|===
| *Nombre del servicio/componente* | *Puerto* | *Protocolo* | *Tipo de puerto* | *Descripción* 


| ntv-gateway-sv (LB) | 443, 8443 | TCP | Externo | Puerto de paso para la comunicación entrante del servicio VASA Provider. El certificado autofirmado del proveedor VASA y el certificado CA personalizado están alojados en este puerto. 


| SSH | 22 | TCP | Externo | Secure Shell para el inicio de sesión en servidores remotos y la ejecución de comandos. 


| Servidor rke2 | 9345 | TCP | Internodo | API de supervisor RKE2 (Restringir a redes de confianza). 


| kube-apiserver | 6443 | TCP | Internodo | Puerto del servidor de la API de Kubernetes (Restringir a redes de confianza). 


| rpcbind/asignador de puertos | 111 | TCP/UDP | Internodo | Se utiliza para la comunicación RPC entre servicios. 


| núcleos de DNS (DNS) | 53 | TCP/UDP | Internodo | Servicio de Sistema de Nombres de Dominio (DNS) para la resolución de nombres dentro del clúster. 


| NTP | 123 | UDP | Internodo | Protocolo de tiempo de red (NTP) para la sincronización horaria. 


| etcd | 2379, 2380, 2381 | TCP | Internodo | Almacén de clave-valor para datos de clúster. 


| kube-vip | 2112 | TCP | Internodo | Puerto del servidor de la API de Kubernetes. 


| kubelet | 10248, 10250 | TCP | Internodo | componente de Kubernetes 


| controlador kube | 10257 | TCP | Internodo | componente de Kubernetes 


| controlador de la nube | 10258 | TCP | Internodo | componente de Kubernetes 


| Programador de kube | 10259 | TCP | Internodo | componente de Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Internodo | componente de Kubernetes 


| calicó-nodo | 9091, 9099 | TCP | Internodo | Componente de red Calico. 


| contenedor | 10010 | TCP | Internodo | Servicio de demonio de contenedor. 


| VXLAN (Franela) | 8472 | UDP | Internodo | Red superpuesta para la comunicación entre pods. 
|===

NOTE: Para implementaciones de alta disponibilidad, asegúrese de que el puerto UDP 8472 esté abierto entre todos los nodos. Este puerto permite la comunicación entre pods a través de nodos; bloquearlo interrumpirá la comunicación entre nodos.

====


== Límites de configuración para desplegar ONTAP tools for VMware vSphere para almacenes de datos vVols

Puedes usar la siguiente tabla como guía para configurar ONTAP tools for VMware vSphere.

|===


| *Despliegue* | *Tipo* | *Número de vVols* | *Número de hosts* 


| No alta disponibilidad | Pequeño (S) | hasta 12K | 32 


| No alta disponibilidad | Medio (M) | hasta 24K | 64 


| Alta disponibilidad | Pequeño (S) | hasta 24K | 64 


| Alta disponibilidad | Medio (M) | hasta 50k | 128 


| Alta disponibilidad | Grande (L) | hasta 100k | 256 
|===

NOTE: Los recuentos de host en la tabla representan el total combinado de todos los vCenters conectados.



== Límites de configuración para desplegar ONTAP tools for VMware vSphere para almacenes de datos VMFS y NFS

Los límites de configuración enumerados en esta sección están validados y respaldados por NetApp. Los límites reales pueden variar según tu entorno y carga de trabajo. Superar estos límites puede afectar el rendimiento o la capacidad de soporte y no se recomienda. Ten en cuenta lo siguiente al revisar la tabla:

* La recuperación ante desastres (DR) de la máquina virtual se configura usando políticas síncronas, asíncronas o de sincronización estricta. DR no es compatible con el protocolo NVMe.
* La protección de clústeres de hosts ESXi usa SnapMirror Active Sync, que no admite implementaciones multi-vCenter.
* ONTAP tools restringe únicamente el número de hosts ESXi y almacenes de datos según el tamaño del despliegue. No hay restricciones sobre la cantidad de servidores vCenter que se pueden conectar a ONTAP tools.
* ONTAP tools realiza el descubrimiento en paralelo de todos los objetos de almacenamiento. Los límites de configuración para los objetos de almacenamiento ONTAP se aplican independientemente del número de objetos en uso activo.
* ONTAP tools no impone un límite en el número de vCenter Servers que se pueden integrar. Los límites de configuración vienen determinados por el número de hosts y almacenes de datos compatibles, como se detalla en la siguiente tabla.


|===
| Despliegue | Número de almacenes de datos VMFS y NFS | Número de almacenes de datos VMFS con DR habilitado | Número de hosts 


| No alta disponibilidad pequeña | 200 | 80 | 32 


| No HA Medio | 250 | 100 | 32 


| HA pequeña | 350 | 200 | 64 


| ALTA disponibilidad media | 600 | 200 | 128 


| ALTA disponibilidad | 1024 | 250 | 256 
|===


== Herramientas de ONTAP para VMware vSphere: Storage Replication Adapter (SRA)

La siguiente tabla muestra los números admitidos por instancia de VMware Live Site Recovery con las herramientas de ONTAP para VMware vSphere.

|===
| *Tamaño de implementación de vCenter* | *Pequeño* | *Media* 


| Cantidad total de máquinas virtuales configuradas para la protección mediante la replicación basada en cabinas | 2000 | 5000 


| Número total de grupos de protección de replicación basados en cabinas | 250 | 250 


| Número total de grupos de protección por plan de recuperación | 50 | 50 


| Número de almacenes de datos replicados | 255 | 255 


| Número de máquinas virtuales | 4000 | 7000 
|===
La siguiente tabla muestra el número de Live Site Recovery de VMware y el tamaño de la puesta en marcha de VMware vSphere con las herramientas de ONTAP correspondientes.

|===


| *Número de instancias de VMware Live Site Recovery* | *ONTAP herramientas de implementación Tamaño* 


| Hasta 4 | Pequeño 


| 4 a 8 | Mediano 


| Más de 8 | Grande 
|===
Para obtener más información, consulte https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Límites operativos de Live Site Recovery de VMware"].
