---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Debe configurar un almacén de datos de marcador de posición para reservar un lugar en el inventario de vCenter, en el sitio de recuperación, para la máquina virtual protegida (VM). El almacén de datos de marcador de posición no necesita ser grande, ya que las VM de marcador de posición son pequeñas y ocupan solo unos pocos cientos de kilobytes o menos.' 
---
= Configure almacenes de datos de marcadores de posición
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar un almacén de datos de marcador de posición para reservar un lugar en el inventario de vCenter, en el sitio de recuperación, para la máquina virtual (VM) protegida. No es necesario que el almacén de datos de marcador de posición sea grande, ya que las VM de marcador de posición son pequeñas y ocupan solo unos pocos cientos de kilobytes o menos.

.Antes de empezar
* Debe haber conectado los sitios protegidos y de recuperación.
* Debe haber configurado las asignaciones de recursos.


.Pasos
. Inicie sesión en vCenter Server y seleccione *Site Recovery* > *Sites*.
. Seleccione su sitio protegido y seleccione *Administrar*.
. Seleccione *Placeholder datastores* > *New* en la pestaña Administrar para crear un nuevo almacén de datos de marcador de posición.
. Seleccione el almacén de datos apropiado y seleccione *OK*.
+

NOTE: Los almacenes de datos de marcador de posición pueden ser locales o remotos y no deben replicarse.

. Repita los pasos 3 a 5 para configurar un almacén de datos de marcador de posición para el sitio de recuperación.

