---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Debe configurar los intervalos de tiempo de espera de almacenamiento según los ajustes recomendados para que el adaptador de replicación de almacenamiento \(SRA\) funcione de forma óptima en entornos con gran escala.' 
---
= Configure SRA para entornos con gran escala
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe configurar los intervalos de tiempo de espera de almacenamiento según la configuración recomendada para que el adaptador de replicación de almacenamiento (SRA) funcione de forma óptima en entornos con alta escala.



== Configuración del proveedor de almacenamiento

Debe establecer los siguientes valores de tiempo de espera en Live Site Recovery de VMware para entornos escalados:

|===


| *Ajustes avanzados* | *Valores de tiempo de espera* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Aumente el valor del ajuste de 900 segundos a 12000 segundos.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Establecer un valor alto (por ejemplo: 99999)

|===
También debe habilitar el `StorageProvider.autoResignatureMode` opción.

Consulte https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Cambie la configuración del proveedor de almacenamiento"] para obtener más información sobre la modificación de la configuración del proveedor de almacenamiento.



== Configuración de almacenamiento

Cuando alcance un tiempo de espera, aumente los valores de `storage.commandTimeout` y.. `storage.maxConcurrentCommandCnt` a un valor superior.


NOTE: El intervalo de tiempo de espera especificado es el valor máximo.  No es necesario esperar a que se alcance el tiempo de espera máximo.  La mayoría de los comandos finalizan dentro del intervalo de tiempo de espera máximo establecido.

Consulte https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Cambie la configuración de almacenamiento"] para modificar la configuración del proveedor de SAN.
