---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Configure un almacén de datos de marcador de posición para reservar espacio en el inventario de vCenter en el sitio de recuperación para máquinas virtuales (VM) protegidas.  Los almacenes de datos de marcador de posición requieren una capacidad mínima, porque las máquinas virtuales de marcador de posición son pequeñas y normalmente utilizan solo unos pocos cientos de kilobytes.' 
---
= Configura los almacenes de datos de marcadores de posición en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configure un almacén de datos de marcador de posición para reservar espacio en el inventario de vCenter en el sitio de recuperación para máquinas virtuales (VM) protegidas.  Los almacenes de datos de marcador de posición requieren una capacidad mínima, porque las máquinas virtuales de marcador de posición son pequeñas y normalmente utilizan solo unos pocos cientos de kilobytes.

.Antes de empezar
* Asegúrese de que los sitios protegidos y de recuperación estén conectados.
* Verifique que se hayan configurado las asignaciones de recursos.


.Pasos
. Inicie sesión en vCenter Server y seleccione *Site Recovery* > *Sites*.
. Seleccione su sitio protegido y seleccione *Administrar*.
. Seleccione *Placeholder datastores* > *New* en la pestaña Administrar para crear un nuevo almacén de datos de marcador de posición.
. Seleccione el almacén de datos apropiado y seleccione *OK*.
+

NOTE: Los almacenes de datos de marcador de posición pueden residir en un almacenamiento local o remoto, pero no requieren replicación.

. Repita los pasos 3 a 5 para configurar un almacén de datos de marcador de posición para el sitio de recuperación.

