---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: Debe crear grupos de protección para proteger un grupo de máquinas virtuales en el sitio protegido. 
---
= Configura sitios protegidos y de recuperación en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe crear grupos de protección para proteger un grupo de máquinas virtuales en el sitio protegido.

Al agregar un nuevo almacén de datos, puede incluirlo en el grupo de almacenes de datos existente o agregar uno nuevo y crear un nuevo volumen o grupo de consistencia para su protección. Después de agregar un nuevo almacén de datos a un grupo de consistencia o volumen protegido, actualice SnapMirror y realice la detección de almacenamiento tanto en el sitio protegido como en el de recuperación. Puede ejecutar la detección manualmente o de forma programada para garantizar que el nuevo almacén de datos se detecte y proteja.



== Sitios protegidos para pares y de recuperación

Debe emparejar los sitios protegidos y de recuperación creados mediante vSphere Client para habilitar el Storage Replication Adapter (SRA) para detectar los sistemas de almacenamiento.


NOTE: El adaptador de replicación de almacenamiento (SRA) admite la distribución en abanico con una relación de sincronización de tipo dúplex de conmutación por error automatizada y una relación asincrónica SnapMirror en un grupo de consistencia. Sin embargo, no se admite la distribución en abanico con dos SnapMirror asíncronos en un grupo de consistencia ni la distribución en abanico de SnapMirrors en un volumen. Las relaciones SnapMirror de tipo bóveda no se consideran dentro de estas restricciones de distribución.

.Antes de empezar
* Debe tener VMware Live Site Recovery instalado en los sitios protegidos y de recuperación.
* Debe tener el SRA instalado en los sitios protegidos y de recuperación.


.Pasos
. En la página de inicio de vSphere Client, haga doble clic en el ícono *Site Recovery* y luego seleccione *Sitios*.
. Selecciona *Objetos* > *Acciones* > *Emparejar sitios*.
. En el cuadro de diálogo *Emparejar servidores de Site Recovery Manager*, introduzca la dirección del controlador de servicios de plataforma del sitio protegido y, a continuación, seleccione *Siguiente*.
. En la sección Select vCenter Server, realice lo siguiente:
+
.. Compruebe que vCenter Server del sitio protegido aparece como candidato coincidente al emparejar.
.. Introduzca las credenciales administrativas de SSO y, a continuación, seleccione * Finalizar *.


. Si se le solicita, seleccione *Sí* para aceptar los certificados de seguridad.


.Resultado
El cuadro de diálogo *Objetos* muestra los sitios protegidos y de recuperación.



== Configure los grupos de protección

.Antes de empezar
Debe asegurarse de que los sitios de origen y destino están configurados para lo siguiente:

* Misma versión de VMware Live Site Recovery instalada
* Equipos virtuales
* Sitios protegidos y de recuperación emparejados
* Los almacenes de datos de origen y destino deben montarse en las ubicaciones respectivas


.Pasos
. Inicie sesión en vCenter Server y seleccione *Site Recovery* > *Grupos de protección*.
. En el panel *Grupos de protección*, selecciona *Nuevo*.
. Especifique un nombre y una descripción para el grupo de protección, la dirección y seleccione *Siguiente*.
. En el campo *Tipo*, seleccione la opción *Tipo...* como grupos de almacenes de datos (replicación basada en matrices) para almacenes de datos NFS y VMFS. El dominio de fallos no son más que máquinas virtuales de servicio (SVM) con replicación habilitada. Se muestran las SVM que solo tienen emparejamiento implementado y no presentan problemas.
. En la pestaña Grupos de replicación, seleccione el par de matrices habilitado o los grupos de replicación que tienen la máquina virtual configurada y, a continuación, seleccione *Siguiente*.
+
Todas las máquinas virtuales del grupo de replicación se agregan al grupo de protección.

. Puede seleccionar el plan de recuperación existente o crear uno nuevo seleccionando *Agregar al nuevo plan de recuperación.*
. En la pestaña Listo para completar, revise los detalles del grupo de protección que creó y luego seleccione *Finalizar*.

