---
permalink: protect/map-resource.html 
sidebar: sidebar 
keywords: resource mappings, ESXi hosts and clusters, VMware Live Site Recovery, failover configuration, ONTAP tools 
summary: Asigna pools de recursos, hosts o clústeres entre los sitios protegidos y los de recuperación para ubicar correctamente las máquinas virtuales durante la conmutación por error. 
---
= Configura las asignaciones de recursos en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe asignar los recursos en el sitio protegido y el sitio de recuperación de modo que las máquinas virtuales estén configuradas para conmutar al nodo de respaldo a un grupo de hosts o a otro.

.Antes de empezar
Debe haber conectado los sitios protegidos y de recuperación.


NOTE: En VMware Live Site Recovery, los recursos pueden ser pools de recursos, hosts ESXi o clústeres de vSphere.

.Pasos
. Inicie sesión en vCenter Server y seleccione *Site Recovery* > *Sites*.
. Seleccione su sitio protegido y seleccione *Administrar*.
. Seleccione *Asignaciones de recursos* > *Nuevo* en la pestaña Administrar para crear una nueva asignación de recursos.
. En el asistente Create Resource Mapping, realice lo siguiente:
+
.. Selecciona *Automatically Prepare Mappings for Resources with Matching Names* y selecciona *Next*.
.. Seleccione los objetos del centro de datos necesarios para los sitios protegidos y de recuperación y seleccione *Agregar asignaciones*.
.. Seleccione *Siguiente* después de que las asignaciones se hayan creado correctamente.
.. Seleccione el objeto utilizado anteriormente para crear una asignación inversa y luego seleccione *Finalizar*.




.Resultado
La página Resource Mappings muestra los recursos del sitio protegido y los recursos del sitio de recuperación. Puedes seguir los mismos pasos para otros recursos en tu entorno.
