---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: Para que VMware Live Site Recovery se comunique con el SRA, debe actualizar las credenciales del SRA en el servidor de VMware Live Site Recovery si ha modificado las credenciales. 
---
= Actualiza las credenciales de SRA en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que VMware Live Site Recovery se comunique con el SRA, debe actualizar las credenciales del SRA en el servidor de VMware Live Site Recovery si ha modificado las credenciales.

.Antes de empezar
Debe haber ejecutado los pasos mencionados en el tema link:../protect/configure-on-srm-appliance.html["Configurar SRA en el dispositivo VMware Live Site Recovery"].

.Pasos
. Ejecuta los siguientes comandos para eliminar las credenciales de ONTAP tools almacenadas en caché del equipo VMware Live Site Recovery:
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Ejecute el comando Perl para configurar SRA con las nuevas credenciales:
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` Es necesario tener una sola cotización en torno al valor de la contraseña.
+
Aparece un mensaje de éxito que confirma que se han almacenado las credenciales de almacenamiento. SRA puede comunicarse con el servidor SRA utilizando la dirección IP, el puerto y las credenciales proporcionadas.







== Reconfigura vCenter en el dispositivo VMware Live Site Recovery después de un cambio de certificado

Si el certificado de vCenter cambia, por ejemplo después de una actualización de vCenter, puedes encontrarte con un error de no coincidencia de huella digital en la extensión Site Recovery. Sigue estos pasos para resolverlo.

.Pasos
. Reconfigura vCenter en el dispositivo VMware Live Site Recovery
+
.. Abre la interfaz de gestión del dispositivo VMware Live Site Recovery en un navegador: `\https://<SRM_IP>:5480`
.. Selecciona la pestaña *Resumen*.
.. Selecciona *Reconfigurar* para la conexión del servidor vCenter.
+
Esta opción obtiene y acepta la huella digital del certificado más reciente de vCenter.



. Vuelve a conectar el emparejamiento del sitio (si persiste el error)
+
Si el error de no coincidencia de huella persiste tras la reconfiguración:

+
.. Inicia sesión en la interfaz de usuario de vCenter.
.. Navega hasta la extensión *Site Recovery*.
.. Ubica la sección *Emparejamiento de sitios*.
.. Selecciona *Reconectar* para restablecer el emparejamiento del sitio con el certificado actualizado.



