---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords: key concepts, ONTAP tools terms, consistency group, dual stack 
summary: Repasa los conceptos y términos clave utilizados en la documentación de ONTAP tools for VMware vSphere. 
---
= Términos y definiciones clave de las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Familiarízate con los conceptos clave y la terminología utilizada en ONTAP tools for VMware vSphere. Las definiciones abarcan los storage backends, los volúmenes virtuales (vVols), la sincronización activa de SnapMirror, VASA, SRA y otros componentes fundamentales.



[[certificate-authority-ca]]
=== Entidad de certificación (CA)

Una CA es una entidad de confianza que emite certificados Secure Sockets Layer (SSL).



[[consistency-group]]
=== Grupo de consistencia

Un grupo de coherencia es una colección de volúmenes gestionados como una única unidad. Los grupos de coherencia se sincronizan para garantizar la coherencia de los datos entre las unidades de almacenamiento y los volúmenes. En ONTAP, proporcionan una gestión sencilla y garantías de protección para una carga de trabajo de aplicaciones que abarca varios volúmenes. Más información sobre https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["grupos de consistencia"].



[[dual-stack]]
=== Pila doble

Una red de pila doble es un entorno de red que admite el uso simultáneo de direcciones IPv4 e IPv6.



[[high-availability-ha]]
=== Alta disponibilidad

Los nodos en clúster están configurados en pares de alta disponibilidad para realizar operaciones no disruptivas.



[[logical-unit-number-lun]]
=== Número de unidad lógica (LUN)

Una LUN es un número utilizado para identificar una unidad lógica dentro de una red de área de almacenamiento (SAN). Estos dispositivos direccionables suelen ser discos lógicos a los que se accede a través del protocolo de Interfaz de Sistemas de Computadoras Pequeñas (SCSI) o uno de sus derivados encapsulados.



[[nvme-namespace-and-subsystem]]
=== Subsistema y espacio de nombres NVMe

Un espacio de nombres NVMe es una cantidad de memoria no volátil que se puede formatear en bloques lógicos. Los espacios de nombres son el equivalente a los LUN de los protocolos FC e iSCSI, y un subsistema NVMe es análogo a un igroup. Un subsistema NVMe puede asociarse a iniciadores, lo que les permite acceder a los espacios de nombres dentro del subsistema.



[[ontap-tools-manager]]
=== Gestor de herramientas de ONTAP

ONTAP tools Manager proporciona ONTAP tools para administradores de VMware vSphere con un mayor control sobre las instancias de vCenter Server gestionadas y los backends de almacenamiento incorporados. Ayuda a gestionar las instancias de vCenter Server, los backends de almacenamiento, los certificados, las contraseñas y los paquetes de registro.



[[open-virtual-appliance-ova]]
=== Open Virtual Appliance (OVA)

OVA es un estándar abierto para empaquetar y distribuir dispositivos virtuales o software que deben ejecutarse en máquinas virtuales.



[[recovery-point-objective-rpo]]
=== Objetivo de punto de recuperación (RPO)

El RPO mide con qué frecuencia haces copias de seguridad o replicas datos. Especifica el punto exacto en el tiempo al que necesitas restaurar los datos después de una interrupción para reanudar las operaciones del negocio. Por ejemplo, si una organización tiene un RPO de cuatro horas, puede tolerar la pérdida de hasta cuatro horas de datos en caso de desastre.



[[snapmirror-active-sync]]
=== SnapMirror síncrono activo

SnapMirror active sync permite que los servicios empresariales sigan funcionando incluso en caso de un fallo total del sitio, permitiendo que las aplicaciones realicen una conmutación por error de forma transparente usando una copia secundaria. SnapMirror active sync no requiere intervención manual ni scripts personalizados para activar una conmutación por error. Más información sobre https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["SnapMirror síncrono activo"].



[[storage-backends]]
=== Back-ends de almacenamiento

Los back-ends de almacenamiento son la infraestructura de almacenamiento subyacente que el host ESXi utiliza para almacenar archivos de máquinas virtuales, datos y otros recursos. Permiten que el host ESXi acceda a datos persistentes y los gestione, lo que proporciona la funcionalidad de almacenamiento y el rendimiento necesarios para un entorno virtualizado.

.Clúster global (back-end de almacenamiento)
Los back-ends de almacenamiento global, disponibles solo con las credenciales del clúster de ONTAP, se incorporan a través de la interfaz del Gestor de herramientas de ONTAP. Se pueden agregar con una cantidad mínima de Privileges para permitir la detección de los recursos de clúster esenciales necesarios para la gestión de vVols. Los clústeres globales son ideales para escenarios de multi-tenancy en los que se añade un usuario de SVM localmente para la gestión de vVols.

.Back-end de almacenamiento local
Los back-ends de almacenamiento local con credenciales de clúster o SVM se añaden mediante la interfaz de usuario de herramientas de ONTAP y se limitan a un para vCenter. Cuando se usan las credenciales del clúster localmente, las SVM asociadas se asignan automáticamente con el para gestionar vVols o VMFS. Para la gestión de VMFS, incluido el SRA, las herramientas de ONTAP admiten credenciales de SVM sin necesidad de un clúster global.



[[storage-replication-adapter-sra]]
=== Adaptador de replicación de almacenamiento (SRA)

SRA es el software específico de proveedor de almacenamiento que se instala en el dispositivo Live Site Recovery de VMware. El adaptador habilita la comunicación entre el Site Recovery Manager y una controladora de almacenamiento en el nivel de Storage Virtual Machine (SVM) y la configuración a nivel del clúster.



[[storage-virtual-machine-svm]]
=== Máquina virtual de almacenamiento (SVM)

SVM es la unidad de multitenancy en ONTAP. Al igual que una máquina virtual que se ejecuta en un hipervisor, SVM es una entidad lógica que abstrae recursos físicos. SVM contiene volúmenes de datos y uno o más LIF a través de los cuales sirve datos a los clientes.



[[uniform-and-non-uniform-configuration]]
=== Configuración uniforme y no uniforme

* * El acceso uniforme a host* significa que los hosts de dos sitios están conectados a todas las rutas a los clústeres de almacenamiento en ambos sitios. Las rutas entre sitios se extienden a distancias.
* * El acceso no uniforme del host* significa que los hosts en cada sitio están conectados solo al clúster en el mismo sitio. Las rutas entre sitios y las rutas extendidas no están conectadas.
+

NOTE: SnapMirror active sync admite el acceso uniforme a los hosts en cualquier implementación; solo las implementaciones simétricas activo/activo admiten el acceso no uniforme a los hosts. Más información sobre https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Información general sobre la sincronización activa de SnapMirror en ONTAP"].





[[virtual-machine-file-system-vmfs]]
=== Sistema de archivos de máquina virtual (VMFS)

VMFS es un sistema de archivos en clúster diseñado para almacenar archivos de equipos virtuales en entornos de VMware vSphere.



[[virtual-volumes-vvols]]
=== Volúmenes virtuales (vVols)

vVols proporcionan una abstracción a nivel de volumen para el almacenamiento utilizado por una máquina virtual. vVols ofrecen varias ventajas y constituyen una alternativa al uso de un LUN tradicional. Un almacén de datos vVol suele estar asociado a un único LUN que actúa como contenedor para vVols.



[[vm-storage-policy]]
=== Política de almacenamiento de máquinas virtuales

Las políticas de almacenamiento de máquinas virtuales se crean en vCenter Server en Políticas y perfiles. Para vVols, cree un conjunto de reglas mediante reglas del proveedor de tipo de almacenamiento NetApp vVols.



[[vmware-live-site-recovery]]
=== Recuperación de sitio en vivo de VMware

VMware Live Site Recovery, anteriormente conocido como Site Recovery Manager (SRM), ofrece funciones de continuidad del negocio, recuperación ante desastres, migración de sitios y pruebas sin interrupciones para entornos virtuales de VMware.



[[vmware-vsphere-apis-for-storage-awareness-vasa]]
=== API de VMware vSphere para detección de almacenamiento (VASA)

VASA es un conjunto de API que integran cabinas de almacenamiento con vCenter Server para su gestión y administración. La arquitectura se basa en varios componentes, incluido el proveedor VASA, que controla la comunicación entre VMware vSphere y los sistemas de almacenamiento.



[[vmware-vsphere-storage-apis-array-integration-vaai]]
=== API de almacenamiento VMware vSphere - Integración de cabina (VAAI)

VAAI es un conjunto de API que permite la comunicación entre hosts ESXi de VMware vSphere y dispositivos de almacenamiento. Las API incluyen un conjunto de operaciones primitivas que utilizan los hosts para descargar las operaciones de almacenamiento hacia la cabina. VAAI puede proporcionar mejoras de rendimiento significativas para tareas que consumen mucho almacenamiento.



[[vsphere-metro-storage-cluster]]
=== Clúster de almacenamiento Metro de vSphere

vSphere Metro Storage Cluster (vMSC) es una arquitectura que permite y admite vSphere en un despliegue de clúster ampliado. Las soluciones vMSC son compatibles con NetApp MetroCluster y SnapMirror active sync (anteriormente SMBC). Estas soluciones proporcionan una continuidad de negocio mejorada en caso de fallo del dominio. El modelo de resistencia se basa en tus opciones de configuración específicas. Más información sobre https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere Metro Storage Cluster"].



[[vvols-datastore]]
=== Almacén de datos vVols

El datastore vVols es una representación lógica de un contenedor vVols creado y mantenido por un VASA Provider.



[[zero-rpo]]
=== RPO cero

RPO es la sigla en inglés para el objetivo de punto de recuperación, la cantidad de pérdida de datos que se considera aceptable durante un tiempo dado. El RPO de cero significa que no es aceptable ninguna pérdida de datos.
