---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords:  
summary: Las herramientas de ONTAP para VMware vSphere son una colección de herramientas para la gestión del ciclo de vida de máquinas virtuales. Se integra con el ecosistema de VMware y ayuda en el aprovisionamiento, la protección básica y la recuperación ante desastres de las máquinas virtuales. 
---
= Información general de las herramientas de ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las ONTAP tools for VMware vSphere son un conjunto de herramientas para la gestión del ciclo de vida de las máquinas virtuales.  Se integra con el ecosistema VMware para simplificar el aprovisionamiento del almacén de datos y proporcionar protección básica para las máquinas virtuales.  Es una colección de microservicios escalables horizontalmente y basados ​​en eventos, implementados como un dispositivo virtual abierto (OVA).

Las ONTAP tools for VMware vSphere admiten:

* Funciones principales de la máquina virtual (VM), como protección y recuperación ante desastres
* Proveedor VASA para la gestión de almacenamiento basada en políticas
* Gestión basada en políticas de almacenamiento
* Adaptador de replicación de almacenamiento (SRA)


.Alta disponibilidad de herramientas ONTAP para VMware
Las ONTAP tools for VMware vSphere ofrecen soporte de alta disponibilidad (HA) para ayudar a mantener un funcionamiento ininterrumpido durante fallas.

La solución HA le ayuda a recuperarse rápidamente de los siguientes tipos de interrupciones:

* Error de host: solo se admite un error de un solo nodo.
* Fallo de red
* Fallo de la máquina virtual (sistema operativo invitado)
* Error en la aplicación (herramientas ONTAP )


No es necesario realizar ninguna configuración adicional para habilitar HA para las ONTAP tools for VMware vSphere.

[NOTE]
====
Las ONTAP tools for VMware vSphere no son compatibles con vCenter HA.

====
Para utilizar la función HA, asegúrese de que la incorporación activa de CPU y la conexión activa de memoria estén habilitadas durante la implementación o más tarde en la configuración de la máquina virtual.
