---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords: ONTAP tools overview, virtual machine lifecycle, VASA Provider, disaster recovery 
summary: Descubre cómo ONTAP tools for VMware vSphere facilita la gestión del ciclo de vida del almacenamiento de máquinas virtuales, el aprovisionamiento de datastores y la recuperación ante desastres. 
---
= Obtenga información sobre las herramientas de ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere es un conjunto de herramientas para la gestión del ciclo de vida de las máquinas virtuales. Se integra con el ecosistema de VMware para simplificar el aprovisionamiento de datastores y proporcionar protección básica y recuperación ante desastres para las máquinas virtuales. Se implementa como un Open Virtual Appliance (OVA) y utiliza microservicios escalables horizontalmente y basados en eventos para ofrecer un rendimiento fiable a gran escala.

Las ONTAP tools for VMware vSphere admiten:

* Funciones principales de la máquina virtual (VM), como protección y recuperación ante desastres
* Proveedor VASA para la gestión de almacenamiento basada en políticas
* Gestión basada en políticas de almacenamiento
* Adaptador de replicación de almacenamiento (SRA)


.Alta disponibilidad para ONTAP tools for VMware vSphere
Las ONTAP tools for VMware vSphere ofrecen soporte de alta disponibilidad (HA) para ayudar a mantener un funcionamiento ininterrumpido durante fallas.

La solución HA le ayuda a recuperarse rápidamente de los siguientes tipos de interrupciones:

* Error de host: solo se admite un error de un solo nodo.
* Fallo de red
* Fallo de la máquina virtual (sistema operativo invitado)
* Error en la aplicación (herramientas ONTAP )


No es necesario realizar ninguna configuración adicional para habilitar HA para las ONTAP tools for VMware vSphere.

[NOTE]
====
Las ONTAP tools for VMware vSphere no son compatibles con vCenter HA.

====
Para utilizar la función HA, asegúrate de que la incorporación en caliente de CPU y la memoria conectable en caliente están activadas durante la implementación o en la configuración de la máquina virtual.
