---
permalink: concepts/rbac-vcenter-use.html 
sidebar: sidebar 
keywords: vCenter RBAC implementation, custom roles, vSphere permissions, ONTAP tools access 
summary: 'Revisa las consideraciones sobre el control de acceso basado en roles (RBAC) del servidor vCenter para ONTAP tools antes de usarlo en un entorno de producción.' 
---
= Cómo funciona el RBAC de vCenter Server con ONTAP tools for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere implementa el control de acceso basado en roles (RBAC) con vCenter Server para controlar el acceso a los objetos de vSphere y a las tareas administrativas. Comprender el modelo RBAC —incluidos los roles predefinidos, las asignaciones de permisos y cómo interactúan los privilegios de vCenter y ONTAP— te ayuda a configurar el acceso adecuado antes de implementar ONTAP tools en un entorno de producción.



[[vcenter-roles-and-the-administrator-account]]
== Los roles de vCenter y la cuenta de administrador

Solo es necesario definir y utilizar los roles personalizados de vCenter Server si desea limitar el acceso a los objetos de vSphere y a las tareas administrativas asociadas. Si no se requiere limitar el acceso, puede utilizar una cuenta de administrador en su lugar. Cada cuenta de administrador se define con el rol de administrador en el nivel superior de la jerarquía de objetos. Esto proporciona acceso completo a los objetos de vSphere, incluidos los añadidos por las herramientas de ONTAP para VMware vSphere 10.



[[vsphere-object-hierarchy]]
== Jerarquía de objetos de vSphere

El inventario de objetos de vSphere está organizado en una jerarquía. Por ejemplo, puede bajar la jerarquía de la siguiente manera:

`vCenter Server` --> `Datacenter` --> `Cluster` --> -- `Virtual Machine`> `ESXi host`

Todos los permisos se validan en la jerarquía del objeto de vSphere, excepto las operaciones del plugin de VAAI, que se validan en el host ESXi de destino.



[[roles-included-with-ontap-tools-for-vmware-vsphere-10]]
== Roles incluidos con las herramientas de ONTAP para VMware vSphere 10

Para simplificar el trabajo con vCenter Server RBAC, ONTAP tools for VMware vSphere proporciona roles predefinidos adaptados a diversas tareas administrativas.


NOTE: Puedes crear nuevos roles personalizados si lo necesitas. Para hacerlo, clona uno de los roles existentes de ONTAP tools y edítalo según lo necesites. Después de hacer los cambios de configuración, los usuarios afectados del cliente vSphere deben cerrar sesión y volver a iniciarla para activar los cambios.

Para ver las ONTAP tools for VMware vSphere roles, selecciona *Menú* en la parte superior del vSphere Client, selecciona *Administración* y luego selecciona *Roles* a la izquierda. Los siguientes privilegios deben incluirse en el rol asignado al usuario de vCenter responsable de implementar o integrar vCenter Server. Verifica que estos privilegios estén configurados antes de iniciar el proceso de implementación o integración.

* Alarmas
+
** Reconocer alarma


* Biblioteca de contenido
+
** Agregar elemento de biblioteca
** Registrarse en una plantilla
** Echa un vistazo a una plantilla
** Descargar archivos
** Almacenamiento de importación
** Almacenamiento de lectura
** Elemento de biblioteca de sincronización
** Sincronizar biblioteca suscrita
** Ver configuración


* Almacén de datos
+
** Asignar espacio
** Explorar el almacén de datos
** Operaciones de archivos de bajo nivel
** Eliminar archivo
** Actualizar archivos de la máquina virtual
** Actualizar los metadatos de la máquina virtual


* Administrador de agentes ESX
+
** Vista


* Carpeta
+
** Crear carpeta


* Host
+
** Configuración
+
*** Configuración avanzada
*** Cambiar la configuración
*** Configuración de red
*** Recursos del sistema
*** Configuración de inicio automático de la máquina virtual


** Operaciones locales
+
*** Crear una máquina virtual
*** Eliminar máquina virtual
*** Reconfigurar la máquina virtual




* Red
+
** Asignar red
** Configurar


* Administrador de Ovf
+
** Acceso al consumidor de Ovf


* Perfil del anfitrión
+
** Vista


* Recurso
+
** Asignar máquina virtual a grupo de recursos


* Tarea programada
+
** Crear tareas
** Modificar tarea
** Ejecutar tarea


* Tareas
+
** Crear tarea
** Tarea de actualización


* vApp
+
** Agregar máquina virtual
** Asignar grupo de recursos
** Asignar vApp
** Cree
** Importar
** Mover
** Apagado
** Encender
** Extraer de la URL
** Ver el entorno OVF


* Máquina virtual
+
** Cambiar configuración
+
*** Agregar disco existente
*** Agregar nuevo disco
*** Agregar o quitar dispositivo
*** Configuración avanzada
*** Cambiar el número de CPU
*** Cambiar memoria
*** Cambiar configuración
*** Cambiar recurso
*** Extender el disco virtual
*** Modificar la configuración del dispositivo
*** Quitar el disco
*** Restablecer la información del huésped
*** Actualizar la compatibilidad de las máquinas virtuales


** Editar inventario
+
*** Crear a partir de existente
*** Crear nuevo
*** Mover
*** Registro
*** Quitar
*** Darse de baja


** Interacción
+
*** Operación de copia de seguridad en una máquina virtual
*** Configurar medios de CD
*** Configurar medios de disquete
*** Conectar dispositivos
*** Interacción con la consola
*** Gestión del sistema operativo invitado mediante la API VIX
*** Apagado
*** Encender
*** Reiniciar
*** Suspender


** Aprovisionamiento
+
*** Permitir acceso al disco
*** Plantilla de clonación
*** Personalizar invitado
*** Implementar plantilla
*** Modificar la especificación de personalización
*** Leer las especificaciones de personalización


** Gestión de instantáneas
+
*** Crear instantánea
*** Eliminar instantánea
*** Cambiar el nombre de la instantánea
*** Volver a la instantánea






Las herramientas de ONTAP para VMware vSphere incluyen tres roles predefinidos.

.Herramientas de NetApp ONTAP para administrador de VMware vSphere
Ofrece todas las Privileges nativas de las herramientas de vCenter Server Privileges y ONTAP necesarias para realizar las herramientas principales de ONTAP para las tareas de administrador de VMware vSphere.

.Herramientas de NetApp ONTAP para VMware vSphere Read Only
Ofrece acceso de solo lectura a herramientas de ONTAP. Estos usuarios no pueden ejecutar ninguna herramienta ONTAP para acciones de VMware vSphere controladas por acceso.

.Herramientas de NetApp ONTAP para el aprovisionamiento de VMware vSphere
Ofrece algunos privilegios nativos de vCenter Server y privilegios específicos de las herramientas de ONTAP que se requieren para aprovisionar el almacenamiento. Es posible realizar las siguientes tareas:

* Crear nuevos almacenes de datos
* Gestionar almacenes de datos




[[vsphere-objects-and-ontap-storage-backends]]
== Objetos de vSphere y back-ends de almacenamiento de ONTAP

Los dos entornos RBAC funcionan conjuntamente. Cuando realizas una tarea en el cliente vSphere, ONTAP tools comprueba primero los roles del servidor vCenter. Si la operación está permitida por vSphere, entonces se examinan los privilegios del rol de ONTAP. Este segundo paso se realiza según el rol de ONTAP asignado al usuario cuando se creó y configuró el backend de almacenamiento.



[[working-with-vcenter-server-rbac]]
== Trabajar con RBAC de vCenter Server

Ten en cuenta lo siguiente al trabajar con los privilegios y permisos de vCenter Server.



[[required-privileges]]
=== Privilegios requeridos

Para acceder a la interfaz de usuario de ONTAP tools for VMware vSphere 10, necesitas tener el privilegio _View_ específico de ONTAP tools. Si inicias sesión en vSphere sin este privilegio y seleccionas el icono NetApp, ONTAP tools for VMware vSphere muestra un mensaje de error y te impide acceder a la interfaz de usuario.

El nivel de asignación en la jerarquía de objetos de vSphere determina a qué porciones de la interfaz de usuario puede acceder. Al asignar el privilegio View al objeto raíz, puede acceder a las herramientas de ONTAP para VMware vSphere haciendo clic en el icono de NetApp.

En su lugar, puedes asignar el privilegio View a otro nivel de objeto inferior de vSphere. Sin embargo, esto limita los menús de ONTAP tools for VMware vSphere a los que puedes acceder.



[[assigning-permissions]]
=== Asignación de permisos

Se deben usar permisos de vCenter Server si desea limitar el acceso a los objetos y las tareas de vSphere. Donde se asigna permiso en la jerarquía de objetos de vSphere determina las herramientas de ONTAP para VMware vSphere 10 tareas que los usuarios pueden realizar.


TIP: A menos que necesite definir un acceso más restrictivo, por lo general es recomendable asignar permisos en el nivel de objeto raíz o carpeta raíz.

Los permisos disponibles con las herramientas de ONTAP para VMware vSphere 10 se aplican a objetos personalizados que no son de vSphere, como sistemas de almacenamiento. Si es posible, debería asignar estos permisos a las herramientas de ONTAP para el objeto raíz de VMware vSphere porque no hay ningún objeto de vSphere al que pueda asignarlo. Por ejemplo, cualquier permiso que incluya un privilegio de «Añadir/modificar/quitar sistemas de almacenamiento» de ONTAP tools for VMware vSphere se debería asignar en el nivel de objeto raíz.

Al definir un permiso a grandes rasgos en la jerarquía de objetos, puedes configurarlo para que se transmita y sea heredado por los objetos hijos. Si es necesario, puedes asignar permisos adicionales a los objetos hijos que anulen los permisos heredados del objeto padre.

Puede modificar un permiso en cualquier momento. Si se cambia alguno de los Privileges dentro de un permiso, los usuarios asociados con el permiso deben cerrar la sesión de vSphere y volver a iniciar sesión para habilitar el cambio.
