---
permalink: automation/create-vvol-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: Un flujo de trabajo es una secuencia de uno o más pasos necesarios para lograr una tarea u objetivo administrativo específico. 
---
= Crear el almacén de datos vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible crear un almacén de datos vVols con volúmenes nuevos o con volúmenes existentes. También puede crear un almacén de datos vVols con la combinación de volúmenes existentes y volúmenes nuevos.


NOTE: Compruebe que los agregados raíz no se asignen a SVM.

Genere un token JWT antes de crear almacenes de datos o aumente la caducidad del token SAML estableciendo 'Maximum Bearer Token Lifetime' en 60m en vCenter.

Debe pasar x-auth para la API. Puede generar esta x-auth desde la nueva API que se añadió en Auth en Swagger.

/virtualization/api/v1/auth/vcenter-login

. Cree el almacén de datos vVols con el nuevo volumen.


Obtenga el ID de agregado, storage_id(svm uuid) mediante la API de REST DE ONTAP.
POST /virtualización/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores

Utilice el siguiente URI para comprobar el estado:

+

[listing]
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Cuerpo de solicitud para almacén de datos NFS

{
   «nombre»: «nfsds1»,
   «protocolo»: «nfs»,
   «platform_type»: «aff»,
   «moref»: «dominio-c8»,
   «volúmenes»:[
      {
         is_existing:false,
         «nombre»: «vol_nfs_pvt»,
         «size_in_mb»:2048000,
         «eficiencia_del_espacio»: «thin»,
         «agregado»:{
            identificación: d7078b3c-3827-4ac9-9273-0a32909455c2
         },
         «qos»:{
            «min_iops»:200,
            «max_iops»:5000
         }
      }
   ],
   «storage_backend»:{
      «id_de_almacenamiento»: 654c67bc-0f75-11ee-8a8c-00a09860a3ff
   }
}

Cuerpo de solicitud para almacén de datos iSCSI:
{
   nombre de : «iscsi_custom»,
   protocolo: iscsi
   «platform_type»: «AFF»,
   «moref» : «dominio-c8»,
   «volúmenes» : [
       {
           is_existing : false,
           nombre de : «iscsi_custom»,
           «size_in_mb» : 8034,
           «eficiencia_del_espacio»: «thin»,
           «agregado»: {
               «id» : «54fe5dd4-e461-49c8-bb2d-6d62c5d75af2»
           }
       }
   ],
   «custom_igroup_name»: «igroup1»,
   «storage_backend»: {
                       «id_de_almacenamiento»: «eb9d33ab-1960-11ee-9506-00a0985c6d9b» }
}
. Cree el almacén de datos vVols con volúmenes existentes.

Obtenga aggregate_id y volume_id mediante la API REST DE ONTAP.

 POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
Cuerpo de la solicitud

....
 {
"name" : "nfsds2",
"protocol" : "nfs",
"platform_type": "aff",
"moref" : "domain-c8",
"volumes" : [
    {
          "is_existing": true,
          "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
        }
],
"storage_backend": {
                    "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }
....
}
