---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: Añada instancias de vCenter Server a herramientas de ONTAP para VMware vSphere para configurar, gestionar y proteger sus almacenes de datos virtuales en el entorno de vCenter Server. 
---
= Agregar instancias de vCenter Server a las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Añada instancias de vCenter Server a herramientas de ONTAP para VMware vSphere para configurar, gestionar y proteger sus almacenes de datos virtuales en el entorno de vCenter Server. Cuando agrega varias instancias de vCenter Server, se requieren certificados de CA personalizados para una comunicación segura entre las herramientas de ONTAP y cada vCenter Server.

.Acerca de esta tarea
Las herramientas de ONTAP se integran con vCenter Server para realizar tareas de almacenamiento como aprovisionamiento, instantáneas y protección de datos directamente desde el cliente vSphere.

.Pasos
. Abra un navegador web y vaya a la URL: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *vCenters* > *Add* para incorporar las instancias de vCenter Server. Proporcione la dirección IP o el nombre de host, el nombre de usuario, la contraseña y los detalles de puerto de vCenter.
. En las opciones avanzadas, obtenga el certificado de vCenter Server automáticamente (autorícelo) o cárguelo manualmente.
+

NOTE: No es necesario tener una cuenta de administrador para añadir instancias de vCenter a las herramientas de ONTAP. Se puede crear un rol personalizado sin la cuenta de administrador con permisos limitados. Consulte link:../concepts/rbac-vcenter-use.html["Utilice el control de acceso basado en roles de vCenter Server con herramientas de ONTAP para VMware vSphere 10"] para obtener más información.



Al agregar una instancia de vCenter Server a herramientas de ONTAP se activan automáticamente las siguientes acciones:

* Las herramientas ONTAP registran el complemento del cliente vCenter como un complemento remoto.
* Las Privileges personalizadas para los plugins y las API se aplican a la instancia de vCenter Server.
* Se crean roles personalizados para gestionar los usuarios.
* El plugin aparece como un acceso directo en la interfaz de usuario de vSphere.

