---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Los back-ends de almacenamiento son los sistemas que los hosts ESXi utilizan para el almacenamiento de datos. 
---
= Agregar backend de almacenamiento a las herramientas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando agrega backends de almacenamiento a las herramientas de ONTAP , puede aprovisionar y administrar almacenes de datos directamente desde vCenter Server.

Para agregar backends de almacenamiento localmente, use credenciales de clúster o SVM en la interfaz de herramientas de ONTAP .  Estos backends de almacenamiento solo están disponibles para el vCenter Server seleccionado.  Las herramientas de ONTAP asignan SVM al vCenter Server para la administración del almacén de datos vVols o VMFS.  Para los flujos de trabajo de SRA y de almacén de datos VMFS, puede usar credenciales SVM sin la necesidad de un clúster mapeado globalmente.

Puede agregar backends de almacenamiento globales usando las credenciales del clúster ONTAP en el Administrador de herramientas ONTAP .  Los backends de almacenamiento global permiten flujos de trabajo de descubrimiento para identificar los recursos del clúster necesarios para la administración de vVol.  En configuraciones de múltiples inquilinos, puede agregar un usuario SVM localmente para administrar almacenes de datos vVols .

Cuando habilita la compatibilidad con MetroCluster en el sistema ONTAP , incorpore los clústeres de origen y destino como backends de almacenamiento locales o globales.

.Antes de empezar
Verifique que el certificado incluya un campo de Nombre alternativo del sujeto (SAN) válido.  Los sistemas ONTAP utilizan el campo SAN para identificar LIF de administración de clústeres y SVM.

[role="tabbed-block"]
====
.Mediante el Administrador de herramientas de ONTAP
--

NOTE: En una configuración multi-tenant, puede añadir un clúster back-end de almacenamiento de forma global y SVM de forma local para usar las credenciales de usuario de SVM.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Añada el back-end de almacenamiento y proporcione la dirección IP del servidor o el FQDN, el nombre de usuario y los detalles de la contraseña.
+

NOTE: Se admiten los LIF de gestión de direcciones IPv4 y IPv6.

. Obtenga los certificados del clúster ONTAP automáticamente y autorice el certificado, o cárguelo manualmente buscando su ubicación.
+

NOTE: Si es necesario, puede deshabilitar la validación del nombre alternativo del sujeto (SAN) desde la consola de mantenimiento. Para obtener instrucciones, consultelink:../manage/change-valid-flag.html["Cambiar la bandera de validación del certificado"] .

. Si el backend de almacenamiento que agrega es parte de una configuración de MetroCluster , el Administrador de herramientas de ONTAP muestra un mensaje emergente para agregar el clúster emparejado.  Seleccione *Agregar* y proporcione los detalles para el backend de almacenamiento de pares de MetroCluster .
+

NOTE: Después de que el sistema ONTAP realice un cambio y un retorno, ejecute el descubrimiento de herramientas ONTAP manualmente.



--
.Mediante la interfaz de usuario del cliente de vSphere
--

NOTE: Los almacenes de datos vVols no admiten la adición directa de un usuario SVM a través de la interfaz de usuario del cliente vSphere.

. Inicie sesión en el cliente de vSphere.
. En la página de accesos directos, seleccione *Herramientas de NetApp ONTAP* en la sección de plugins.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Añada el back-end de almacenamiento y proporcione la dirección IP del servidor, el nombre de usuario, la contraseña y los detalles del puerto.
+

NOTE: Puede agregar un backend de almacenamiento utilizando credenciales basadas en clúster con LIF de administración IPv4 o IPv6.  Para agregar un usuario SVM directamente, proporcione credenciales basadas en SVM junto con un LIF de administración de SVM.  Si ya hay un clúster incorporado, no podrás incorporar nuevamente un usuario SVM desde ese clúster.

. Obtenga los certificados del clúster ONTAP automáticamente y autorice el certificado, o cárguelo manualmente buscando su ubicación.
. Si el backend de almacenamiento agregado es parte de la configuración de MetroCluster , las herramientas de ONTAP muestran la pantalla *Agregar par de MetroCluster *.  Seleccione *Agregar par* para agregar el backend de almacenamiento de pares.
+

NOTE: Después de que el sistema ONTAP realice un cambio y un retorno, ejecute el descubrimiento de herramientas ONTAP manualmente.



.¿Cuál es el siguiente?
Las herramientas ONTAP actualizan la lista para mostrar el nuevo backend de almacenamiento.

--
====
Las herramientas de ONTAP enumeran el back-end de almacenamiento recientemente agregado en la página *Back-ends de almacenamiento*.  Si un certificado vence en 30 días o menos, las herramientas de ONTAP muestran una advertencia en la columna de fecha de vencimiento del certificado.  Después del vencimiento, las herramientas ONTAP marcan el backend de almacenamiento como desconocido porque no puede conectarse al sistema de almacenamiento.

.Información relacionada
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["Configuración de los clústeres en una configuración MetroCluster"]
