---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: Añada instancias de vCenter Server a herramientas de ONTAP para VMware vSphere para configurar, gestionar y proteger sus almacenes de datos virtuales en el entorno de vCenter Server. 
---
= Agregar instancias de vCenter Server a las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Añada instancias de vCenter Server a herramientas de ONTAP para VMware vSphere para configurar, gestionar y proteger sus almacenes de datos virtuales en el entorno de vCenter Server. Cuando agrega varias instancias de vCenter Server, se requieren certificados de CA personalizados para una comunicación segura entre las herramientas de ONTAP y cada vCenter Server.

.Acerca de esta tarea
Las herramientas de ONTAP se integran con vCenter Server para realizar tareas de almacenamiento como aprovisionamiento, instantáneas y protección de datos directamente desde el cliente vSphere.

.Antes de empezar
* Asegúrate de que el certificado del servidor vCenter incluya una extensión válida de nombre alternativo del sujeto (SAN) con entradas tanto de DNS como de dirección IP. Por ejemplo:
+
[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
+
Si el certificado no incluye una extensión SAN, o si la extensión SAN no contiene los valores DNS o de dirección IP correctos, las operaciones de ONTAP tools pueden fallar debido a errores de validación del certificado.

* El identificador de red primario (PNID) del vCenter Server debe incluirse en los detalles de la SAN. El PNID y el nombre DNS deben ser idénticos y resolubles en DNS.
* Se recomienda desplegar vCenter Server usando su nombre de dominio completo (FQDN) y asegurarte de que el SAN en el certificado incluya DNS Name=machine_FQDN para una compatibilidad y soporte óptimos.
* Para más información, consulta la documentación de VMware:
+
** https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-authentication/vsphere-security-certificates-authentication/certificate-requirements-for-different-solution-paths-authentication.html["vSphere requisitos de certificados para diferentes vías de solución"]
** https://knowledge.broadcom.com/external/article/316601/replace-vcenter-machine-ssl-certificate.html["Sustituye el certificado SSL de máquina de vCenter por un certificado firmado por una autoridad de certificación personalizada"]
** https://knowledge.broadcom.com/external/article/406282/error-subject-alternate-name-san-field-d.html["Error: el campo Subject Alternate Name (SAN) no contiene el PNID. Por favor, proporciona un certificado válido"]




[NOTE]
====
Si el FQDN no está disponible, puedes establecer el PNID en la dirección IP e incluir la dirección IP en la SAN. Sin embargo, esto no es recomendable por VMware.

====
.Pasos
. Abra un navegador web y vaya a la URL: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *vCenters* > *Add* para incorporar las instancias de vCenter Server. Proporcione la dirección IP o el nombre de host, el nombre de usuario, la contraseña y los detalles de puerto de vCenter.
. En las opciones avanzadas, obtenga el certificado de vCenter Server automáticamente (autorícelo) o cárguelo manualmente.
+

NOTE: No es necesario tener una cuenta de administrador para añadir instancias de vCenter a las herramientas de ONTAP. Se puede crear un rol personalizado sin la cuenta de administrador con permisos limitados. Consulte link:../concepts/rbac-vcenter-use.html["Utilice el control de acceso basado en roles de vCenter Server con herramientas de ONTAP para VMware vSphere 10"] para obtener más información.



Al agregar una instancia de vCenter Server a herramientas de ONTAP se activan automáticamente las siguientes acciones:

* Las herramientas ONTAP registran el complemento del cliente vCenter como un complemento remoto.
* Las Privileges personalizadas para los plugins y las API se aplican a la instancia de vCenter Server.
* Se crean roles personalizados para gestionar los usuarios.
* El plugin aparece como un acceso directo en la interfaz de usuario de vSphere.

