---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Asocie un back-end de almacenamiento con vCenter Server para crear una asignación entre el back-end de almacenamiento y la instancia incorporada de vCenter Server a nivel global. 
---
= Asocie un back-end de almacenamiento a una instancia de vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Asocie un backend de almacenamiento con una instancia de vCenter Server para habilitar el acceso a todas las instancias de vCenter Server.  Para la configuración de MetroCluster , cuando asocie un clúster de back-end de almacenamiento, asegúrese de asociar también su clúster par con vCenter Server.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione vCenter en la barra lateral.
. Seleccione los puntos suspensivos verticales junto a la instancia de vCenter Server que desea conectar a los backends de almacenamiento.
. En el menú desplegable, seleccione el backend de almacenamiento que desea asociar con la instancia de vCenter Server seleccionada.

