---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: Asocie un back-end de almacenamiento con vCenter Server para crear una asignación entre el back-end de almacenamiento y la instancia incorporada de vCenter Server a nivel global. 
---
= Asocie un back-end de almacenamiento a una instancia de vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Asocie un back-end de almacenamiento con vCenter Server para crear una asignación entre el back-end de almacenamiento y la instancia incorporada de vCenter Server a nivel global.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalancerIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione vCenter en la barra lateral.
. Seleccione los tres puntos verticales en la instancia de vCenter Server que desea asociar con los back-ends de almacenamiento.
. En el menú desplegable, seleccione el back-end de almacenamiento.
. Seleccione el back-end de almacenamiento en el menú desplegable y asocie la instancia de vCenter Server con el back-end de almacenamiento requerido.

