---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: Si no se configuró el acceso a la red, de forma predeterminada todas las direcciones IP detectadas desde el host ESXi se añaden a la política de exportación. 
---
= Configure el acceso a la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A menos que se haya configurado el acceso a la red, todas las direcciones IP descubiertas desde el host ESXi se incluyen automáticamente en la política de exportación.  Puede configurar la política para permitir solo ciertas direcciones IP y excluir otras; sin embargo, si intenta montar desde un host ESXi excluido, la operación fallará.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Seleccione *Herramientas de NetApp ONTAP* en la página de accesos directos en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP , vaya a *Configuración* > *Administrar acceso a la red* > *Editar*.
+
Para agregar varias direcciones IP, separe la lista con comas, rango, enrutamiento entre dominios sin clases (CIDR) o una combinación de los tres.

. Seleccione *Guardar*.

