---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords: ESXi multipath settings, HBA timeout settings, ONTAP tools host settings, NetApp storage failover 
summary: Configura la multivía del host ESXi y los parámetros de tiempo de espera del HBA para un rendimiento óptimo del almacenamiento NetApp. 
---
= Configura los ajustes del host ESXi en ONTAP tools
:allow-uri-read: 
:firstname: = Configure ESXi host settings in ONTAP tools
:author: = Configure ESXi host settings in ONTAP tools
:authorinitials: =
:authors: = Configure ESXi host settings in ONTAP tools
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuración de los parámetros de multivía y tiempo de espera del host ESXi ayuda a mantener la disponibilidad y la integridad de los datos. Permite la conmutación automática por error a una ruta de almacenamiento de backup si la ruta principal deja de estar disponible.



[[apply-recommended-esxi-host-settings]]
== Aplica la configuración recomendada para el host ESXi

Las herramientas de ONTAP para VMware vSphere comprueban y establecen la configuración de multivía del host ESXi y el tiempo de espera de HBA que funcionan mejor con los sistemas de almacenamiento de NetApp.

.Acerca de esta tarea
Este proceso puede llevar tiempo, dependiendo de la configuración y la carga del sistema.  Puede ver el progreso en el panel Tareas recientes.

.Pasos
. En la página de inicio de VMware vSphere Web Client, seleccione *Hosts and Clusters*.
. En la página de accesos directos del cliente web de VMware vSphere, seleccione *NetApp ONTAP tools* en la sección de plugins.
. Vaya a la tarjeta *Conformidad de host ESXi* en la descripción general (consola) de las herramientas de ONTAP para el complemento de VMware vSphere.
. Selecciona el enlace *Aplicar la configuración recomendada*.
. En la ventana *Aplicar configuración de host recomendada*, seleccione los hosts que desea actualizar para usar la configuración recomendada de NetApp y seleccione *Siguiente*.
+

NOTE: Puede expandir el host ESXi para ver los valores actuales.

. En la página settings, seleccione los valores recomendados según sea necesario.
. En el panel de resumen, compruebe los valores y seleccione *Finalizar*. Puede realizar un seguimiento del progreso en el panel de tareas recientes.




[[set-esxi-host-values]]
== Configure los valores de host ESXi

Utilice las ONTAP tools for VMware vSphere para establecer tiempos de espera y otros valores en los hosts ESXi para lograr un rendimiento y una conmutación por error óptimos.  Establece estos valores en función de las pruebas de NetApp .

Puede configurar los siguientes valores en un host ESXi:



[[hbacna-adapter-settings]]
=== Configuración del adaptador de HBA/CNA

ONTAP tools establece los siguientes parámetros en los valores predeterminados:

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Tiempos de espera de FC HBA de Emulex
* Tiempos de espera de HBA FC de QLogic




[[mpio-settings]]
=== Configuración de MPIO

La configuración de MPIO selecciona y utiliza la mejor ruta disponible para los sistemas de almacenamiento NetApp.

Para entornos de alto rendimiento o al realizar pruebas con un único almacén de datos LUN, ajuste la configuración de equilibrio de carga de la política de selección de ruta (PSP) round-robin (VMW_PSP_RR) para mejorar el rendimiento.  Establezca el valor de IOPS predeterminado de 1000 a 1.


NOTE: La configuración de MPIO no se aplica a los protocolos NVMe, NVMe/FC y NVMe/TCP.



[[nfs-settings]]
=== Configuración de NFS

|===
| Parámetro | Definir este valor en... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 o superior 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===