---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: network access configuration, export policy, mount operation, ESXi hosts 
summary: Si no se configuró el acceso a la red, de forma predeterminada todas las direcciones IP detectadas desde el host ESXi se añaden a la política de exportación. 
---
= Configure el acceso a la red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De forma predeterminada, todas las direcciones IP detectadas desde el host ESXi se agregan automáticamente a la política de exportación, a menos que configure el acceso a la red.  Puede modificar la política de exportación para permitir el acceso sólo desde direcciones IP específicas.  Si un host ESXi excluido intenta una operación de montaje, la operación falla.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Seleccione *Herramientas de NetApp ONTAP* en la página de accesos directos en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP , vaya a *Configuración* > *Administrar acceso a la red* > *Editar*.
+
Para agregar varias direcciones IP, separe la lista con comas, rango, enrutamiento entre dominios sin clases (CIDR) o una combinación de los tres.

. Seleccione *Guardar*.

