---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords: create datastore, ONTAP tools NFS VMFS vVols, host cluster datastore provisioning, nconnect datastore settings 
summary: Crea almacenes de datos NFS, VMFS o vVols en ONTAP tools a nivel de host o de clúster de hosts. 
---
= Crear un almacén de datos en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Crea un almacén de datos NFS, VMFS o vVols a nivel de host o de clúster de hosts. Cuando creas un almacén de datos a nivel de clúster de hosts, ONTAP tools lo monta en todos los hosts de destino, siempre que tengas los Privileges necesarios.



[[interoperability-between-native-datastores-and-ontap-tools-managed-datastores]]
== Interoperabilidad entre los almacenes de datos nativos y los almacenes de datos gestionados por ONTAP tools

A partir de las ONTAP tools for VMware vSphere 10.4, las herramientas ONTAP crean igroups anidados para almacenes de datos, con igroups principales específicos para los almacenes de datos y igroups secundarios asignados a los hosts.  Puede crear igroups planos desde ONTAP System Manager y usarlos para crear almacenes de datos VMFS sin utilizar herramientas ONTAP . Referirse a https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Administrar iniciadores SAN y igroups"] Para más información.

Después de incorporar el almacenamiento y ejecutar el descubrimiento del almacén de datos, las herramientas de ONTAP cambian los igroups planos en los almacenes de datos VMFS a igroups anidados.  No es posible utilizar igroups planos anteriores para crear nuevos almacenes de datos.  Utilice la interfaz de herramientas ONTAP o la API REST para reutilizar igroups anidados.

[role="tabbed-block"]
====
.Cree un almacén de datos vVols
--
A partir de ONTAP tools for VMware vSphere 10.3, puedes crear un datastore de vVols en sistemas ASA r2 con eficiencia de espacio thin. El VASA Provider crea un contenedor y los endpoints de protocolo deseados al crear el datastore de vVol. El VASA Provider no asigna ningún volumen de respaldo a este contenedor.

.Antes de empezar
* Asegúrate de que los agregados raíz no están asignados a la SVM.
* Compruebe que el proveedor de VASA esté registrado en la instancia de vCenter seleccionada.
* Para los sistemas de almacenamiento ASA r2, no se requiere la asignación de SVM a agregados.


.Pasos
. Inicia sesión en el vSphere Client.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Crear almacén de datos*.
. Selecciona vVols como *tipo de almacén de datos*.
. Introduzca la información de *Nombre del almacén de datos* y *Protocolo*.
+

NOTE: El sistema R2 de ASA es compatible con los protocolos iSCSI y FC para vVols.

. Seleccione la máquina virtual de almacenamiento donde desea crear el almacén de datos.
. En *Opciones avanzadas*:
+
** Si seleccionas la *Política de exportación personalizada*, ejecuta el proceso de detección en vCenter para todos los objetos antes de continuar. NetApp recomienda que no uses esta opción.
** Puedes seleccionar un nombre de *grupo iniciador personalizado* para los protocolos iSCSI y FC.
+

NOTE: En el caso de una SVM ASA r2, no se crean unidades de almacenamiento (LUNs/espacios de nombres), ya que el datastore es únicamente un contenedor lógico.



. En el panel *Atributos de almacenamiento*, puede crear nuevos volúmenes o utilizar los volúmenes existentes. Sin embargo, no es posible combinar estos dos tipos de volúmenes para crear un almacén de datos vVols.
+
Al crear un nuevo volumen, puedes activar QoS en el almacén de datos. Por defecto, se crea un volumen por cada solicitud de creación de LUN. Omite este paso para los almacenes de datos vVols en los sistemas de almacenamiento ASA r2.

. Revise su selección en el panel *Resumen* y seleccione *Finalizar*.


--
.Cree un almacén de datos NFS
--
Un almacén de datos NFS conecta los hosts ESXi al almacenamiento compartido mediante el protocolo NFS. Es sencillo y flexible, y los entornos VMware vSphere lo utilizan habitualmente.

.Pasos
. Inicia sesión en el vSphere Client.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Crear almacén de datos*.
. Seleccione NFS en el campo *Datastore type*.
. Introduce el nombre del almacén de datos, el tamaño y la información del protocolo en el panel *Nombre y protocolo*.
+
.. Selecciona *Datastore cluster* y *Kerberos authentication* en las *opciones avanzadas*.
+

NOTE: La autenticación Kerberos solo está disponible cuando se selecciona el protocolo NFS 4,1.

.. Especifica el *número de conexiones (nconnect)* para el almacén de datos. El valor por defecto es 4, configurable de 1 a 8. Si el valor que eliges es mayor que la configuración actual de nconnect a nivel de host, ONTAP tools actualiza la configuración de nconnect a nivel de host para que coincida.


. En el panel *Almacenamiento*, selecciona *Plataforma* y *Storage VM*.
. Si seleccionas *Política de exportación personalizada* en *Opciones avanzadas*, ejecuta el proceso de detección en vCenter para todos los objetos antes de continuar.
+

NOTE: No se puede crear un almacén de datos NFS utilizando la política de volumen raíz o predeterminada de SVM.

+
** En las *Opciones avanzadas*, el botón de selección *Asimétrico* solo aparece si seleccionas rendimiento o capacidad en la lista desplegable de plataformas. Sin embargo, la opción *Asimétrico* no se aplica a la creación de datastore NFS.
** Cuando eliges la opción *Any* en el menú desplegable de la plataforma, todas las SVM en el vCenter son visibles. La plataforma y la configuración asimétrica no afectan la visibilidad.


. En el panel *Atributos de almacenamiento*, selecciona el agregado para la creación del volumen. En las *Opciones avanzadas*, selecciona *Reserva de espacio* y *Habilitar QoS* según sea necesario.
. En el panel *Resumen*, revisa las opciones seleccionadas y selecciona *Finalizar*.


Las herramientas ONTAP crean el almacén de datos NFS y lo montan en todos los hosts.

--
.Cree un almacén de datos de VMFS
--
VMFS es un sistema de archivos agrupado para almacenar archivos de máquinas virtuales.  Varios hosts ESXi pueden acceder a los mismos archivos de VM simultáneamente para las funciones vMotion y alta disponibilidad.

.Antes de empezar
* Habilite los servicios y las LIF para cada protocolo en el almacenamiento de ONTAP.
* Para los sistemas de almacenamiento ASA r2, no se requiere la asignación de SVM a agregados.
* Configure el host ESXi si utiliza el protocolo NVMe/TCP:
+
.. Revise la https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guía de compatibilidad de VMware"]
+

NOTE: VMware vSphere 7,0 U3 y las versiones posteriores admiten el protocolo NVMe/TCP. Sin embargo, se recomienda VMware vSphere 8,0 y versiones posteriores.

.. Comprueba si el fabricante de la tarjeta de interfaz de red (NIC) es compatible con las NIC de ESXi con el protocolo NVMe/TCP.
.. Configure la NIC ESXi para NVMe/TCP según las especificaciones del proveedor de NIC.
.. Cuando utilice la versión de VMware vSphere 7, siga las instrucciones del sitio de VMware https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Configure el enlace de VMkernel para el adaptador de NVMe over TCP"] para configurar el enlace de puerto NVMe/TCP. Al utilizar la versión VMware vSphere 8, siga https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Configurar NVMe over TCP en ESXi"] a , para configurar el enlace de puerto NVMe/TCP.
.. Para la versión de VMware vSphere 7, siga las instrucciones de la página https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Habilite los adaptadores de software de NVMe over RDMA o NVMe over TCP"] para configurar los adaptadores de software NVMe/TCP. Para la versión VMware vSphere 8, siga https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Añada adaptadores de software NVMe sobre RDMA o NVMe over TCP"] para configurar los adaptadores de software NVMe/TCP.
.. Ejecuta la acción link:../configure/discover-storage-systems-and-hosts.html["Detectar sistemas de almacenamiento y hosts"] en el host ESXi. Para obtener más información, consulta  https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Cómo configurar NVMe/TCP con vSphere 8,0 Update 1 y ONTAP 9.13,1 para almacenes de datos VMFS"].


* Si utilizas el protocolo NVMe/FC, sigue estos pasos para configurar el host ESXi:
+
.. Si aún no está activado, activa NVMe over Fabrics (NVMe-oF) en tus hosts ESXi.
.. Complete la división en zonas de SCSI.
.. Asegúrese de que los hosts ESXi y el sistema ONTAP estén conectados en una capa física y lógica.




Para configurar una SVM de ONTAP para el protocolo FC, consulte https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Configure una SVM para FC"] .

Para obtener más información sobre el uso del protocolo NVMe/FC con VMware vSphere 8,0, consulte https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configuración de host de NVMe-oF para ESXi 8.x con ONTAP"] .

Para obtener más información sobre el uso de NVMe/FC con VMware vSphere 7.0, consulta https://docs.netapp.com/us-en/ontap-sanhost/nvme-esxi-7.html["Guía de configuración de hosts ONTAP NVMe/FC"].

.Pasos
. Inicia sesión en el vSphere Client.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Crear almacén de datos*.
. Selecciona el tipo de almacén de datos VMFS.
. Introduce el nombre, el tamaño y la información sobre el protocolo del almacén de datos en el panel *Nombre y protocolo*. Para añadir el nuevo almacén de datos a un clúster VMFS ya existente, selecciona el clúster de almacenes de datos en *Opciones avanzadas*.
. Selecciona la máquina virtual de almacenamiento en el panel *Almacenamiento*. Introduce el *nombre personalizado del grupo de iniciadores* en la sección *Opciones avanzadas* según sea necesario. Puedes elegir un igroup ya existente para el datastore o crear un nuevo igroup con un nombre personalizado.
+
Cuando se selecciona el protocolo NVMe/FC o NVMe/TCP, se crea un nuevo subsistema de espacio de nombres que se usa para la asignación de espacios de nombres. ONTAP tools crea el subsistema de espacio de nombres usando el nombre generado automáticamente que incluye el nombre del datastore. Puedes cambiar el nombre del subsistema de espacio de nombres en el campo *custom namespace subsystem name* en las *Advanced options* del panel *Storage*.

. Desde el panel *Atributos de almacenamiento*:
+
.. Seleccione *Aggregate* de las opciones desplegables.
+

NOTE: En el caso de los sistemas de almacenamiento ASA r2, la opción *Agregado* no aparece porque el almacenamiento está desagregado. Cuando eliges un SVM del tipo de sistema de almacenamiento ASA r2, la página *Atributos de almacenamiento* muestra opciones para habilitar QoS.

.. Las herramientas ONTAP crean una unidad de almacenamiento (LUN/espacio de nombres) con una reserva de espacio reducida según el protocolo seleccionado.
+

NOTE: A partir de ONTAP 9.16.1, los sistemas de almacenamiento R2 de ASA admiten hasta 12 nodos por clúster.

.. Selecciona el *nivel de servicio de rendimiento* para un sistema de almacenamiento ASA r2 con un SVM de 12 nodos en un clúster heterogéneo. Esta opción no está disponible si el SVM seleccionado es un clúster homogéneo o usa un usuario de SVM.
+
'Any' es el valor de nivel de servicio de rendimiento (PSL) por defecto. Este ajuste crea la unidad de almacenamiento mediante el algoritmo de ubicación equilibrada de ONTAP. Sin embargo, puede seleccionar la opción Performance o Extreme según sea necesario.

.. Seleccione *Usar volumen existente*, *Activar QoS* opciones según sea necesario, y proporcione los detalles.
+

NOTE: En el tipo de almacenamiento ASA r2, la creación o selección de volúmenes no se aplica a la creación de unidades de almacenamiento (LUN/Namespace). Por lo tanto, estas opciones no se muestran.

+

NOTE: No puede utilizar el volumen existente para crear un almacén de datos VMFS con el protocolo NVMe/FC o NVMe/TCP.  Cree un nuevo volumen para el almacén de datos VMFS.



. En la ventana *Protección*, selecciona *Proteger este almacén de datos mediante la replicación de SnapMirror* para activar la protección. Puedes añadir el almacén de datos a un grupo de protección ya existente o crear uno nuevo. Para crear un nuevo grupo de protección:
+
.. Introduce un *nombre de grupo de protección*.
.. Configura la relación SnapMirror. Si seleccionas la política Automated Failover Duplex (AFD), configura los parámetros del clúster de hosts antes de continuar. Para obtener más información, consulta link:../protect/config-proximity.html["Configura el clúster para la protección del almacén de datos con ONTAP tools"].
+

NOTE: Si el volumen seleccionado ya forma parte de otra configuración de protección, la siguiente página de protección se desactiva y aparece un mensaje informativo. Si el almacén de datos no es apto para protección, la opción de protección se desactiva y se muestra el motivo de la inelegibilidad. Aun así, puedes crear el almacén de datos sin protección.



. Revise los detalles del almacén de datos en el panel *Summary* y seleccione *Finish*.
+

NOTE: Si un almacén de datos está protegido, ONTAP tools lo monta en todos los hosts del clúster.



.Resultado
Las herramientas ONTAP crean el almacén de datos VMFS y lo montan en todos los hosts.

--
====