---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords:  
summary: Cuando crea un almacén de datos en el nivel del clúster de host, las herramientas de ONTAP lo montan en todos los hosts de destino y habilitan la acción solo si tiene los privilegios necesarios. 
---
= Cree un almacén de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando crea un almacén de datos en el nivel del clúster de host, las herramientas de ONTAP lo montan en todos los hosts de destino y habilitan la acción solo si tiene los privilegios necesarios.

*Interoperabilidad entre almacenes de datos nativos con vCenter Server y almacenes de datos administrados por herramientas ONTAP*

A partir de las ONTAP tools for VMware vSphere 10.4, las herramientas ONTAP crean igroups anidados para almacenes de datos, con igroups principales específicos para los almacenes de datos y igroups secundarios asignados a los hosts.  Puede crear igroups planos desde ONTAP System Manager y usarlos para crear almacenes de datos VMFS sin utilizar herramientas ONTAP . Referirse a https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Administrar iniciadores SAN y igroups"] Para más información.

Después de incorporar el almacenamiento y ejecutar el descubrimiento del almacén de datos, las herramientas de ONTAP cambian los igroups planos en los almacenes de datos VMFS a igroups anidados.  No es posible utilizar igroups planos anteriores para crear nuevos almacenes de datos.  Utilice la interfaz de herramientas ONTAP o la API REST para reutilizar igroups anidados.

[role="tabbed-block"]
====
.Cree un almacén de datos vVols
--
A partir de las ONTAP tools for VMware vSphere 10.3, puede crear un almacén de datos vVols en sistemas ASA r2 con eficiencia de espacio como thin.vVol.  El proveedor VASA crea un contenedor y los puntos finales de protocolo deseados mientras crea el almacén de datos vVol.  El proveedor VASA no asigna ningún volumen de respaldo a este contenedor.

.Antes de empezar
* Asegúrese de que los agregados raíz no estén asignados a SVM.
* Compruebe que el proveedor de VASA esté registrado en la instancia de vCenter seleccionada.
* En el sistema de almacenamiento ASA r2, la SVM debe asignarse al agregado para el usuario SVM.


.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Crear almacén de datos*.
. Seleccione vVols *Tipo de almacén de datos*.
. Introduzca la información de *Nombre del almacén de datos* y *Protocolo*.
+

NOTE: El sistema R2 de ASA es compatible con los protocolos iSCSI y FC para vVols.

. Seleccione la máquina virtual de almacenamiento donde desea crear el almacén de datos.
. En Opciones avanzadas:
+
** Si selecciona la *Política de exportación personalizada*, asegúrese de ejecutar la detección en vCenter para todos los objetos.  Se recomienda que no utilice esta opción.
** Puede seleccionar el nombre de *Grupo de iniciadores personalizado* para los protocolos iSCSI y FC.
+

NOTE: En el sistema de almacenamiento ASA r2 tipo SVM, no se crean unidades de almacenamiento (LUN/espacio de nombres) porque el almacén de datos es solo un contenedor lógico.



. En el panel *Atributos de almacenamiento*, puede crear nuevos volúmenes o utilizar los volúmenes existentes. Sin embargo, no es posible combinar estos dos tipos de volúmenes para crear un almacén de datos vVols.
+
Al crear un nuevo volumen, puede habilitar QoS en el almacén de datos.  De forma predeterminada, se crea un volumen por cada solicitud creada por LUN.  Omita este paso para los almacenes de datos vVols en sistemas de almacenamiento ASA r2.

. Revise su selección en el panel *Resumen* y seleccione *Finalizar*.


--
.Cree un almacén de datos NFS
--
Un almacén de datos NFS conecta hosts ESXi al almacenamiento compartido mediante el protocolo NFS.  Son simples y flexibles y se utilizan en entornos VMware vSphere.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Crear almacén de datos*.
. Seleccione NFS en el campo *Datastore type*.
. Introduzca el nombre del almacén de datos, el tamaño y la información del protocolo en el panel *Nombre y protocolo*. Seleccione *Datastore cluster* y *Kerberos authentication* en las opciones avanzadas.
+

NOTE: La autenticación Kerberos solo está disponible cuando se selecciona el protocolo NFS 4,1.

. Seleccione *Plataforma* y *Storage VM* en el panel *Almacenamiento*.
. Si selecciona *Política de exportación personalizada* en las opciones avanzadas, ejecutará la detección en vCenter para todos los objetos.  Se recomienda que no utilice esta opción.
+

NOTE: No se puede crear un almacén de datos NFS utilizando la política de volumen raíz o predeterminada de SVM.

+
** En las opciones avanzadas, el botón de alternar *Asimétrico* solo es visible si se selecciona el rendimiento o la capacidad en el menú desplegable de la plataforma.
** Cuando elige la opción *Cualquiera* en el menú desplegable de la plataforma, puede ver todas las SVM en vCenter.  Plataforma y bandera asimétrica no afectan visibilidad.


. Seleccione el agregado para la creación de volúmenes en el panel *Atributos de almacenamiento*. En las opciones avanzadas, elija *Space Reserve* y *Enable QoS* según sea necesario.
. Revise las selecciones en el panel *Resumen* y seleccione *Finalizar*.


Las herramientas ONTAP crean el almacén de datos NFS y lo montan en todos los hosts.

--
.Cree un almacén de datos de VMFS
--
VMFS es un sistema de archivos agrupado para almacenar archivos de máquinas virtuales.  Varios hosts ESXi pueden acceder a los mismos archivos de VM simultáneamente para las funciones vMotion y alta disponibilidad.

En un clúster protegido:

* Solo puede crear almacenes de datos VMFS.  Agregar un almacén de datos VMFS a un clúster protegido lo protege automáticamente.
* No es posible crear un almacén de datos en un centro de datos con uno o varios clústeres de hosts protegidos.
* No se puede crear un almacén de datos en un host ESXi si el clúster del host principal está protegido por una "Política de dúplex de conmutación por error automatizada" (configuración uniforme o no uniforme).
* Un almacén de datos VMFS solo se puede crear en un host ESXi protegido por una relación asíncrona. No se puede crear ni montar un almacén de datos en un host ESXi que forma parte de un clúster de hosts protegido por la política «Automatic Failover Duplex».


.Antes de empezar
* Habilite los servicios y las LIF para cada protocolo en el almacenamiento de ONTAP.
* Asigne SVM al agregado para el usuario de SVM en el sistema de almacenamiento ASA R2.
* Configure el host ESXi si utiliza el protocolo NVMe/TCP:
+
.. Revise la https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["Guía de compatibilidad de VMware"]
+

NOTE: VMware vSphere 7,0 U3 y las versiones posteriores admiten el protocolo NVMe/TCP. Sin embargo, se recomienda VMware vSphere 8,0 y versiones posteriores.

.. Compruebe si el proveedor de la tarjeta de interfaz de red (NIC) admite la NIC ESXi con el protocolo NVMe/TCP.
.. Configure la NIC ESXi para NVMe/TCP según las especificaciones del proveedor de NIC.
.. Cuando utilice la versión de VMware vSphere 7, siga las instrucciones del sitio de VMware https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["Configure el enlace de VMkernel para el adaptador de NVMe over TCP"] para configurar el enlace de puerto NVMe/TCP. Al utilizar la versión VMware vSphere 8, siga https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["Configurar NVMe over TCP en ESXi"] a , para configurar el enlace de puerto NVMe/TCP.
.. Para la versión de VMware vSphere 7, siga las instrucciones de la página https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Habilite los adaptadores de software de NVMe over RDMA o NVMe over TCP"] para configurar los adaptadores de software NVMe/TCP. Para la versión VMware vSphere 8, siga https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["Añada adaptadores de software NVMe sobre RDMA o NVMe over TCP"] para configurar los adaptadores de software NVMe/TCP.
.. Ejecute link:../configure/discover-storage-systems-and-hosts.html["Detectar sistemas de almacenamiento y hosts"] la acción en el host ESXi. Para obtener más información, consulte https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["Cómo configurar NVMe/TCP con vSphere 8,0 Update 1 y ONTAP 9.13,1 para almacenes de datos VMFS"].


* Si utiliza el protocolo NVME/FC, realice los siguientes pasos para configurar el host ESXi:
+
.. Si todavía no está habilitado, habilite NVMe over Fabrics(NVMe-oF) en los hosts ESXi.
.. Complete la división en zonas de SCSI.
.. Asegúrese de que los hosts ESXi y el sistema ONTAP estén conectados en una capa física y lógica.




Para configurar una SVM de ONTAP para el protocolo FC, consulte https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["Configure una SVM para FC"] .

Para obtener más información sobre el uso del protocolo NVMe/FC con VMware vSphere 8,0, consulte https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configuración de host de NVMe-oF para ESXi 8.x con ONTAP"] .

Para obtener más información sobre el uso de NVMe/FC con VMware vSphere 7,0, consulte https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Guía de configuración de hosts ONTAP NVMe/FC"] y http://www.netapp.com/us/media/tr-4684.pdf["TR-4684"].

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Crear almacén de datos*.
. Seleccione el tipo de almacén de datos VMFS.
. Ingrese el nombre del almacén de datos, el tamaño y la información del protocolo en el panel *Nombre y protocolo*.  Para agregar el nuevo almacén de datos a un clúster VMFS existente, seleccione el clúster del almacén de datos en Opciones avanzadas.
. Seleccione Storage VM en el panel *Storage*. Proporcione el *Nombre de grupo iniciador personalizado* en la sección *Opciones avanzadas* según sea necesario. Es posible seleccionar un igroup existente para el almacén de datos o crear un igroup nuevo con un nombre personalizado.
+
Cuando se selecciona el protocolo NVMe/FC o NVMe/TCP, se crea un nuevo subsistema de espacio de nombres y se utiliza para la asignación de espacios de nombres.  Las herramientas ONTAP crean el subsistema de espacio de nombres utilizando el nombre generado automáticamente que incluye el nombre del almacén de datos.  Puede cambiar el nombre del subsistema de espacio de nombres en el campo *nombre del subsistema de espacio de nombres personalizado* en las opciones avanzadas del panel *Almacenamiento*.

. Desde el panel *storage attributes*:
+
.. Seleccione *Aggregate* de las opciones desplegables.
+

NOTE: Para los sistemas de almacenamiento ASA r2, la opción *Agregar* no se muestra porque el almacenamiento está desagregado. Al elegir un sistema de almacenamiento ASA r2 de tipo SVM, la página de atributos de almacenamiento muestra las opciones para habilitar QoS.

.. Las herramientas ONTAP crean una unidad de almacenamiento (LUN/espacio de nombres) con una reserva de espacio reducida según el protocolo seleccionado.
+

NOTE: A partir de ONTAP 9.16.1, los sistemas de almacenamiento R2 de ASA admiten hasta 12 nodos por clúster.

.. Seleccione el *Nivel de servicio de rendimiento* para los sistemas de almacenamiento ASA R2 con 12 nodos SVM que es un clúster heterogéneo. Esta opción no está disponible si la SVM seleccionada es un clúster homogéneo o utiliza un usuario de SVM.
+
'Any' es el valor de nivel de servicio de rendimiento (PSL) por defecto. Este ajuste crea la unidad de almacenamiento mediante el algoritmo de ubicación equilibrada de ONTAP. Sin embargo, puede seleccionar la opción Performance o Extreme según sea necesario.

.. Seleccione *Usar volumen existente*, *Activar QoS* opciones según sea necesario, y proporcione los detalles.
+

NOTE: En el tipo de almacenamiento ASA r2, la creación o selección de volumen no se aplica a la creación de unidades de almacenamiento (LUN/espacio de nombres).  Por lo tanto, estas opciones no se muestran.

+

NOTE: No puede utilizar el volumen existente para crear un almacén de datos VMFS con el protocolo NVMe/FC o NVMe/TCP.  Cree un nuevo volumen para el almacén de datos VMFS.



. Revise los detalles del almacén de datos en el panel *Summary* y seleccione *Finish*.



NOTE: Si crea el almacén de datos en un clúster protegido, se muestra un mensaje de solo lectura que indica que el almacén de datos se está montando en un clúster protegido.

.Resultado
Las herramientas ONTAP crean el almacén de datos VMFS y lo montan en todos los hosts.

--
====