---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords: discover storage systems and hosts, ONTAP tools first discovery, ESXi host and LUN discovery, NFS export discovery 
summary: Descubre los hosts ESXi, los LUN, las exportaciones NFS y los sistemas de almacenamiento NetApp en las herramientas de ONTAP al primer inicio. 
---
= Descubre sistemas de almacenamiento y hosts en las herramientas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando las ONTAP tools for VMware vSphere se inician en vSphere Client por primera vez, descubren automáticamente los hosts ESXi, sus LUN asociados y las exportaciones NFS, así como los sistemas de almacenamiento NetApp que poseen estos recursos.

.Antes de empezar
* Asegúrese de que todos los hosts ESXi estén encendidos y conectados.
* Asegúrese de que todas las máquinas virtuales de almacenamiento (SVM) que se van a descubrir estén en ejecución y que cada nodo del clúster tenga al menos un LIF de datos configurado para el protocolo de almacenamiento en uso (NFS o iSCSI).


.Acerca de esta tarea
Puede descubrir nuevos sistemas de almacenamiento o actualizar los existentes para obtener los últimos detalles de capacidad y configuración.  También puede cambiar las ONTAP tools for VMware vSphere para el acceso al sistema de almacenamiento.

Al detectar los sistemas de almacenamiento, las herramientas de ONTAP para VMware vSphere recopilan información de los hosts ESXi que gestiona la instancia de vCenter Server.

.Pasos
. Desde la página de inicio del cliente de vSphere, selecciona *Hosts y clústeres*.
. Haz clic con el botón derecho en el centro de datos requerido y selecciona *NetApp ONTAP tools* > *Actualizar datos de host y almacenamiento*.
+
En el cuadro de diálogo *Confirmar*, confirme su elección.

. Seleccione los controladores de almacenamiento detectados que tengan el estado `Authentication Failure` y seleccione *Acciones* > *Modificar*.
. Rellene la información necesaria en el cuadro de diálogo *Modificar sistema de almacenamiento*.
. Repita los pasos 4 y 5 para todas las controladoras de almacenamiento con `Authentication Failure` estado.


Una vez completado el proceso de detección, realice las siguientes acciones:

* Utilice las herramientas de ONTAP para VMware vSphere para configurar las opciones del host ESXi para los hosts que muestran el icono de alerta en la columna de configuración del adaptador, la columna MPIO settings o la columna NFS settings.
* Proporcione las credenciales del sistema de almacenamiento.

