---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: Es posible configurar tiempos de espera y otros valores en los hosts ESXi mediante las herramientas de ONTAP para VMware vSphere con el fin de garantizar el mejor rendimiento y una conmutación al respaldo correcta. Los valores que las herramientas ONTAP para conjuntos de VMware vSphere se basan en las pruebas internas de NetApp. 
---
= Configure los valores de host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar tiempos de espera y otros valores en los hosts ESXi mediante las herramientas de ONTAP para VMware vSphere con el fin de garantizar el mejor rendimiento y una conmutación al respaldo correcta. Los valores que las herramientas ONTAP para conjuntos de VMware vSphere se basan en las pruebas internas de NetApp.

Puede configurar los siguientes valores en un host ESXi:



== Configuración del adaptador de HBA/CNA

Configura los ajustes de tiempo de espera recomendados del adaptador de bus de host para los sistemas de almacenamiento de NetApp.

|===
| Parámetros | Definir este valor en... 


| Disk.QFullSampleSize | 32 para todas las configuraciones. Si configura este valor, se evitan los errores de I/O. 


| Disk.QFullThreshold | 8 para todas las configuraciones. Si configura este valor, se evitan los errores de I/O. 


| Tiempos de espera de FC HBA de Emulex | Valor predeterminado. 


| Tiempos de espera de HBA FC de QLogic | Valor predeterminado. 
|===


== Configuración de MPIO

La configuración de MPIO define las rutas preferidas para los sistemas de almacenamiento de NetApp. La configuración de MPIO determina cuáles de las rutas disponibles están optimizadas (a diferencia de las rutas no optimizadas que atraviesan el cable de interconexión) y establece la ruta preferida en una de estas rutas.

En entornos de alto rendimiento, o cuando esté probando el rendimiento con un único almacén de datos LUN, considere la posibilidad de cambiar la configuración del equilibrio de carga de la política de selección de ruta (PSP) round-robin (VMW_PSP_RR) de la configuración de IOPS predeterminada de 1000 a un valor de 1.



== Configuración de NFS

|===


| Parámetro | Definir este valor en... 


| NET.TcpipHeapSize | 32 


| NET.TcpipHeapMax | 1024MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 o superior 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===