---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords: install NFS VAAI plug-in, NetApp NFS Plug-in for VAAI, ONTAP tools VAAI installation, vSphere NFS offload 
summary: Instala el complemento NFS de NetApp para VAAI usando ONTAP tools for VMware vSphere. 
---
= Instala el complemento VAAI de NFS mediante las ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento NFS vStorage API for Array Integration (NFS VAAI) conecta VMware vSphere a las matrices de almacenamiento NFS, permitiendo que la matriz de almacenamiento gestione ciertas operaciones de almacenamiento en lugar de los hosts ESXi. Utiliza ONTAP tools for VMware vSphere para instalar el complemento VAAI.

.Antes de empezar
* Descargue https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plugin NFS de NetApp para VAAI de VMware"] el paquete de instalación.
* Asegúrate de que tienes hosts ESXi con vSphere 7.0 U3 (último parche o posterior) y ONTAP 9.14.1 o posterior.
* Montar un almacén de datos NFS.


.Pasos
. Inicie sesión en el cliente de vSphere.
. Selecciona *Accesos directos* > *NetApp ONTAP tools* en la sección de complementos.
. Selecciona *Configuración* > *Herramientas NFS VAAI*.
. Si ya ha cargado el complemento VAAI en vCenter Server, seleccione *Cambiar* en *Versión existente*.  Si no lo has hecho, selecciona *Subir*.
. Busque y seleccione el `.vib` archivo y seleccione *Cargar* para cargar el archivo en las herramientas de ONTAP.
. Selecciona *Install on ESXi host*, selecciona el host ESXi en el que quieres instalar el complemento NFS VAAI y luego selecciona *Install*.
+
vSphere Web Client muestra solo los hosts ESXi que pueden instalar el complemento. Puede supervisar el progreso de la instalación en la sección de tareas recientes.

. Reinicie el host ESXi manualmente después de la instalación.
+
Después de reiniciar el host ESXi, ONTAP tools for VMware vSphere detecta y habilita automáticamente el complemento NFS VAAI.



.El futuro
Después de instalar el complemento NFS VAAI y reiniciar su host ESXi, configure las políticas de exportación de NFS para la descarga de copias de VAAI.  Asegúrese de que las normas de política de exportación cumplan estos requisitos:

* El volumen ONTAP relevante permite llamadas NFSv4.
* El usuario root permanece como root y se permite NFSv4 en todos los volúmenes principales de unión.
* La opción de compatibilidad con VAAI se configura en el servidor NFS correspondiente.


Para obtener más información, consulte https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Configure las políticas de exportación de NFS correctas para la copia de datos descargados de VAAI"] Artículo de KB.

.Información relacionada
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Compatibilidad con VMware vStorage sobre NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Habilitar o deshabilitar NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["Compatibilidad con ONTAP para NFSv4.2"]
