---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Puede instalar el plugin NFS de NetApp para las API de VMware vStorage para la integración de cabinas \(VAAI\) utilizando las herramientas ONTAP para VMware vSphere.' 
---
= Instalar el complemento NFS VAAI mediante las herramientas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento NFS vStorage API for Array Integration (NFS VAAI) conecta VMware vSphere con matrices de almacenamiento NFS.  Utilice las ONTAP tools for VMware vSphere para instalar el complemento VAAI. Esto permite que la matriz de almacenamiento NFS gestione ciertas operaciones de almacenamiento en lugar de los hosts ESXi.

.Antes de empezar
* Descargue https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plugin NFS de NetApp para VAAI de VMware"] el paquete de instalación.
* Asegúrese de que tiene el host ESXi y la revisión más reciente de vSphere 7.0U3 o versiones posteriores, y de ONTAP 9.14.1 o versiones posteriores.
* Montar un almacén de datos NFS.


.Pasos
. Inicie sesión en el cliente de vSphere.
. Selecciona *Atajos* > *Herramientas NetApp ONTAP* en la sección de plug-ins.
. Selecciona *Configuración* > *Herramientas de VAAI NFS*.
. Si ya ha cargado el complemento VAAI en vCenter Server, seleccione *Cambiar* en *Versión existente*.  Si no lo has hecho, selecciona *Subir*.
. Busque y seleccione el `.vib` archivo y seleccione *Cargar* para cargar el archivo en las herramientas de ONTAP.
. Seleccione *Instalar en el HOST ESXi*, seleccione el host ESXi en el que desea instalar el plugin VAAI NFS y, a continuación, seleccione *Instalar*.
+
vSphere Web Client muestra solo los hosts ESXi que pueden instalar el complemento. Puede supervisar el progreso de la instalación en la sección de tareas recientes.

. Reinicie el host ESXi manualmente después de la instalación.
+
Después de reiniciar el host ESXi, las ONTAP tools for VMware vSphere detectan y habilitan automáticamente el complemento NFS VAAI.



.El futuro
Después de instalar el complemento NFS VAAI y reiniciar su host ESXi, configure las políticas de exportación de NFS para la descarga de copias de VAAI.  Asegúrese de que las normas de política de exportación cumplan estos requisitos:

* El volumen ONTAP relevante permite llamadas NFSv4.
* El usuario root permanece como root y se permite NFSv4 en todos los volúmenes principales de unión.
* La opción de compatibilidad con VAAI se configura en el servidor NFS correspondiente.


Para obtener más información, consulte https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Configure las políticas de exportación de NFS correctas para la copia de datos descargados de VAAI"] Artículo de KB.

.Información relacionada
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Compatibilidad con VMware vStorage sobre NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Habilitar o deshabilitar NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["Compatibilidad con ONTAP para NFSv4.2"]
