---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: Puede registrar el proveedor VASA con una instancia de vCenter Server mediante la interfaz del complemento remoto de ONTAP tools for VMware vSphere . 
---
= Registra el proveedor VASA con una instancia de vCenter Server en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice las ONTAP tools for VMware vSphere para registrar el proveedor VASA con una instancia de vCenter Server.  Esto permite la gestión basada en políticas de almacenamiento, compatibilidad con vVols e integración con dispositivos VMware Live Site Recovery en sistemas ONTAP .

La configuración del proveedor VASA muestra el estado de registro del vCenter Server seleccionado.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Selecciona *Atajos* > *Herramientas NetApp ONTAP* en la sección de plug-ins.
. Seleccione *Configuración* > *Configuración del proveedor VASA*.  Las herramientas ONTAP muestran el estado de registro del proveedor VASA como no registrado.
. Seleccione el botón *Registrar* para registrar el proveedor VASA.
. Ingrese un nombre y credenciales para el proveedor de VASA.  El nombre de usuario solo puede contener letras, números y guiones bajos.  Establezca la longitud de la contraseña entre 8 y 256 caracteres.
. Seleccione *Registrar*.
. Después de un registro exitoso y una actualización de página, las herramientas de ONTAP muestran el estado, el nombre y la versión del proveedor VASA registrado.


.El futuro
Compruebe que el proveedor de VASA incorporado aparezca en la lista en VASA Provider desde el cliente de vCenter:

.Pasos
. Vaya a la instancia de vCenter Server.
. Inicie sesión con las credenciales de administrador.
. Selecciona *Proveedores de almacenamiento* > *Configurar*. Compruebe que el proveedor de VASA incorporado esté correctamente en la lista.

