---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: Conozca las nuevas capacidades disponibles en las ONTAP tools for VMware vSphere 10.5. 
---
= Novedades en las ONTAP tools for VMware vSphere 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca las nuevas capacidades disponibles en las ONTAP tools for VMware vSphere 10.5.

* *Calificación de plataforma*


Las ONTAP tools for VMware vSphere 10.5 agregan soporte para sistemas ASA r2, brindando compatibilidad con las últimas configuraciones de hardware y software.  Esta versión también incluye integración con ONTAP 9.16.1 y 9.17.1, ampliando los entornos compatibles.

* *Calificación y certificaciones de VMware*


Las ONTAP tools for VMware vSphere 10.5 cumplen con los estándares actuales de certificación de interoperabilidad de VMware y son compatibles tanto con el host ESXi como con vCenter Server.

* * Soporte MetroCluster *


Esta versión presenta soporte para configuraciones de MetroCluster (MCC), mejorando las capacidades de alta disponibilidad y recuperación ante desastres.

* *Seguridad y gestión de certificados*


Esta versión introduce una gestión optimizada de certificados autofirmados, mejorando tanto la experiencia del usuario como el cumplimiento de los estándares de seguridad.  Proporciona flujos de trabajo de validación de certificados mejorados para proteger ONTAP y las ONTAP tools for VMware vSphere .

* *Mejoras de replicación*


Esta versión admite la replicación VMFS con un grupo de consistencia jerárquico que incluye SRA y sincronización activa de SnapMirror en sistemas ASA r2.  Admite copias de seguridad de RPO cero para mejorar la protección y recuperación de datos.

* *Actualización y migración*


El proceso de actualización y migración de versiones anteriores de las ONTAP tools for VMware vSphere a las ONTAP tools for VMware vSphere 10.5 está diseñado para ser fluido y eficiente, minimizando el tiempo de inactividad y garantizando una transición sin problemas.



== Plataformas ONTAP compatibles y versiones de vCenter Server

Para obtener los detalles más recientes sobre la compatibilidad de versiones, consulte https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] .
