---
permalink: manage/add-vsphere-host.html 
sidebar: sidebar 
keywords: add vSphere host, ONTAP tools host discovery, register ESXi host, VMware host management 
summary: Agrega hosts de VMware vSphere a ONTAP tools for VMware vSphere. 
---
= Agrega hosts de VMware vSphere a las ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Agregue nuevos hosts de VMware vSphere a las ONTAP tools for VMware vSphere para administrar y proteger los almacenes de datos en los hosts.

.Pasos
. Agrega un host a tu clúster de VMware vSphere siguiendo las https://techdocs.broadcom.com/["Documentación técnica de Broadcom"] instrucciones.
. Después de agregar el host, vaya al menú principal de herramientas ONTAP y seleccione *Descubrir* en el panel de resumen. Espere a que finalice el proceso de descubrimiento. Como alternativa, puede esperar a que finalice la detección de host programada.


.Resultado
El nuevo host ahora es detectado y administrado por las ONTAP tools for VMware vSphere. Puede proceder a administrar el almacén de datos en el nuevo host.

.Temas relacionados
* link:../manage/mount-a-vvols-datastore.html["Monte un almacén de datos vVols"]en nuevos hosts.
* link:../manage/mount-datastores-on-host.html["Montar NFS y almacén de datos VMFS"]en nuevos hosts.

