---
permalink: manage/add-vsphere-host.html 
sidebar: sidebar 
keywords: add vSphere host, ONTAP tools host discovery, register ESXi host, VMware host management 
summary: Agrega hosts de VMware vSphere a ONTAP tools for VMware vSphere. 
---
= Agrega hosts de VMware vSphere a las ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Añade nuevos hosts de VMware vSphere a ONTAP tools for VMware vSphere para que puedas gestionar y proteger los almacenes de datos de los hosts.

.Pasos
. Agrega un host a tu clúster de VMware vSphere siguiendo las https://techdocs.broadcom.com/["Documentación técnica de Broadcom"] instrucciones.
. Después de añadir el host, ve al menú principal de ONTAP tools y selecciona *Discover* en el panel de resumen, o espera a que finalice la detección programada del host.


.Resultado
El nuevo host ahora es detectado y gestionado por ONTAP tools for VMware vSphere. Ahora puedes gestionar los almacenes de datos en el host.

.Temas relacionados
* link:../manage/mount-a-vvols-datastore.html["Monte un almacén de datos vVols"]en nuevos hosts.
* link:../manage/mount-datastores-on-host.html["Montar NFS y almacén de datos VMFS"]en nuevos hosts.

