---
permalink: manage/attach-detach-disk.html 
sidebar: sidebar 
keywords:  
summary: Conectar un disco de datos a una máquina virtual para expandir la capacidad de almacenamiento. 
---
= Conectar o desconectar un disco de datos de una máquina virtual en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga estos pasos para conectar o desconectar discos de datos de máquinas virtuales en vSphere y administrar sus recursos de almacenamiento.



== Conectar un disco de datos a una máquina virtual

Conecte un disco de datos a una máquina virtual para agregar más almacenamiento.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic derecho en una máquina virtual en el inventario y seleccione *Editar configuración*.
. En la pestaña *Virtual Hardware*, seleccione *Disco duro existente*.
. Seleccione la máquina virtual donde existe el disco.
. Seleccione el disco que desea adjuntar y seleccione el botón *Aceptar*.


.Resultado
El disco duro aparece en la lista Dispositivos de hardware virtual.



== Desconectar un disco de datos de la máquina virtual

Desconecte un disco de datos de una máquina virtual cuando ya no lo necesite.  El disco no se elimina; permanece en el sistema de almacenamiento ONTAP .

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic derecho en una máquina virtual en el inventario y seleccione *Editar configuración*.
. Mueva el puntero sobre el disco y seleccione * Eliminar *.
+

NOTE: El disco se elimina de la máquina virtual. Si otras máquinas virtuales comparten el disco, los archivos del disco no se eliminan.



.Información relacionada
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html["Agregar un nuevo disco duro a una máquina virtual"]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html["Agregar un disco duro existente a una máquina virtual"]
