---
permalink: manage/attach-detach-disk.html 
sidebar: sidebar 
keywords: attach data disk VM, detach VM disk, ONTAP tools virtual machine disk, VMware VM storage expansion 
summary: Conecta o desconecta los discos de datos de las máquinas virtuales para gestionar la capacidad de almacenamiento. 
---
= Conectar o desconectar un disco de datos de una máquina virtual en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conecta o desconecta discos de datos de máquinas virtuales en vSphere para gestionar la capacidad de almacenamiento.



[[attach-a-data-disk-to-a-virtual-machine]]
== Conectar un disco de datos a una máquina virtual

Conecte un disco de datos a una máquina virtual para agregar más almacenamiento.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haz clic con el botón derecho del ratón en una máquina virtual del inventario y selecciona *Editar configuración*.
. En la pestaña *Virtual Hardware*, seleccione *Disco duro existente*.
. Selecciona la máquina virtual que contiene el disco.
. Selecciona el disco que quieras conectar y selecciona *OK*.


.Resultado
El disco duro aparece en la lista Dispositivos de hardware virtual.



[[detach-a-data-disk-from-the-virtual-machine]]
== Desconectar un disco de datos de la máquina virtual

Desconecta un disco de datos de una máquina virtual cuando ya no lo necesites. El disco no se elimina y permanece en el sistema de almacenamiento ONTAP.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic derecho en una máquina virtual en el inventario y seleccione *Editar configuración*.
. Mueva el puntero sobre el disco y seleccione * Eliminar *.
+

NOTE: El disco se elimina de la máquina virtual. Si otras máquinas virtuales comparten el disco, los archivos del disco no se eliminan.



.Información relacionada
https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-a-new-hard-disk-to-a-virtual-machinevm-admin.html["Agregar un nuevo disco duro a una máquina virtual"]

https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/configuring-virtual-machine-hardwarevm-admin/virtual-disk-configurationvm-admin/add-a-hard-disk-to-a-virtual-machinevm-admin/add-an-existing-hard-disk-to-a-virtual-machinevm-admin.html["Agregar un disco duro existente a una máquina virtual"]
