---
permalink: manage/backup-settings.html 
sidebar: sidebar 
keywords: ONTAP tools backup settings, configure backup schedule, appliance backup configuration, ONTAP tools data protection 
summary: Activa o desactiva la copia de seguridad de ONTAP tools y configura la frecuencia de la copia de seguridad entre 10 y 60 minutos. 
---
= Editar la configuración de copia de seguridad de ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir de ONTAP tools for VMware vSphere 10.5, las copias de seguridad están habilitadas de forma predeterminada y se ejecutan cada 10 minutos. Puedes desactivar las copias de seguridad o cambiar la frecuencia de las copias de seguridad.

No desactives la copia de seguridad porque esto impide que las ONTAP tools mantengan un objetivo de punto de recuperación (RPO) bajo. Desactivar la copia de seguridad no elimina los archivos de copia de seguridad existentes. Puedes cambiar la frecuencia de la copia de seguridad a un valor entre 10 y 60 minutos.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione la opción *Configuración* > *Copia de seguridad* > *Editar*.
. En la ventana Editar, desactiva el backup o cambia la frecuencia del backup.

