---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: Una única instancia de herramientas de ONTAP para VMware vSphere puede gestionar varias instancias de vCenter Server. Las herramientas de ONTAP para VMware vSphere se ponen en marcha con un certificado autofirmado para el proveedor VASA. Con esto, solo se puede gestionar una instancia de vCenter Server para almacenes de datos vVols. 
---
= Gestionar certificados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se genera un certificado autofirmado para las herramientas ONTAP y el proveedor VASA de forma predeterminada durante la implementación. Puede utilizar la interfaz del Administrador de herramientas de ONTAP para renovar este certificado o reemplazarlo con un certificado CA personalizado. En implementaciones de varios vCenter, es necesario utilizar certificados CA personalizados.

.Antes de empezar
Deberías tener lo siguiente antes de empezar:

* El nombre de dominio asignado a la dirección IP virtual.
* Búsqueda DNS exitosa del nombre de dominio, confirmando que se resuelve a la dirección IP correcta.
* Certificados creados con el nombre de dominio y la dirección IP de las herramientas ONTAP .



NOTE: Una dirección IP de ONTAP Tools debe asignarse a un nombre de dominio completamente cualificado (FQDN). Los certificados deben contener el mismo FQDN asignado a la dirección IP de las herramientas de ONTAP en nombres alternativos de asunto o asunto.


NOTE: No se puede pasar de un certificado firmado por CA a un certificado autofirmado.

[role="tabbed-block"]
====
.Actualizar el certificado de herramientas de ONTAP
--
La pestaña Herramientas de ONTAP muestra detalles como el tipo de certificado (autofirmado/firmado por CA) y el nombre de dominio. Durante la implementación, se genera un certificado autofirmado de forma predeterminada. Puede renovar el certificado o actualizar el certificado a CA.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Selecciona *Certificados* > *Herramientas ONTAP* > *Renovar* para renovar los certificados.
+
Puede renovar el certificado si ha caducado o se acerca a su fecha de vencimiento. La opción de renovación está disponible cuando el tipo de certificado es firmado por CA. En la ventana emergente, proporcione los detalles del certificado de servidor, la clave privada, la CA raíz y el certificado intermedio.

+

NOTE: El sistema estará fuera de línea hasta que se renueve el certificado y se cerrará la sesión en la interfaz del Administrador de herramientas de ONTAP.

. Para actualizar el certificado autofirmado a un certificado de CA personalizado, seleccione la opción *Certificados* > *Herramientas de ONTAP* > *Actualizar a CA*.
+
.. En la ventana emergente, cargue el certificado de servidor, la clave privada de certificado de servidor, el certificado de CA raíz y los archivos de certificado intermedio.
.. Ingrese el FQDN de la IP del balanceador de carga para el cual generó este certificado y actualice el certificado.
+

NOTE: El sistema estará fuera de línea hasta que se complete la actualización y se cerrará la sesión en la interfaz del Administrador de herramientas de ONTAP.





--
.Actualizar el certificado de proveedor VASA
--
Las herramientas de ONTAP para VMware vSphere se ponen en marcha con un certificado autofirmado para el proveedor VASA. Con esto, solo se puede gestionar una instancia de vCenter Server para almacenes de datos vVols. Cuando se gestionan varias instancias de vCenter Server y se desea habilitar la funcionalidad vVols en ellas, debe cambiar el certificado autofirmado a un certificado de CA personalizado.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *Certificados* > *Proveedor VASA* o *Herramientas ONTAP* > *Renovar* para renovar los certificados.
. Seleccione *Certificados* > *Proveedor VASA* o *Herramientas ONTAP* > *Actualizar a CA* para actualizar el certificado autofirmado a un certificado de CA personalizado.
+
.. En la ventana emergente, cargue el certificado de servidor, la clave privada de certificado de servidor, el certificado de CA raíz y los archivos de certificado intermedio.
.. Ingrese el FQDN de la IP del balanceador de carga para el cual generó este certificado y actualice el certificado.
+

NOTE: El sistema estará fuera de línea hasta que se complete la actualización y se cerrará la sesión en la interfaz del Administrador de herramientas de ONTAP.





--
====