---
permalink: manage/change-valid-flag.html 
sidebar: sidebar 
keywords:  
summary: Puede cambiar el indicador de validación del certificado mediante la consola de mantenimiento. 
---
= Cambia el indicador de validación de certificados en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De forma predeterminada, el indicador de validación del certificado está habilitado (establecido como verdadero).  Puede establecer el indicador de validación del certificado de backend de almacenamiento ONTAP en falso si necesita omitir las verificaciones del certificado SAN.  Esta configuración no se aplica a los certificados de vCenter Server.

.Antes de empezar
Debe tener credenciales de inicio de sesión de usuario de mantenimiento.

.Pasos
. Desde vCenter Server, abra una consola a las herramientas de ONTAP.
. Inicie sesión como el usuario de mantenimiento.
. Ingresar `1` para seleccionar el menú *Configuración de la aplicación*.
. Ingresar `3` para cambiar el indicador de validación del certificado.
+
La consola de mantenimiento muestra el estado del indicador de validación del certificado y le solicita que lo cambie.

. Introduzca 'y' para alternar la bandera o 'n' para cancelar.


Cuando se habilita la opción de validación de certificados (establecida en verdadero), ONTAP tools verifica que todos los backends de almacenamiento utilicen certificados con un Nombre Alternativo del Sujeto (SAN).  Si algún backend utiliza un certificado sin SAN, no se puede habilitar la validación del certificado.  Antes de habilitar esta opción, verifique que todos los sistemas de almacenamiento utilicen certificados basados ​​en SAN.  Si deshabilita la bandera de validación de certificados (estableciéndola en falso), ONTAP tools omite la validación de certificados para todos los backends de almacenamiento configurados.
