---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords: remote diagnostic access, ONTAP tools SSH diag user, enable SSH diagnostics, appliance troubleshooting access 
summary: Activa el acceso SSH para el usuario diag en ONTAP tools for VMware vSphere. 
---
= Configura el acceso remoto de diagnóstico para las herramientas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes habilitar el acceso SSH para el usuario diag en ONTAP tools for VMware vSphere.

.Antes de empezar
Habilite la extensión VASA Provider para su instancia de vCenter Server.

.Acerca de esta tarea
El uso de SSH para acceder a la cuenta de usuario diag tiene las siguientes limitaciones:

* Solo puedes usar una cuenta de inicio de sesión cada vez que habilites SSH.
* El acceso SSH a la cuenta de usuario «diag» está desactivado en cualquiera de estos casos:
+
** La hora caduca.
+
La sesión iniciada caduca a medianoche del día siguiente.

** Inicie sesión como usuario diag de nuevo con SSH.




.Pasos
. Inicia sesión en el servidor vCenter.
. Busca la máquina virtual de ONTAP tools e inicia la consola web.
. Inicia sesión usando las credenciales de `maint`.
. Ingrese `4` para seleccionar *Soporte y Diagnóstico*.
. Ingresar `2` para seleccionar *Habilitar acceso a diagnóstico remoto*.
. Escribe  `y` en el cuadro de diálogo de confirmación para habilitar el acceso al diagnóstico remoto.
. Introduzca una contraseña para el acceso de diagnóstico remoto.

