---
permalink: manage/delete-deployment.html 
sidebar: sidebar 
keywords: remove FlexVol after uninstall, ONTAP tools cleanup, delete unused FlexVol volumes, post-uninstall storage cleanup 
summary: Elimina los volúmenes FlexVol que no se utilicen después de quitar la implementación de ONTAP tools para evitar impactos en el rendimiento. 
---
= Elimina los volúmenes FlexVol después de desinstalar ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando implementas ONTAP tools for VMware vSphere en un clúster ONTAP dedicado, la implementación crea muchos volúmenes FlexVol sin usar. Después de quitar ONTAP tools, elimina los volúmenes FlexVol sin usar para evitar posibles impactos en el rendimiento.

.Pasos
. Determina el tipo de implementación de ONTAP tools for VMware vSphere desde la máquina virtual del nodo de gestión de ONTAP tools. Ejecuta el siguiente comando para comprobar el tipo de implementación: _cat /opt/netapp/meta/ansible_vars.yaml | grep -i protocol_
+
Si la implementación utiliza iSCSI, elimina también los igroups.

. Obtenga la lista de volúmenes FlexVol . _kubectl describe volúmenes persistentes | grep nombreInterno | awk -F'=' '{print $2}'_
. Quite las máquinas virtuales de vCenter Server. Consulte https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Elimine y vuelva a registrar máquinas virtuales y plantillas de máquinas virtuales"].
. Eliminar volúmenes FlexVol . Referirse a https://docs.netapp.com/us-en/ontap/volumes/delete-flexvol-task.html["Eliminar un volumen de FlexVol"] . Ingrese el nombre exacto del FlexVol volume en el comando CLI para eliminar un volumen.
. Para las implementaciones iSCSI, elimina los igroups SAN del backend de almacenamiento ONTAP. Consulta https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Consulte y gestione iniciadores E iGroups SAN"].

