---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: La acción Eliminar el almacén de datos elimina el almacén de datos. En el caso de un almacén de datos NFS o VMFS, se muestra un cuadro de diálogo con la lista de máquinas virtuales que utilizan el almacén de datos. 
---
= Eliminar almacenes de datos en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta página describe cómo eliminar almacenes de datos NFS, VMFS o vVols utilizando las herramientas ONTAP en vCenter Server.

Al eliminar un almacén de datos, se realizan las siguientes acciones según el tipo de almacén de datos:

* El contenedor vVol no está montado.
* Si el igroup no está en uso, iqn se elimina del igroup.
* Se elimina el contenedor vVol.
* Los volúmenes flexibles se dejan en la matriz de almacenamiento.


Puede eliminar el almacén de datos solo si no hay vVols presentes en el almacén de datos seleccionado.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic con el botón derecho en un sistema host, un clúster de host o un centro de datos y seleccione *Herramientas de NetApp ONTAP * > *Eliminar almacén de datos*.
+

NOTE: No se puede eliminar un almacén de datos utilizado por máquinas virtuales.  Mueva las máquinas virtuales a otro almacén de datos antes de eliminarlas.  No puedes eliminar el volumen si es parte de un clúster de host protegido.

+
.. En el caso de un almacén de datos NFS o VMFS, aparece un cuadro de diálogo con la lista de máquinas virtuales que utilizan el almacén de datos.
.. Si no hay máquinas virtuales asociadas a un almacén de datos VMFS, verá un cuadro de diálogo de confirmación.  Si la protección del clúster de host está habilitada y existe una relación AFD, puede limpiar elementos de almacenamiento secundario.
.. Para los almacenes de datos VMFS protegidos en sistemas ASA r2, elimine la protección antes de borrar. A partir de ONTAP 9.17.1 y las ONTAP tools for VMware vSphere 10.5, puede eliminar un almacén de datos protegido.  Si es el único almacén de datos en el grupo de protección, la protección del clúster de hosts se elimina automáticamente.
.. Para los almacenes de datos vVols , puede eliminar el almacén de datos solo si no hay vVols presentes.  El cuadro de diálogo *Eliminar almacén de datos* incluye una opción para eliminar volúmenes del clúster ONTAP .
.. Para los almacenes de datos vVols en sistemas ASA r2, no es posible eliminar los volúmenes de respaldo de ONTAP mediante la opción *Eliminar almacén de datos*.


. Para eliminar los volúmenes de respaldo en el almacenamiento de ONTAP, seleccione *Eliminar volúmenes en el clúster de ONTAP*.
+

NOTE: En el caso de los almacenes de datos VMFS en el almacenamiento ONTAP unificado que forman parte de un clúster de host protegido, no se puede eliminar el volumen del clúster ONTAP .



Cuando elimina un almacén de datos NFS, VMFS o vVols , los igroups principales permanecen en el sistema ONTAP . Los igroups secundarios que no están asignados a ningún LUN se eliminan automáticamente. Las herramientas de ONTAP realizan una limpieza diaria para eliminar los igroups primarios predeterminados no asignados. Elimine manualmente los igroups principales personalizados en ONTAP.  Las herramientas ONTAP no pueden reutilizar igroups principales obsoletos.
