---
permalink: manage/disable-autosupport.html 
sidebar: sidebar 
keywords:  
summary: Cuando se configura por primera vez el sistema de almacenamiento, se habilita AutoSupport de manera predeterminada. Envía mensajes al soporte técnico 24 horas después de que está habilitado. 
---
= Deshabilite AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se configura por primera vez el sistema de almacenamiento, se habilita AutoSupport de manera predeterminada. Envía mensajes al soporte técnico 24 horas después de que está habilitado. Al deshabilitar AutoSupport, ya no recibirá soporte y supervisión proactivos.


NOTE: Se recomienda mantener la función AutoSupport habilitada. Ayuda a acelerar la detección y resolución de problemas. El sistema recopila información de AutoSupport y la almacena localmente, incluso cuando está desactivada. Sin embargo, no envía el informe a ninguna red.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione la opción *Ajustes* > *Telemetría* > *Editar*.
. Deseleccione la opción *AutoSupport* y guarde los cambios.

