---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Es posible editar las relaciones de SnapMirror del clúster de hosts protegido. Puede agregar, modificar y suprimir las relaciones. Sin embargo, no puede editar el nombre del grupo de consistencia. 
---
= Modifica un clúster de hosts protegidos en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la configuración de protección de un clúster de host en un solo flujo de trabajo.  Se admiten los siguientes cambios:

* Añada nuevos almacenes de datos o hosts al clúster protegido.
* Añada nuevas relaciones de SnapMirror a la configuración de protección.
* Elimine las relaciones de SnapMirror existentes de la configuración de protección.
* Modifique una relación de SnapMirror existente.



NOTE: Debe realizar la detección de almacenamiento después de crear, editar o eliminar la protección de un clúster de host para reflejar los cambios.  Si no realiza la detección de almacenamiento, los cambios se reflejan después de que se activa la detección de almacenamiento periódica.



== Supervise la protección del clúster de hosts

Supervise el estado de protección, las relaciones de SnapMirror , los almacenes de datos y el estado de SnapMirror para cada clúster de host protegido.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Vaya a *Herramientas de NetApp ONTAP * > *Protección* > *Relaciones del clúster de host*.
+
La columna de protección muestra un icono que indica el estado de protección.

. Pase el ratón sobre el icono para ver más detalles.




== Añada hosts o almacenes de datos nuevos

Agregue hosts o cree almacenes de datos en el clúster protegido mediante la interfaz de usuario de vCenter.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Para editar las propiedades de un clúster protegido, puede hacer lo siguiente
+
.. Vaya a *Herramientas de NetApp ONTAP * > *Protección* > *Relaciones del clúster de host*, seleccione el menú de puntos suspensivos junto al clúster y seleccione *Editar* o
.. Haga clic con el botón derecho en un clúster de host y seleccione * Herramientas de NetApp ONTAP * > * Proteger clúster *.


. Si crea un almacén de datos en la interfaz de usuario de vCenter, aparecerá como desprotegido.  Puede ver todos los almacenes de datos del clúster y su estado de protección en un cuadro de diálogo.  Seleccione el botón *Proteger* para habilitar la protección.
+

NOTE: Después de crear un almacén de datos en la interfaz de usuario de vCenter Server, seleccione *Descubrir* en la página de descripción general para mostrar el almacén de datos como candidato para protección en el clúster de host.  El estado de protección se actualiza a protegido después del próximo descubrimiento de protección periódico.

. Si agrega un nuevo host ESXi, el estado de protección se muestra como parcialmente protegido.  Seleccione el menú de puntos suspensivos en la configuración de SnapMirror y seleccione *Editar* para establecer la proximidad del host ESXi recién agregado.
+

NOTE: En el caso de las relaciones asincrónicas, no se admite la edición en las herramientas ONTAP porque el SVM de destino de un sitio terciario no se puede agregar a la misma instancia.  Para modificar la configuración de la relación, utilice el Administrador del sistema o la CLI en la SVM de destino.

. Después de realizar los cambios, seleccione *Guardar*.
. Puedes ver los cambios en la ventana *Protect Cluster*.


Las herramientas de ONTAP crean una tarea de vCenter y usted puede seguir su progreso en el panel *Tarea reciente*.



== Añada una nueva relación de SnapMirror

.Pasos
. Inicie sesión en el cliente de vSphere.
. Para editar las propiedades de un clúster protegido, puede hacer lo siguiente
+
.. Vaya a * Herramientas de NetApp ONTAP * > * Protección * > * Relaciones de clúster de host *, seleccione el menú de puntos suspensivos frente al clúster y seleccione * Editar * o
.. Haga clic con el botón derecho en un clúster de host y seleccione * Herramientas de NetApp ONTAP * > * Proteger clúster *.


. Seleccione *Añadir relación*.
. Agregue una nueva relación como tipo de política *Asynchronous* o *AutomatedFailOverDuplex*.
. Seleccione *Proteger*.
+
Puedes ver los cambios en la ventana *Protect Cluster*.



Las herramientas de ONTAP crean una tarea de vCenter y usted puede seguir su progreso en el panel *Tarea reciente*.



== Eliminar una relación de SnapMirror existente

Para eliminar una relación asincrónica de SnapMirror , asegúrese de que el SVM o clúster del sitio secundario se agregue como back-end de almacenamiento en las ONTAP tools for VMware vSphere.  No es posible eliminar todas las relaciones de SnapMirror a la vez.  Al eliminar una relación también se elimina la relación correspondiente del clúster ONTAP .  Cuando se elimina una relación SnapMirror de dúplex de conmutación por error automatizada, el sistema desasigna los almacenes de datos de destino y elimina el grupo de consistencia, los LUN, los volúmenes y los igroups del clúster ONTAP de destino.

Cuando se elimina la relación, el sistema vuelve a escanear el sitio secundario para eliminar el LUN no asignado como ruta activa de los hosts.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Para editar las propiedades de un clúster protegido, puede hacer lo siguiente
+
.. Vaya a * Herramientas de NetApp ONTAP * > * Protección * > * Relaciones de clúster de host *, seleccione el menú de puntos suspensivos frente al clúster y seleccione * Editar * o
.. Haga clic con el botón derecho en un clúster de host y seleccione * Herramientas de NetApp ONTAP * > * Proteger clúster *.


. Seleccione el menú de puntos suspensivos en la configuración de SnapMirror y seleccione *Eliminar*.
+
** Si elimina una relación basada en tipo de política asincrónica de un clúster de host protegido, debe quitar manualmente los elementos de almacenamiento del clúster de almacenamiento terciario.  Los elementos de almacenamiento incluyen grupos de consistencia, volúmenes (para sistemas ONTAP ), unidades de almacenamiento (LUN/espacios de nombres) e instantáneas.
** Si elimina una relación basada en políticas de dúplex de conmutación por error automatizada (AFD) de un clúster de host protegido, puede optar por eliminar los elementos de almacenamiento asociados en el almacenamiento secundario directamente desde la interfaz.
** Si elimina una relación basada en políticas de dúplex de conmutación por error automatizada (AFD) y el grupo de consistencia ahora es jerárquico para las copias de seguridad a nivel de aplicación, aparece una advertencia sobre el impacto en la copia de seguridad.  Confirme para continuar.  Después de la confirmación, elimine los elementos de almacenamiento asociados en el almacenamiento secundario.  Si no los elimina, permanecerán en el sitio secundario.




Las herramientas de ONTAP crean una tarea de vCenter y usted puede seguir su progreso en el panel *Tarea reciente*.



== Modifique una relación de SnapMirror existente

Para modificar una relación asincrónica de SnapMirror , asegúrese de que el SVM o clúster del sitio secundario se agregue como back-end de almacenamiento en las ONTAP tools for VMware vSphere.  Para las relaciones SnapMirror dúplex de conmutación por error automatizada, puede actualizar la proximidad del host para configuraciones uniformes o el acceso del host para configuraciones no uniformes.  No se admite el cambio entre los tipos de políticas de dúplex de conmutación por error automatizada y asincrónica.  Puede configurar ajustes de proximidad o acceso para los hosts recién descubiertos en el clúster.


NOTE: No es posible editar una relación asincrónica de SnapMirror existente.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Para editar las propiedades de un clúster protegido, puede hacer lo siguiente
+
.. Vaya a * Herramientas de NetApp ONTAP * > * Protección * > * Relaciones de clúster de host *, seleccione el menú de puntos suspensivos frente al clúster y seleccione * Editar * o
.. Haga clic con el botón derecho en un clúster de host y seleccione * Herramientas de NetApp ONTAP * > * Proteger clúster *.


. Si se selecciona el tipo de política AutomatedFailOverDuplex, agregue detalles de proximidad del host o acceso del host.
. Seleccione el botón *Proteger*.


Las herramientas ONTAP crean una tarea de vCenter.  Siga su progreso en el panel *Tarea reciente*.
