---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: Puede cambiar la contraseña del administrador mediante el Administrador de herramientas de ONTAP. 
---
= Cambiar la configuración del dispositivo ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice el Administrador de herramientas de ONTAP para ampliar la configuración de las ONTAP tools for VMware vSphere , ya sea aumentando la cantidad de nodos o habilitando la alta disponibilidad (HA).  De forma predeterminada, las ONTAP tools for VMware vSphere se implementan como una configuración de nodo único y sin alta disponibilidad.

.Antes de empezar
* Asegúrese de que la plantilla OVA tiene la misma versión de OVA que el nodo 1. El nodo 1 es el nodo predeterminado donde se pone en marcha inicialmente las herramientas de ONTAP para VMware vSphere OVA.
* Asegúrese de que la conexión en caliente de la CPU y la conexión en caliente de la memoria están activadas.
* En vCenter Server, configure el nivel de automatización del Servicio de Recuperación ante Desastres (DRS) como parcialmente automatizado. Tras implementar la alta disponibilidad, revíselo a completamente automatizado.
* Los nombres de host de los nodos en la configuración de HA deben estar en minúsculas.


.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione la opción *Editar configuración del aparato* en la sección de descripción general.
. En la sección *Configuración*, aumente el tamaño del nodo y habilite la configuración de alta disponibilidad (HA).  Utilice las credenciales de vCenter Server para realizar cambios.
+
En la configuración de HA, puede cambiar los detalles de la biblioteca de contenido.  Proporcione la contraseña para cada edición.

+

NOTE: En las ONTAP tools for VMware vSphere, solo se permite aumentar el tamaño del nodo; no se puede reducir el tamaño del nodo.  En una configuración que no es HA, solo se admite una configuración de tamaño mediano.  En una configuración de alta disponibilidad, se admiten configuraciones medianas y grandes.

. Utilice el botón de alternar HA para habilitar la configuración de alta disponibilidad. En la página *HA settings*, asegúrese de que:
+
** La biblioteca de contenido pertenece a la misma instancia de vCenter Server donde se ejecutan los equipos virtuales del nodo de herramientas de ONTAP. Las credenciales de vCenter Server se utilizan para validar y descargar la plantilla OVA para realizar cambios en el dispositivo.
** La máquina virtual que aloja las herramientas de ONTAP no se implementa directamente en un host ESXi. La máquina virtual debe ponerse en marcha en un clúster o un pool de recursos.
+

NOTE: Una vez habilitada la configuración de HA, no es posible volver a una configuración de nodo único que no sea de HA.



. En la sección *Configuración HA* de la ventana *Editar configuración de dispositivo*, puede introducir los detalles de los nodos 2 y 3. Las herramientas de ONTAP para VMware vSphere admiten tres nodos en una configuración de alta disponibilidad.
+

NOTE: Las herramientas ONTAP rellenan previamente la mayoría de las opciones de entrada con los detalles de la red del Nodo 1 para simplificar el flujo de trabajo.  Puedes editar los datos de entrada antes de ir a la última página del asistente. Puede ingresar detalles de la dirección IPv6 para los otros dos nodos solo cuando la dirección IPv6 esté habilitada en el nodo de administración de herramientas ONTAP .

+
Compruebe que un host ESXi contenga solo una máquina virtual de ONTAP Tools. Las entradas se validan cada vez que se mueve a la siguiente ventana.

. Revise los detalles en la sección *Resumen* y *Guardar* los cambios.


.El futuro
La página *Descripción general* muestra el estado de la implementación. También puede realizar un seguimiento del estado del trabajo de edición de la configuración del dispositivo desde la vista de trabajos utilizando el ID del trabajo.

Si falla la implementación de HA y el estado del nuevo nodo es 'Nuevo', elimine la nueva máquina virtual en vCenter antes de intentar habilitar HA nuevamente.

La pestaña *Alertas* en el panel izquierdo muestra las alertas de las herramientas de ONTAP para VMware vSphere.
