---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords: modify ESXi host settings, ONTAP tools host configuration, VMware host tuning, ESXi settings dashboard 
summary: Edita la configuración del host ESXi desde el panel de control de ONTAP tools. 
---
= Modifique la configuración del host ESXi mediante las herramientas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utiliza el panel de herramientas de ONTAP en VMware vSphere para identificar problemas de configuración, consultar los ajustes recomendados de NetApp para los hosts ESXi seleccionados y aplicarlos.

.Antes de empezar
El portlet de sistemas host ESXi muestra problemas con la configuración del host ESXi.  Seleccione un problema para ver el nombre del host o la dirección IP.

.Pasos
. Inicia sesión en el vSphere Client.
. En la página de accesos directos, selecciona *NetApp ONTAP tools* en la sección de complementos.
. Ve al portlet *Cumplimiento del host ESXi* en el panel de control de Resumen del complemento ONTAP tools for VMware vSphere.
. Selecciona el enlace *Aplicar la configuración recomendada*.
. En la ventana *Aplicar la configuración recomendada para los hosts*, selecciona los hosts a los que deseas aplicar la configuración recomendada por NetApp y luego selecciona *Siguiente*.
+

NOTE: Puede expandir el host ESXi para ver los valores actuales.

. En la página Configuración, selecciona los valores recomendados según sea necesario.
. En el panel de resumen, comprueba los valores y selecciona *Finalizar*. Puedes seguir el progreso en el panel de tareas recientes.


.Información relacionada
link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Configure los ajustes del host ESXi"]
