---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords:  
summary: 'Puede cambiar la contraseña de administrador usando el Administrador de herramientas de ONTAP para habilitar servicios como VASA Provider, importación de la configuración de vVols y recuperación ante desastres (SRA) con el Administrador de herramientas de ONTAP.' 
---
= Habilite herramientas de ONTAP para los servicios de VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede cambiar la contraseña de administrador usando el Administrador de herramientas de ONTAP para habilitar servicios como VASA Provider, importación de la configuración de vVols y recuperación ante desastres (SRA) con el Administrador de herramientas de ONTAP.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione la opción *Editar configuración del aparato* en la sección de descripción general.
. En la sección *Servicios*, puede habilitar servicios opcionales como VASA Provider, importación de configuración de vVols y recuperación ante desastres (SRA) según sea necesario.
+
Cuando se habilitan los servicios por primera vez, debe crear las credenciales del proveedor VASA y del SRA. Estos se usan para registrar o habilitar el proveedor VASA y los servicios de SRA en vCenter Server. El nombre de usuario sólo puede contener letras, números y guiones bajos. La longitud de la contraseña debe tener entre 8 y 256 caracteres.

+

NOTE: Antes de deshabilitar cualquier servicio opcional, asegúrese de que los servidores vCenter administrados por las herramientas de ONTAP no los utilicen.

+
La opción *Permitir importación de configuración de vVols * se muestra solo cuando el servicio del proveedor VASA está habilitado.  Esta opción habilita la migración de datos vVols desde las herramientas ONTAP 9.xx a las herramientas ONTAP 10.5.


