---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords: enable ONTAP tools services, enable VASA provider, enable SRA service, vVols service configuration 
summary: 'Habilita los servicios opcionales de ONTAP tools, incluyendo VASA Provider, la importación de configuración de vVols y la recuperación ante desastres (SRA).' 
---
= Habilitar los servicios de ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usa ONTAP tools Manager para habilitar servicios opcionales como VASA Provider, importación de configuración de vVols y recuperación ante desastres (SRA).

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. En la sección *Resumen*, selecciona *Editar configuración del dispositivo*.
. En la sección *Servicios*, activa los servicios opcionales que necesites, como VASA Provider, importación de configuración de vVols y recuperación ante desastres (SRA).
+
Cuando actives estos servicios por primera vez, crea las credenciales de VASA Provider y SRA.

+
** Utiliza estas credenciales para registrar y habilitar los servicios VASA Provider y SRA en vCenter Server.
** El nombre de usuario solo puede contener letras, números y guiones bajos.
** La longitud de la contraseña debe estar comprendida entre 8 y 256 caracteres.





NOTE: Antes de desactivar cualquier servicio opcional, asegúrate de que las instancias de vCenter Server gestionadas por ONTAP tools no utilicen ese servicio.

+ La opción *Permitir la importación de la configuración de vVols* solo aparece cuando el servicio VASA Provider está habilitado. Esta opción permite la migración de datos de vVols desde ONTAP tools 9.x a ONTAP tools 10.6.
