---
permalink: manage/expand-storage-of-vvol-datastore.html 
sidebar: sidebar 
keywords: expand vVols datastore, increase vVol datastore capacity, ONTAP tools vVol storage expansion, VMware virtual volumes scaling 
summary: Amplía el almacenamiento del almacén de datos vVols desde la vista del objeto vCenter usando las acciones de ONTAP tools. 
---
= Amplía un datastore de vVols en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al hacer clic con el botón derecho del ratón sobre el objeto datastore en la vista de objetos de vCenter, la sección del complemento muestra las acciones compatibles para ONTAP tools for VMware vSphere. Las acciones disponibles dependen del tipo de datastore y de los Privileges actuales del usuario.


NOTE: Este procedimiento no se aplica a los almacenes de datos vVols basados en el sistema ASA r2.

.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. En el panel de navegación, seleccione el centro de datos que contiene el almacén de datos.
. Haga clic con el botón derecho en el almacén de datos y seleccione *Herramientas de NetApp ONTAP* > *Añadir almacenamiento al almacén de datos*.
. En la ventana *Crear o Seleccionar volúmenes*, puede crear nuevos volúmenes o elegir entre los volúmenes existentes. Siga las instrucciones en pantalla para realizar su selección.
. En la ventana *Resumen*, revise las selecciones y seleccione *Expandir*. Puede realizar un seguimiento del progreso en el panel de tareas recientes.

