---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management 
summary: Gestiona las instancias de vCenter en ONTAP tools para controlar los hosts, las máquinas virtuales y los backends de almacenamiento. 
---
= Administrar instancias de vCenter Server en las herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las instancias de vCenter Server son plataformas de gestión central que permiten controlar hosts, máquinas virtuales y back-ends de almacenamiento.



[[dissociate-storage-backends-from-a-vcenter-server-instance]]
== Desvincular los backends de almacenamiento de una instancia de vCenter Server

La página enumerada de vCenter Server muestra el número asociado de back-ends de almacenamiento. Cada instancia de vCenter Server tiene la opción de asociar o desasociar con un back-end de almacenamiento.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Selecciona *vCenters* en la barra lateral.
. Selecciona los tres puntos verticales para el servidor vCenter que quieres asociar o desasociar con los backends de almacenamiento.
. Seleccione *Dissociar backend de almacenamiento*.




[[modify-a-vcenter-server-instance]]
== Modifique una instancia de vCenter Server

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Selecciona *vCenters* en la barra lateral.
. Selecciona los tres puntos verticales para el servidor vCenter que quieres modificar y selecciona *Modificar*.
. En la ventana *Modificar vCenter*, ingrese el nombre de usuario, la contraseña y los detalles del puerto.
. Sube el certificado y selecciona *Modificar*.




[[remove-a-vcenter-server-instance]]
== Quite una instancia de vCenter Server

Puedes eliminar una instancia de vCenter Server incluso cuando los almacenes de datos y los backends de almacenamiento siguen asociados. El cuadro de diálogo *Eliminar vCenter* te guía a través de las acciones necesarias según el estado actual del vCenter Server.


NOTE: La eliminación forzada solo elimina los metadatos de ONTAP tools. No elimina los objetos de almacenamiento de ONTAP (volúmenes o LUNs), vSphere datastores ni máquinas virtuales.

.Antes de empezar
La eliminación forzada se bloquea si el servidor vCenter tiene almacenes de datos vVols o almacenes de datos protegidos. Antes de continuar:

* Elimina o migra todos los almacenes de datos vVols.
* Desprotege todos los almacenes de datos protegidos.
* Asegúrate de que no haya ninguna tarea de detección en ejecución. La operación de eliminación forzada no se llevará a cabo si hay tareas de detección en curso.



NOTE: Se conservan los backends de almacenamiento globales compartidos con otras instancias de vCenter Server. Solo se elimina la asociación con el vCenter Server eliminado.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Selecciona *vCenters* en la barra lateral.
. Selecciona los tres puntos verticales para el vCenter Server requerido y selecciona *Eliminar*.
. En el cuadro de diálogo *Eliminar vCenter*, revisa el estado del servidor vCenter y completa cualquier acción requerida.
+
El comportamiento del cuadro de diálogo depende del estado del servidor vCenter:

+
[cols="2,2,3"]
|===
| Estado | Comportamiento de los cuadros de diálogo | Acción necesaria 


| No vVols ni almacenes de datos protegidos, pero los backends de almacenamiento están asociados | El cuadro de diálogo muestra el número de backends de almacenamiento y almacenes de datos asociados. | Selecciona *Eliminar todos los artefactos de almacenamiento de este vCenter Server* y *Entiendo que los almacenes de datos asociados dejarán de ser gestionados por ONTAP tools*. 


| No hay almacenes de datos vVols, almacenes de datos protegidos ni backends de almacenamiento | El cuadro de diálogo confirma la eliminación. | No es necesario realizar ninguna acción adicional. 
|===
. Selecciona *Eliminar de forma forzada*.
. Confirma la acción.


.Resultado
ONTAP tools realiza las siguientes acciones automáticamente:

* El plugin se ha cancelado del registro.
* Se quitaron los privilegios de plugins y los roles de plugins.


La instancia de vCenter Server ya no está gestionada por ONTAP tools.

Si el servidor vCenter no está disponible durante la eliminación:

* Las herramientas de ONTAP eliminan el registro del servidor vCenter.
* No se produce la cancelación del registro del plugin.
* Aparece un aviso.
* Debes dar de baja manualmente el complemento de VMware vCenter Server.




[[renew-vcenter-server-certificate]]
== Renovar el certificado de vCenter Server

Las herramientas de ONTAP le notifican cuando el certificado de vCenter está próximo a vencer o ha vencido. Después de renovar el certificado de vCenter, cargue el nuevo certificado en las herramientas de ONTAP siguiendo los siguientes pasos:

. Inicie sesión en el shell de diagnóstico remoto de las herramientas ONTAP .
. Obtenga el certificado de vCenter renovado desde el shell de diagnóstico:
+
[listing]
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p'
----
. Asegúrese de que el certificado esté en formato ASCII Base 64 e incluya las líneas inicial y final, por ejemplo:
+
[listing]
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. Copie la salida y guárdela como un archivo de texto con un `.pem` extensión en su escritorio.
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione la instancia de vCenter Server aplicable en la barra lateral
. Selecciona los tres puntos verticales para el servidor vCenter que quieres modificar y selecciona *Modificar*.
. En la ventana *Modificar vCenter*, ingrese el nombre de usuario, la contraseña y los detalles del puerto.
. Sube el certificado y selecciona *Modificar*.


.Información relacionada
link:../manage/configure-remote-diagnostic-access.html["Configurar el acceso de diagnóstico remoto"]
