---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html 
sidebar: sidebar 
keywords: migrate VMs to vVols, NFS VMFS to vVol migration, virtual machine storage migration, policy-based VM storage 
summary: Migra máquinas virtuales desde almacenes de datos NFS y VMFS a almacenes de datos vVols para una gestión basada en políticas. 
---
= Migra máquinas virtuales a almacenes de datos vVols en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede migrar máquinas virtuales de almacenes de datos de NFS y VMFS a almacenes de datos de Virtual Volumes (vVols) para aprovechar la gestión de máquinas virtuales basada en políticas y otras funcionalidades de vVols. Los almacenes de datos vVols le permiten satisfacer requisitos de cargas de trabajo crecientes.

.Antes de empezar
Comprueba que VASA Provider no se esté ejecutando en ninguna de las máquinas virtuales que tengas previsto migrar. Si migras una máquina virtual en la que se está ejecutando VASA Provider a un almacén de datos de vVols, no podrás realizar ninguna operación de gestión, incluido el encendido de las máquinas virtuales que se encuentren en los almacenes de datos de vVols.

.Acerca de esta tarea
Cuando se migra de un almacén de datos NFS y VMFS a un almacén de datos vVols, la instancia de vCenter Server utiliza las API de vStorage para la integración de cabinas (VAAI) descarga las cargas al mover datos de almacenes de datos VMFS, pero no de un archivo VMDK NFS. Las descargas de VAAI suelen reducir la carga en el host.

.Pasos
. Haga clic con el botón derecho en la máquina virtual que desea migrar y seleccione *Migrate*.
. Seleccione *Cambiar solo almacenamiento* y luego seleccione *Siguiente*.
. Seleccione un formato de disco virtual, una política de almacenamiento de VM y un almacén de datos vVol que coincida con las características del almacén de datos que está migrando.
. Revise los ajustes y seleccione *Finalizar*.

