---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Debe tener en cuenta algunos de los aspectos que se deben tener en cuenta al migrar las máquinas virtuales existentes en el centro de datos. 
---
= Consideraciones para migrar o clonar máquinas virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta algunos de los aspectos que se deben tener en cuenta al migrar las máquinas virtuales existentes en el centro de datos.



== Migrar máquinas virtuales protegidas

Puede migrar las máquinas virtuales protegidas a:

* El mismo almacén de datos vVols en un host ESXi diferente
* Distinto almacén de datos vVols compatible en el mismo host ESXi
* Distinto almacén de datos vVols compatible en un host ESXi diferente


Si migra la máquina virtual a un FlexVol volume diferente, el sistema actualiza el archivo de metadatos de ese volumen con la información de la máquina virtual. Si se migra una máquina virtual a un host ESXi diferente pero al mismo almacenamiento, el archivo de metadatos del FlexVol volume subyacente no se modificará.



== Clonar máquinas virtuales protegidas

Es posible clonar máquinas virtuales protegidas con las siguientes características:

* El mismo contenedor de un mismo volumen FlexVol que utiliza el grupo de replicación
+
El archivo de metadatos del mismo volumen de FlexVol se actualiza con los detalles de la máquina virtual clonada.

* El mismo contenedor de un volumen FlexVol diferente mediante el grupo de replicación
+
Volumen FlexVol donde se coloca la máquina virtual clonada, el archivo de metadatos se actualiza con los detalles de la máquina virtual clonada.

* Diferentes contenedores o almacenes de datos vVols
+
Volumen FlexVol donde se coloca la máquina virtual clonada, el archivo de metadatos se actualiza los detalles de la máquina virtual.



Actualmente, VMware no admite máquinas virtuales clonadas en una plantilla de VM.

Se admite el clonado de clon de una máquina virtual protegida.

Consulte https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Crear una máquina virtual para clonación"] si desea obtener más información.



== Snapshots de máquina virtual

Actualmente solo se admiten instantáneas de máquina virtual sin memoria. Si la máquina virtual tiene una snapshot con memoria, no se considera que la máquina virtual tenga protección.

Tampoco puedes proteger máquinas virtuales desprotegidas que tengan instantáneas de memoria.  Para esta versión, se espera que elimine la instantánea de memoria antes de habilitar la protección para la máquina virtual.

Para una máquina virtual Windows con almacenamiento ASA r2, una instantánea de la máquina virtual es de solo lectura.  Al encender la máquina virtual, el proveedor VASA crea una LUN a partir de la instantánea de solo lectura y habilita las IOPS.  Cuando se apaga la máquina virtual, el proveedor VASA elimina el LUN y deshabilita las IOPS.
