---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords: virtual machine migration considerations, ONTAP tools VM cloning guidance, VMware storage vMotion considerations, VM migration best practices 
summary: Revisa los aspectos clave que debes tener en cuenta antes de migrar las máquinas virtuales existentes en tu centro de datos. 
---
= Infórmate sobre la migración y la clonación de máquinas virtuales en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere admite todos los principales tipos de migración de máquinas virtuales, incluidas las de solo computación (vMotion), las de solo almacenamiento (Storage vMotion) y las migraciones combinadas de computación y almacenamiento en todos los almacenes de datos. Comprender estas consideraciones y mejores prácticas sobre migración y clonación te ayuda a obtener resultados satisfactorios, independientemente del tipo de almacén de datos subyacente.



[[migrate-protected-virtual-machines]]
== Migrar máquinas virtuales protegidas

Puedes migrar máquinas virtuales protegidas a:

* El mismo almacén de datos en un host ESXi diferente
* Un datastore compatible diferente en el mismo host ESXi
* Un datastore compatible diferente en un host ESXi diferente


Si migras la máquina virtual a otro volumen de FlexVol, el sistema actualiza el archivo de metadatos de ese volumen con la información de la máquina virtual. Si una máquina virtual se migra a otro host ESXi pero al mismo almacenamiento, el archivo de metadatos del volumen subyacente de FlexVol no se modifica.

Para obtener información sobre la migración de máquinas virtuales, consulta https://techdocs.broadcom.com/["Documentación técnica de Broadcom"]



[[clone-protected-virtual-machines]]
== Clonar máquinas virtuales protegidas

Es posible clonar máquinas virtuales protegidas con las siguientes características:

* El mismo contenedor del mismo volumen FlexVol utilizando un grupo de replicación
+
ONTAP tools actualiza el archivo de metadatos del mismo volumen FlexVol con los detalles de la máquina virtual clonada.

* El mismo contenedor de un volumen FlexVol diferente utilizando un grupo de replicación
+
En el volumen FlexVol donde se encuentra la máquina virtual clonada, ONTAP tools actualiza el archivo de metadatos con los detalles de la máquina virtual clonada.

* Un contenedor diferente o almacén de datos vVols
+
En el volumen FlexVol donde se aloja la máquina virtual clonada, ONTAP tools actualiza el archivo de metadatos con los detalles de la máquina virtual.



Actualmente, VMware no admite máquinas virtuales clonadas a partir de una plantilla de máquina virtual.

Se admite un clon de un clon de una máquina virtual protegida.

Consulta la documentación de Broadcom: https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Crear una máquina virtual para clonación"] para más detalles.



[[virtual-machine-snapshots]]
== Instantáneas de máquinas virtuales

Las herramientas ONTAP admiten instantáneas de máquinas virtuales a través de flujos de trabajo estándar de VMware. Las instantáneas son puntos de reversión a corto plazo pensados para casos de uso como pruebas y preparación de parches. No sustituyen la protección de datos basada en copias de seguridad o replicación. Ejecutar una máquina virtual en una instantánea durante periodos prolongados puede provocar inestabilidad y pérdida de datos.

Puedes tomar snapshots consistentes con fallos (snapshots sin estado de memoria, que pueden usarse para reiniciar la máquina virtual a un estado consistente) en todos los tipos de datastore compatibles. También se admiten snapshots en reposo, que usan VMware Tools para volcar los datos en memoria al disco antes de capturar. Para una visión general de los tipos de snapshots y su comportamiento, consulta https://techdocs.broadcom.com/["Documentación técnica de Broadcom"].


NOTE: Las instantáneas de memoria capturan el estado de la memoria en ejecución y aturden temporalmente la máquina virtual. No están soportadas en los flujos de trabajo de ONTAP tools. Si una máquina virtual tiene una instantánea de memoria, debes eliminarla antes de que la máquina virtual pueda incluirse en un grupo de consistencia o en una relación de clúster de host gestionada por ONTAP tools.

En los sistemas de almacenamiento ASA r2, el comportamiento de las instantáneas de máquinas virtuales difiere de otros tipos de almacenamiento. Las instantáneas son de solo lectura. Cuando enciendes la máquina virtual, VASA Provider crea un LUN a partir de la instantánea de solo lectura y habilita las IOPS. Cuando apagas la máquina virtual, VASA Provider elimina el LUN y deshabilita las IOPS.

Para obtener información sobre cómo gestionar instantáneas de máquinas virtuales, consulta https://techdocs.broadcom.com/["Documentación técnica de Broadcom"].
