---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Debe tener en cuenta algunos de los aspectos que se deben tener en cuenta al migrar las máquinas virtuales existentes en el centro de datos. 
---
= Consideraciones sobre la migración y clonación de máquinas virtuales para ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta algunos de los aspectos que se deben tener en cuenta al migrar las máquinas virtuales existentes en el centro de datos.



== Migrar máquinas virtuales protegidas

Puede migrar las máquinas virtuales protegidas a:

* El mismo almacén de datos vVols en un host ESXi diferente
* Distinto almacén de datos vVols compatible en el mismo host ESXi
* Distinto almacén de datos vVols compatible en un host ESXi diferente


Si migra la máquina virtual a un FlexVol volume diferente, el sistema actualiza el archivo de metadatos de ese volumen con la información de la máquina virtual. Si se migra una máquina virtual a un host ESXi diferente pero al mismo almacenamiento, el archivo de metadatos del FlexVol volume subyacente no se modificará.



== Clonar máquinas virtuales protegidas

Es posible clonar máquinas virtuales protegidas con las siguientes características:

* El mismo contenedor de un mismo volumen FlexVol que utiliza el grupo de replicación
+
El archivo de metadatos del mismo volumen de FlexVol se actualiza con los detalles de la máquina virtual clonada.

* El mismo contenedor de un volumen FlexVol diferente mediante el grupo de replicación
+
Volumen FlexVol donde se coloca la máquina virtual clonada, el archivo de metadatos se actualiza con los detalles de la máquina virtual clonada.

* Diferentes contenedores o almacenes de datos vVols
+
Volumen FlexVol donde se coloca la máquina virtual clonada, el archivo de metadatos se actualiza los detalles de la máquina virtual.



Actualmente, VMware no admite máquinas virtuales clonadas en una plantilla de VM.

Se admite el clonado de clon de una máquina virtual protegida.

Consulte https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Crear una máquina virtual para clonación"] si desea obtener más información.



== Snapshots de máquina virtual

Se admiten instantáneas de máquinas virtuales sin memoria. Si una máquina virtual tiene una instantánea con memoria, la máquina virtual no puede protegerse.

No puedes proteger máquinas virtuales no protegidas que contengan instantáneas de memoria. Elimina las instantáneas de memoria antes de activar la protección para la máquina virtual.

Para una máquina virtual Windows con tipo de almacenamiento ASA r2, las instantáneas de la máquina virtual son de solo lectura. Cuando enciendes la máquina virtual, VASA Provider crea un LUN a partir de la instantánea de solo lectura y habilita las IOPS. Cuando apagas la máquina virtual, VASA Provider elimina el LUN y deshabilita las IOPS.
