---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host 
summary: Monta los almacenes de datos en hosts adicionales tras añadir hosts a tu entorno VMware. 
---
= Monta almacenes de datos NFS y VMFS en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Montar un almacén de datos proporciona acceso al almacenamiento a los hosts adicionales después de añadirlos a tu entorno VMware.


NOTE: Una vez añadido el host, espera a que finalice el proceso de detección programado para que aparezca en ONTAP tools. Como alternativa, puedes ejecutar manualmente la detección desde la pantalla de resumen de NetApp ONTAP tools. Para obtener información sobre cómo añadir un host ESXi a tu clúster de vSphere, consulta https://techdocs.broadcom.com/["Documentación técnica de Broadcom"].

.Acerca de esta tarea
* Algunas acciones de clic con el botón derecho quedan deshabilitadas o no disponibles según la versión del cliente de vSphere y el tipo de almacén de datos seleccionado.
+
** Si utiliza vSphere Client 8,0 o versiones posteriores, algunas de las opciones del botón derecho están ocultas.
** Al pasar de vSphere 7.0U3 a vSphere 8.0, aunque aparecen las opciones, la acción está desactivada.


* vSphere deshabilita la opción de montaje de almacén de datos cuando el clúster host está protegido con configuraciones uniformes.


.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. En el panel de navegación de la izquierda, seleccione los centros de datos que contienen los hosts.
. Para montar almacenes de datos NFS/VMFS en un host o un clúster de hosts, haga clic con el botón derecho y seleccione *Herramientas de NetApp ONTAP * > *Montar almacenes de datos*.
. Seleccione los almacenes de datos que desea montar y seleccione *Mount*.


.El futuro
Puede realizar un seguimiento del progreso en el panel de tareas recientes.

.Tema relacionado
link:../manage/add-vsphere-host.html["Agregar nuevos hosts de VMware vSphere"]
