---
permalink: manage/mount-a-vvols-datastore.html 
sidebar: sidebar 
keywords: mount vVols datastore, add vVol datastore to hosts, ONTAP tools vVol host access, VMware virtual volumes mount 
summary: Monta un datastore de vVols en hosts adicionales para proporcionar acceso al almacenamiento en todo tu entorno virtual. 
---
= Monta un almacén de datos vVols en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puedes montar un almacén de datos de VMware Virtual Volumes (vVols) en uno o varios hosts adicionales para proporcionar acceso al almacenamiento a hosts adicionales. Solo puedes desmontar un almacén de datos de vVols a través de las API a nivel de host. No se admite el desmontaje de almacenes de datos a nivel de clúster.


NOTE: Una vez añadido el host, espera a que finalice el proceso de detección programado para que aparezca en ONTAP tools. Como alternativa, puedes ejecutar manualmente la detección desde la pantalla de resumen de NetApp ONTAP tools. Para obtener información sobre cómo añadir un host ESXi a tu clúster de vSphere, consulta https://techdocs.broadcom.com/["Documentación técnica de Broadcom"].

.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. En el panel de navegación, seleccione el centro de datos que contiene el almacén de datos.
. Haga clic con el botón derecho en el almacén de datos y seleccione *Herramientas de NetApp ONTAP* > *Almacén de datos de montaje*.
. En el cuadro de diálogo *Mount datastores on hosts*, seleccione los hosts en los que desea montar el almacén de datos y, a continuación, seleccione *Mount*.


El panel de tareas recientes muestra el progreso.

.Tema relacionado
link:../manage/add-vsphere-host.html["Agregar nuevos hosts de VMware vSphere"]
