---
permalink: manage/recover-backup.html 
sidebar: sidebar 
keywords: recover ONTAP tools setup, appliance recovery workflow, near zero RPO recovery, restore ONTAP tools configuration 
summary: Recupera las ONTAP tools desde una copia de seguridad y entiende el comportamiento de RPO cero y casi cero según la versión. 
---
= Recupera ONTAP tools for VMware vSphere desde una copia de seguridad
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recupera las herramientas ONTAP para VMware vSphere restaurando un archivo de copia de seguridad almacenado en el datastore. A partir de ONTAP tools for VMware vSphere 10.5, la copia de seguridad está habilitada de forma predeterminada, así que normalmente hay una copia de seguridad reciente disponible si necesitas volver a implementar o recuperar el appliance.

El almacén de datos donde implementas ONTAP tools for VMware vSphere máquinas virtuales almacena los archivos de copia de seguridad. Una carpeta con el nombre de la dirección IP de ONTAP tools almacena los dos archivos de copia de seguridad más recientes (_OTV_backup_1.tar.enc_ y _OTV_backup_2.tar.enc_) y el archivo de información (_OTV_backup_info.txt_), que identifica la copia de seguridad más reciente.

Asegúrese de que la nueva máquina virtual utilice la misma dirección IP de las herramientas ONTAP y coincida con la configuración inicial del sistema, incluidos los servicios habilitados, el tamaño del nodo y el modo HA.

.Pasos
. Descargue los archivos de respaldo del almacén de datos de la máquina virtual original a su sistema local.
+
.. Vaya a la sección de almacenamiento y elija el almacén de datos que contiene los archivos de respaldo de la máquina virtual.
.. Seleccione la sección *Archivos*.
.. Descargue el directorio de respaldo requerido.


. Apague la máquina virtual existente.  Luego, implemente una nueva máquina virtual utilizando el mismo archivo OVA que la implementación original.
. Inicia sesión en el servidor vCenter.
. Localiza la máquina virtual de ONTAP tools recién implementada e inicia la consola web.
. Inicia sesión usando las credenciales de `maint`.
. Ingrese `4` para seleccionar *Soporte y Diagnóstico*.
. Ingrese `2` para seleccionar la opción *Activar acceso a diagnóstico remoto* y crear una nueva contraseña para el acceso de diagnóstico.
. Elija un archivo de respaldo del directorio descargado.  Consulte el archivo _OTV_backup_info.txt_ para identificar la última copia de seguridad.
. Utilice el siguiente comando para transferir el archivo de respaldo a la nueva máquina virtual.  Cuando se le solicite, ingrese la contraseña de diagnóstico.
+
[listing]
----
scp <OTV_backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: No modifiques la ruta de destino ni el nombre del archivo (/home/diag/system_recovery.tar.enc) que se indican en el comando.

. Después de transferir el archivo de respaldo, inicie sesión en el shell de diagnóstico y ejecute el siguiente comando:
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
Los registros se guardan en el archivo _/var/log/otvng/post-deploy-upgrade.log_.



Una vez completada la recuperación, las herramientas de ONTAP restauran los servicios y los objetos de vCenter.
