---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: shrink vVols datastore, remove storage from vVol datastore, ONTAP tools vVol capacity reduction, virtual volumes datastore resize down 
summary: Elimina un almacén de datos vVols solo cuando no queden vVols en el almacén de datos seleccionado. 
---
= Reduce un almacén de datos vVols en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Elimina volúmenes de un almacén de datos vVols en ONTAP tools para reducir la capacidad cuando ya no necesites el almacenamiento adicional.

Utilice la acción "Eliminar almacenamiento del almacén de datos" en cualquier almacén de datos vVols administrado por las herramientas ONTAP en vCenter Server.

No puedes eliminar almacenamiento de un volumen si contiene vVols; la opción de eliminar está desactivada para estos volúmenes. Al eliminar volúmenes del almacén de datos, también tienes la opción de eliminar los volúmenes seleccionados del almacenamiento ONTAP.


NOTE: La operación de reducción del almacén de datos vVols no es compatible con almacenes de datos vVols basados ​​en sistemas ASA r2.

.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. En el panel de navegación, seleccione el centro de datos que contiene el almacén de datos.
. Haz clic con el botón derecho en el almacén de datos vVol y selecciona *NetApp ONTAP tools* > *Remove storage from datastore*.
. Seleccione los volúmenes que no tengan vVols y seleccione *Eliminar*.
+

NOTE: La opción para seleccionar el volumen en el que vVols reside está desactivada.

. En la ventana emergente *Eliminar almacenamiento*, marca la casilla de comprobación *Eliminar volúmenes del clúster ONTAP* para eliminar los volúmenes del datastore y del almacenamiento ONTAP y luego selecciona *Eliminar*.

