---
permalink: manage/reports.html 
sidebar: sidebar 
keywords: ONTAP tools reports, virtual machine reports, datastore reports, VMware storage reporting 
summary: Consulta los informes sobre máquinas virtuales y almacenes de datos en el complemento ONTAP tools. 
---
= Informes de ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento ONTAP tools for VMware vSphere ofrece informes que te ayudan a supervisar las máquinas virtuales y los datastores respaldados por el almacenamiento ONTAP. Para ver estos informes, selecciona el icono del complemento ONTAP tools for VMware vSphere en la sección de accesos directos del cliente vCenter y luego selecciona la pestaña Reports.

El informe «Máquinas virtuales» muestra una lista de las máquinas virtuales detectadas que tienen al menos un disco en un almacén de datos basado en almacenamiento ONTAP, junto con métricas de rendimiento. Al desplegar el registro de la máquina virtual, la interfaz muestra toda la información del almacén de datos relacionada con el disco.

El informe de almacenes de datos muestra los almacenes de datos que detecta ONTAP tools for VMware vSphere y que utilizan almacenamiento ONTAP, junto con las métricas de rendimiento.

Puede utilizar la opción Gestionar columnas para ocultar o mostrar columnas diferentes.
