---
permalink: manage/reports.html 
sidebar: sidebar 
keywords: ONTAP tools reports, virtual machine reports, datastore reports, VMware storage reporting 
summary: Consulta los informes sobre máquinas virtuales y almacenes de datos en el complemento ONTAP tools. 
---
= Informes de ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El complemento ONTAP tools for VMware vSphere ofrece informes que te ayudan a supervisar máquinas virtuales y almacenes de datos respaldados por almacenamiento ONTAP. Para ver los informes, selecciona el icono del complemento ONTAP tools for VMware vSphere en la sección de accesos directos de la vSphere Client y luego selecciona la pestaña *Informes*.

El informe «Máquinas virtuales» muestra una lista de las máquinas virtuales detectadas que tienen al menos un disco en un almacén de datos basado en almacenamiento ONTAP, junto con métricas de rendimiento. Cuando amplías el registro de una máquina virtual, puedes ver toda la información del almacén de datos para sus discos.

El informe de almacenes de datos muestra los almacenes de datos que detecta ONTAP tools for VMware vSphere y que utilizan almacenamiento ONTAP, junto con las métricas de rendimiento.

Puedes utilizar la opción *Manage Columns* para ocultar o mostrar columnas.
