---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Si ha olvidado la contraseña del administrador de herramientas de ONTAP, puede restablecer las credenciales de administrador con el token generado por las herramientas de ONTAP para la consola de mantenimiento de VMware vSphere. 
---
= Restablezca la contraseña del administrador de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si olvida la contraseña del administrador de herramientas de ONTAP , puede restaurar el acceso de administrador mediante un token de restablecimiento generado desde la consola de mantenimiento de ONTAP tools for VMware vSphere .

.Pasos
. Abra un navegador web y navegue hasta `https://<ONTAPtoolsIP>:8443/virtualization/ui/` para acceder al Administrador de herramientas de ONTAP .
. En la página de inicio de sesión, seleccione *Restablecer contraseña*.
. Genere un token de restablecimiento de contraseña utilizando las ONTAP tools for VMware vSphere :
+
.. Inicie sesión en vCenter Server y abra la consola de mantenimiento.
.. Ingresar `2` para seleccionar *Configuración del sistema*.
.. Ingresar `3` para seleccionar *Cambiar contraseña de usuario 'maint'*.


. En el cuadro de diálogo de restablecimiento de contraseña, ingrese el token de restablecimiento, el nombre de usuario y la nueva contraseña.
. Seleccione *Restablecer* para actualizar las credenciales.
. Inicie sesión en el Administrador de herramientas de ONTAP con la nueva contraseña.

