---
permalink: manage/resize-datastores.html 
sidebar: sidebar 
keywords:  
summary: El cambio de tamaño de un almacén de datos permite aumentar el almacenamiento de los archivos de las máquinas virtuales. Es posible cambiar el tamaño de un almacén de datos a medida que cambian los requisitos de infraestructura. 
---
= Redimensiona los almacenes de datos NFS y VMFS en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El cambio de tamaño de un almacén de datos permite aumentar el almacenamiento de los archivos de las máquinas virtuales. Es posible cambiar el tamaño de un almacén de datos a medida que cambian los requisitos de infraestructura.

.Acerca de esta tarea
Puede aumentar el tamaño de los almacenes de datos NFS y VMFS.  Un FlexVol volume en estos almacenes de datos no puede reducirse por debajo de su tamaño actual, pero puede crecer hasta un 120%.

.Pasos
. En la página inicial de vSphere Client, seleccione *Hosts and Clusters*.
. En el panel de navegación, seleccione el centro de datos que contiene el almacén de datos.
. Haga clic con el botón derecho en el almacén de datos NFS o VMFS y seleccione *Herramientas de NetApp ONTAP* > *Cambiar tamaño de almacén de datos*.
. En el cuadro de diálogo Cambiar tamaño, introduzca un nuevo tamaño para el almacén de datos y seleccione *Aceptar*.

