---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords: manage storage backends, ONTAP backend systems, storage backend operations, VMware datastore backend configuration 
summary: Administra los sistemas de almacenamiento que usan los hosts ESXi para almacenar datos. 
---
= Administra los backends de almacenamiento en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los back-ends de almacenamiento son los sistemas que los hosts ESXi utilizan para el almacenamiento de datos.



[[discover-storage]]
== Descubra el almacenamiento

Puede ejecutar el descubrimiento de un backend de almacenamiento a pedido sin esperar a que un descubrimiento programado actualice los detalles de almacenamiento de inmediato.  Para las configuraciones de MetroCluster , ejecute la detección de herramientas ONTAP manualmente después de un cambio.

Siga estos pasos para detectar los back-ends de almacenamiento.

.Pasos
. Inicie sesión en el cliente de vSphere.
. En la página de accesos directos, seleccione *Herramientas de NetApp ONTAP* en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP , vaya a *Backends de almacenamiento* y seleccione un backend de almacenamiento.
. Selecciona el menú de los tres puntos verticales y selecciona *Descubrir almacenamiento*


Puede realizar un seguimiento del progreso en el panel de tareas recientes.



[[modify-storage-backends]]
== Modificar los back-ends de almacenamiento

Puede modificar las credenciales del backend de almacenamiento o el nombre del puerto.  También puede modificar el backend de almacenamiento para clústeres ONTAP globales mediante el Administrador de herramientas ONTAP .  Si el certificado caducará en 30 días o menos, las herramientas ONTAP muestran una advertencia.  Modifique el backend de almacenamiento y cargue el nuevo certificado desde el administrador de ONTAP .

Cuando modifica el back-end de almacenamiento, las ONTAP tools for VMware vSphere realizan una detección del back-end de almacenamiento para actualizar los detalles de almacenamiento.

Siga los pasos de esta sección para modificar un back-end de almacenamiento.

. Inicie sesión en el cliente de vSphere.
. En la página de accesos directos, seleccione *Herramientas de NetApp ONTAP* en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP , vaya a *Backends de almacenamiento* y seleccione un backend de almacenamiento.
. Selecciona el menú de los tres puntos verticales y elige *Modificar* para modificar las credenciales o el nombre del puerto. Puedes seguir el progreso en el panel de tareas recientes.


Modifique los clústeres globales de ONTAP con el Administrador de herramientas de ONTAP de la siguiente manera.

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione los back-ends de almacenamiento en la barra lateral.
. Seleccione el backend de almacenamiento que desea modificar.
. Selecciona el menú de los tres puntos verticales y selecciona *Modificar*.
. Puede modificar las credenciales o el puerto. Introduzca el *Nombre de usuario* y *Contraseña* para modificar el backend de almacenamiento.




[[remove-storage-backends]]
== Retire los back-ends de almacenamiento

Debes eliminar todos los almacenes de datos adjuntos al backend de almacenamiento antes de eliminarlo.  Siga los pasos a continuación para eliminar un backend de almacenamiento.

. Inicie sesión en el cliente de vSphere.
. En la página de accesos directos, seleccione *Herramientas de NetApp ONTAP* en la sección de plugins.
. En el panel izquierdo de las herramientas de ONTAP , vaya a *Backends de almacenamiento* y seleccione un backend de almacenamiento.
. Selecciona el menú de los tres puntos verticales y elige *Eliminar*. Asegúrate de que el backend de almacenamiento no contenga ningún datastore. Puedes seguir el progreso en el panel de tareas recientes.


Puedes eliminar clústeres ONTAP globales usando ONTAP tools Manager.

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione *Backends de almacenamiento* en la barra lateral.
. Seleccione el back-end de almacenamiento que desea quitar
. Selecciona el menú de los tres puntos verticales y selecciona *Eliminar*.




[[drill-down-view-of-storage-backend]]
== Vista detallada del back-end de almacenamiento

La página del backend de almacenamiento enumera todos los backends de almacenamiento.  Puede realizar operaciones de descubrimiento de almacenamiento, modificación y eliminación en los backends de almacenamiento que agregó, pero no en la SVM secundaria individual del clúster.

Seleccione el clúster principal o secundario para ver el resumen del componente.  Para el clúster principal, use el menú desplegable de acciones para descubrir almacenamiento, modificar o eliminar el backend de almacenamiento.

La página de resumen proporciona los siguientes detalles:

* Estado del back-end de almacenamiento
* Información de capacidad
* Información básica acerca de la máquina virtual
* Detalles del certificado, como el estado del certificado y la fecha de vencimiento.
* Información de red como la dirección IP y el puerto de la red.  Para el SVM secundario, la información es la misma que la del backend de almacenamiento principal.
* Privilegios permitidos y restringidos para el backend de almacenamiento. Para el SVM hijo, la información es la misma que para el backend de almacenamiento padre. ONTAP tools muestra los privilegios solo en los backends de almacenamiento basados en cluster. Si añades SVM como backend de almacenamiento, no se muestra la información de privilegios.
* La vista detallada del clúster del sistema ASA r2 no incluye la pestaña de niveles locales cuando la propiedad desagregada está configurada como "verdadera" para la SVM o el clúster.
* Para los sistemas de SVM R2 de ASA, no se muestra el portlet de capacidad. El portal de capacidad solo es necesario cuando la propiedad desagregada se establece como «true» para la SVM o el clúster.
* Para los sistemas ASA R2 SVM, la sección de información básica muestra el tipo de plataforma.


La pestaña Interfaz proporciona información detallada sobre la interfaz.

La pestaña de niveles locales proporciona información detallada sobre la lista de agregados.
