---
permalink: manage/uninstall-deployment.html 
sidebar: sidebar 
keywords: uninstall ONTAP tools, remove ONTAP tools deployment, appliance decommission workflow, graceful deployment termination 
summary: Finaliza tu implementación de ONTAP tools for VMware vSphere de forma controlada. 
---
= Desinstala tus ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Desinstalar ONTAP tools for VMware vSphere elimina los datos del appliance, así que sigue estos pasos para apagar la implementación de forma controlada y evitar una pérdida inesperada de datos.

.Pasos
. Quita o mueve todas las máquinas virtuales desde las herramientas de ONTAP para almacenes de datos gestionados de VMware vSphere.
+
** Para eliminar las máquinas virtuales, consulte https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Elimine y vuelva a registrar máquinas virtuales y plantillas de máquinas virtuales"]
** Para trasladarlas a un almacén de datos no gestionado, consulta https://techdocs.broadcom.com/["Documentación técnica de Broadcom"] para migrar máquinas virtuales con Storage vMotion


. link:../manage/delete-ds.html["Eliminar almacenes de datos"] Creado en herramientas de ONTAP para VMware vSphere.
. Si has habilitado el proveedor VASA, selecciona *Settings* > *VASA Provider settings* > *Unregister* en ONTAP tools para dar de baja el proveedor VASA de todas las instancias de vCenter Server.
. Quite el adaptador de SRA de VMware Live Site Recovery:
+
.. Inicie sesión como administrador en la interfaz de gestión del dispositivo VMware Live Site Recovery mediante el puerto 5480.
.. Seleccione *Adaptadores de replicación de almacenamiento*.
.. Seleccione la tarjeta SRA apropiada y, en el menú desplegable, seleccione *Eliminar*.
.. Confirme que conoce los resultados de eliminar el adaptador y seleccione *Eliminar*.


. Elimina las instancias de vCenter Server integradas en ONTAP tools for VMware vSphere. Consulta link:../manage/manage-vcenter.html["Gestione instancias de vCenter Server"].
+
Al eliminar una instancia de vCenter Server, las herramientas de ONTAP pueden guiarte durante la limpieza necesaria. Si se te solicita en el cuadro de diálogo *Eliminar vCenter*, selecciona *Eliminar todos los artefactos de almacenamiento de este vCenter Server* y *Entiendo que los datastores asociados ya no serán gestionados por las herramientas de ONTAP* y, a continuación, selecciona *Forzar eliminación*.

+
Antes de usar *Force delete*, asegúrate de que se hayan eliminado o migrado todos los almacenes de datos de vVols, de que todos los almacenes de datos protegidos estén desprotegidos y de que no haya ninguna tarea de detección en ejecución.

+
Si no se puede acceder al servidor vCenter durante el proceso de eliminación, ONTAP tools solo elimina el registro del servidor vCenter. Debes anular manualmente el registro del complemento de VMware vCenter Server.

. Apague las herramientas de ONTAP para máquinas virtuales de VMware vSphere desde vCenter Server y elimine las máquinas virtuales.


.¿Cuál es el siguiente?
link:../manage/delete-deployment.html["Quite volúmenes FlexVol"]
