---
permalink: manage/uninstall-deployment.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Siga las instrucciones de esta sección para terminar sin problemas las herramientas de ONTAP para la puesta en marcha de VMware vSphere. 
---
= Desinstale la puesta en marcha de herramientas de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al desinstalar las herramientas de ONTAP para VMware vSphere se eliminan todos los datos de las herramientas.

.Pasos
. Elimine todas las máquinas virtuales de almacenes de datos gestionados por las herramientas de ONTAP para VMware vSphere. Puede eliminarlos (consulte https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Eliminar y volver a registrar máquinas virtuales y plantillas de máquinas virtuales"] ) o utilizarlos https://techdocs.broadcom.com/it/it/vmware-cis/vsphere/vsphere/8-0/vcenter-and-host-management-8-0/migrating-virtual-machines-host-management/migration-with-vmotion-host-management/migration-with-storage-vmotion-host-management.html["VMotion de almacenamiento"] para moverlos a un almacén de datos no gestionado.
. link:../manage/delete-ds.html["Eliminar almacenes de datos"] Creado en herramientas de ONTAP para VMware vSphere.
. Cancele el registro de los proveedores VASA de todos los servidores vCenter mediante los pasos siguientes:
+
.. En las herramientas de ONTAP, seleccione *Configuración* > *Configuración del proveedor VASA* > *Anular registro* en la parte inferior de la pantalla.
.. En la página *Unregister VASA Provider*, proporcione las credenciales de usuario de la aplicación y seleccione *Unregister*.


. Desasocie todos los back-ends de almacenamiento de la instancia de vCenter Server. Consulte link:../manage/manage-vcenter.html["Asocie o disocie los back-ends de almacenamiento con la instancia de vCenter Server"].
. Elimine todos los back-ends de almacenamiento. Consulte link:../manage/storage-backend.html["Gestione los back-ends de almacenamiento"].
. Quitar el adaptador de SRA de VMware Live Site Recovery:
+
.. Inicie sesión en la interfaz de gestión del dispositivo VMware Live Site Recovery usando el puerto 5480 como administrador.
.. Seleccione *Adaptadores de replicación de almacenamiento*.
.. Seleccione la tarjeta SRA apropiada y, en el menú desplegable, seleccione *Eliminar*.
.. Confirme que conoce los resultados de eliminar el adaptador y seleccione *Eliminar*.


. Elimine todas las instancias del servidor de vCenter incorporadas a las herramientas de ONTAP para VMware vSphere. Consulte link:../manage/manage-vcenter.html["Gestione instancias de vCenter Server"].
. Apague las herramientas de ONTAP para máquinas virtuales VMware vSphere desde vCenter Server y elimine las máquinas virtuales.

