---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: La acción del almacén de datos desmonta un almacén de datos NFS o VMFS de los hosts ESXi. La acción de desmontaje del almacén de datos se habilita para los almacenes de datos NFS y VMFS que las herramientas de ONTAP para VMware vSphere detectan o gestionan. 
---
= Desmonta los almacenes de datos NFS y VMFS en ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La acción Desmontar almacén de datos elimina un almacén de datos NFS o VMFS de los hosts ESXi.  Está disponible para almacenes de datos descubiertos o administrados por las ONTAP tools for VMware vSphere.

.Pasos
. Inicie sesión en el cliente de vSphere.
. Haga clic con el botón derecho en un objeto de almacén de datos NFS o VMFS y seleccione *Desmontar almacén de datos*.
+
El cliente vSphere abre un cuadro de diálogo y muestra una lista de los hosts ESXi que montan el almacén de datos. Cuando la operación se realiza en un almacén de datos protegido, se muestra un mensaje de advertencia en la pantalla.

. Seleccione uno o varios hosts ESXi para desmontar el almacén de datos.
+
No es posible desmontar el almacén de datos de todos los hosts. La interfaz de usuario sugiere que se utilice la operación de eliminación del almacén de datos en su lugar.

. Seleccione el botón *Desmontar*.
+
Si el almacén de datos forma parte de un clúster de hosts protegido, se muestra un mensaje de advertencia.




NOTE: Si se desmonta el almacén de datos protegido, la configuración de protección existente podría resultar en una protección parcial. Consulte link:../manage/edit-hostcluster-protection.html["Modifique el clúster de hosts protegido"] para permitir una protección completa.

.El futuro
Puede realizar un seguimiento del progreso en el panel de tareas recientes.
