---
permalink: manage/update-proxyurl.html 
sidebar: sidebar 
keywords:  
summary: 'Puede recopilar archivos de registro para las herramientas de ONTAP para VMware vSphere desde las opciones disponibles en las herramientas de ONTAP para la interfaz gráfica de usuario de VMware vSphere \(GUI\). Es posible que el soporte técnico le solicite recoger los archivos de registro que sirven como ayuda para la solución de un problema.' 
---
= Actualice la URL del proxy de AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Actualice la URL del proxy de AutoSupport para garantizar el funcionamiento correcto de la función AutoSupport en los casos en los que se utilice un servidor proxy para el control de acceso a la red o las medidas de seguridad. Permite que los datos de AutoSupport se enruten a través del proxy adecuado, lo que permite una transmisión segura y el cumplimiento de normativas.

.Pasos
. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Selecciona *Ajustes* en la barra lateral.
. Seleccione la opción *Ajustes* > *Telemetría* > *Editar*.
. Introduzca una *URL de proxy* válida y guarde los cambios.
+
Si deshabilita AutoSupport, la URL del proxy también se deshabilita.


