---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: Puede actualizar las credenciales de vCenter Server y ONTAP con la consola de mantenimiento. 
---
= Actualice las credenciales de vCenter Server y ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar la instancia de vCenter Server y las credenciales de ONTAP con la consola de mantenimiento.

*Lo que necesitará*

Debe tener credenciales de inicio de sesión de usuario de mantenimiento.

*Acerca de esta tarea*

Si cambió las credenciales de vCenter Server, ONTAP o Data LIF después de la puesta en marcha, deberá actualizar las credenciales con este procedimiento.

* Pasos*

. En vCenter Server, abra una consola al proveedor VASA.
. Inicie sesión como el usuario de mantenimiento.
. Introduzca `4` Para seleccionar Support and Diagnostics.
. Introduzca `1` Para seleccionar el shell de diagnóstico de Access.
. Introduzca `y` para continuar.
. Actualice las credenciales según sea necesario:
+
.. Para actualizar las credenciales de ONTAP, ejecute el comando:
+
--
otv-update --ontapUsername <new username> --ontapPassword <new password>

--
.. Para actualizar las credenciales de vCenter, ejecute el comando:
+
--
otv-update --vcenterUsername <new username> --vcenterPassword <new password>

--
.. Para actualizar la LIF de datos ejecute el comando:
+
--
otv-update --dataLif <new Datalif IP>

--



